### ISSUE TITLE
Pulizia repository

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#1]
Vorrei togliere codice non nostro da repository principlamente:

tutto il codice di ELGG salvo configurazion i
la libreria SLIM.

Anche se vorrei comunque laciare un modo per deployare facilmente la piattaforma a partire dal codice versionato.

Magari con uno script di build che deve:

Copiare plugin elgg in cartella , copiare configurazioni particolari. Installazione seria SLIM. Script database.

**Comment by Panciz** [comment]
Rimane da pulire parte ELGG

**Comment by coder-molok** [comment]
Ciao, questo è da considerare il repo di deploy, quindi è giusto che abbia
tutto.
Per le singole modifiche potete gestirvi dei branche o repository
"ridotti", per me è indifferente.

M

Il giovedì 22 gennaio 2015, Davide Poletti <notifications@github.com> ha
scritto:
> Rimane da pulire parte ELGG
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/-nA4Vv15eAVKwKyEQVqGTJrF8yerm8WSeiLCe7sHtcA-4H44RUuVs-cDhW2QksyqhTEfE849J2zK0dTHZrunswyYdSvFs80AwQliBIUItl1r8Nqno4rOV3oty1b62-N1bFj_uwT7SoZCiuRyVJ8Nt7geWnzBfQ=s0-d-e1-ft#https://github.com/notifications/beacon/AH--r25B2rpUp7n_pM4c1SndT5LDkNHAks5nkDVdgaJpZM4DUmtH.gif
>
