### ISSUE TITLE
Gestire logging

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#10]
Migliorare il log dell'applicazione valutare un framework php per il logging.

**Comment by predorock** [comment]
Monolog
https://github.com/Seldaek/monolog
Slim-Monolog
https://github.com/Flynsarmy/Slim-Monolog

**Comment by Panciz** [comment]
Perfetto se le conosci e riesci a configurarle per entrambi i moduli sarebbe perfetto.

**Comment by predorock** [comment]
Le metto nel composer.json e poi configuro

**Comment by Panciz** [comment]
si e' scelto di usare per la parte API monolog.
