### ISSUE TITLE
Invio email di registrazione

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#100]
Non ricevo la mail di registrazione:
Username: Tommy
Nome visualizzato: Tommy_bis

**Comment by SimoSca** [comment]
Questo perchè lato server non l'abbiamo ancora configurata.
Avete già una mail ufficiale per il sito?

**Comment by DDDamage** [comment]
Devi chiedere a @coder-molok

**Comment by coder-molok** [comment]
Possiamo usare l'account collegato al dominio foowd.eu per ora.
Ti invio i parametri prima possibile.

**Comment by SimoSca** [comment]
@coder-molok :+1:

**Comment by coder-molok** [comment]
Parametri posta utilizzabili per test

Nome casella principale: info@foowd.eu

Nome account: foowd.eu
Password: ohsoofup
Server posta in uscita (SMTP): mail.foowd.eu
Server posta in ingresso (POP3/IMAP): pop.foowd.eu

Nota che il server SMTP funziona attraverso username e password, si dovra'
quindi impostare il client di posta elettronica per l'autenticazione SMTP.

Dimmi se serve altro

M
Il 22/lug/2015 09:45, "Simone S." <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
appena impostati, thanks!
