### ISSUE TITLE
Barra navigazione - pulsante "altro/tre linee"

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#101]
Il pulsante in alto a dx con le tre linette deve far abbassare una tendina scura (come da progetto grafico), in cui metteremo diversi link. Non è tanto importante che i link siano attivi da ora perchè questo spazio lo usiamo per correggere aspetti della user experience dopo i test.

Però è importante che ci sia l'elemento con lo spazio per inserire alcuni elementi che non compaiono da altre parti:
-FAQ (documento che forniremo/guida sul sito, cioè toggle messaggi di spiegazione su diversi elementi)
-Inizia a vendere (possibilità di modificare la registrazione inserendo i campi da offerente)
![navigazione pulsante](https://cloud.githubusercontent.com/assets/13355694/8796528/b273db5c-2f95-11e5-81cd-7afb9a797fa6.png)

**Comment by Panciz** [comment]
vedi https://github.com/coder-molok/foowd_alpha2/issues/78
