### ISSUE TITLE
Richesta password smarrita

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#103]
Nelle mie innumerevoli registrazioni (e a caso) nn ricordo la password username di nessuna.
Ho quindi provato a richiedere la password via mail (essendo ho usato tutte quelle in mio possesso non potevo sbagliare)

Una volta inviata la richiesta, però, mi manda al wall e non ricevo alcuna mail
![pass smarrita](https://cloud.githubusercontent.com/assets/13355694/8796645/a6c18efc-2f96-11e5-866d-7d5b7f277428.png)

**Comment by SimoSca** [comment]
vedi [commento iss#100](https://github.com/coder-molok/foowd_alpha2/issues/100#issuecomment-123291500)

**Comment by SimoSca** [comment]
Dato che le vecchie richieste non erano andate a buon fine, di fatto le email non venivano salvate da elgg e pertanto ne risultava impossibile il recupero.
Ora con le email validate funziona.
