### ISSUE TITLE
Registrazione - campo mancante

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#105]
Non ricordo se ne avevo discusso con @Panciz.. Ma avevo pensato di mettere l'inserimento del codice fiscale per evitare scummate.

Considerando che qui si tratta di gruppi di acquisto e quindi scambi di merce e denaro senza applicazione di iva (all'interno del gruppo), sarebbe meglio far inserire il codice fiscale ad ogni utente.

Casomai valutiamo se ha un effetto negativo in sede di test della user experience.

**Comment by Panciz** [comment]
Ma stai parlando per tutti i clienti?

Se lo devi inserire per discriminare utenti veri dai falsi solo il codice Fiscale non basta. Dovresti validarlo con nome cognome luogo e data nascita per capire se è valido.

Altrimenti uno inserisce AAABBB99P22AAXXX e di per se potrebbe essere un codice valido.

**Comment by Panciz** [comment]
a maggior ragione se non si vuole fare inserire neanche il nome (vedi https://github.com/coder-molok/foowd_alpha2/issues/105). il C.F. per gli utenti normali mi sembra estageto.

**Comment by DDDamage** [comment]
Avevo in mente ebay che me l'ha fatto inserire quando mi sono registrato.
Dici che non ha senso preoccuparsi di utenti fasulli? Magari già il resto delle funzionalità serve a scremare (soprattutto riguardo alle amicizie)

**Comment by Panciz** [comment]
beh possiamo per l'inizio prevenire gli  utenti bot mettendo i [CAPTCHA](https://it.wikipedia.org/wiki/CAPTCHA) (dovrebbe esistere un plugin elgg penso) .

Ma per il resto all'inizio non metterei altro.

**Comment by DDDamage** [comment]
Ok
