### ISSUE TITLE
Registrazione - campo doppio?

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#106]
Non comprendo la funzione di avere un doppio campo per il nome dell'utente. Non crea confusione?

Se possibile, direi di unificare i due campi in un solo username, che poi è quello visualizzato.
![registrazione campi2](https://cloud.githubusercontent.com/assets/13355694/8796856/4f45fb8e-2f98-11e5-88ec-aac8509ec1f5.png)

**Comment by SimoSca** [comment]
Quelli sono i dati della registrazione standard di elgg: alcuni plugin visualizzano un dato, ed altri visualizzano l'atro. Anche a me sembra una forzatura.
Per non perdere la registrazione standard, posso fare in modo che venga richiesto solo lo Username, e forzare la mano facendo in modo che il nome visualizzato combaci con lo username.

**Comment by DDDamage** [comment]
Se si può fare sarebbe meglio.
Non so su cosa elgg faccia il controllo per capire se lo stesso nome utente è già utilizzato

**Comment by coder-molok** [comment]
Deve essere username.
Nome visualizzato serve a potermi "presentare" come "Marco Colombo" quando
lo username è molok837.

Tutto qui.

M
Il 21/lug/2015 16:27, "DDDamage" <notifications@github.com> ha scritto:

**Comment by Panciz** [comment]
Non credo che sia un problema toglierlo ma a me sembra una cosa normale che ci sia lo username univoco per utente e il nome visualizzaile che puo essere uguale a quello di un altro utente. Sarà che di Poletti e o di Davide ce ne sono 100.000 ma mi capita spesso che il nome utente composto da parti di nome e cognome sia in uso. Mi fa piacere che a volte nonostante io utilizzzi un nick a caso si possa sapere il mio nome vero.

**Comment by DDDamage** [comment]
..ok è una scelta possiamo lasciarlo così.
Non l'ho segnalato come bug proprio per questo. Cmq negli altri social simili (es. pinterest/instagram) viene visualizzato sono lo username anche se fittizio.

Se volete lasciamo la questione in sospeso fino ai test sulla user exp
