### ISSUE TITLE
Registrazione - crop immagini

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#107]
Il crop delle immagini è quadrato. 

Serve vedere il funzionamento della pagina del produttore per capire se queste immagini hanno qualche requisito particolare.

![registrazione crop](https://cloud.githubusercontent.com/assets/13355694/8796940/becd149c-2f98-11e5-80fa-4e1e3a4af819.png)

**Comment by SimoSca** [comment]
esatto: per comodità attualmente lo sto tenendo quadrato, ma non appena saranno chiari i vincoli sarà mio piacere modificarlo.

**Comment by DDDamage** [comment]
Ok facciamo un crop orizzontale con proporzione 5:3
