### ISSUE TITLE
Registrazione descrizione - funzioni da eliminare

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#108]
Ci sono alcune funzioni a disposizione per la descrizione dell'azienda che sono ridondanti e potrebbero generare confusione oltre ad utilizzi impropri.

Mi riferisco a:
- testo barrato
- inserisci link
- inserisci immagine

Soprattutto riferendosi al secondo e terzo punto, sono funzioni già incasellate negli altri campi.

![registrazione descrizione1](https://cloud.githubusercontent.com/assets/13355694/8797007/2354024a-2f99-11e5-85d6-12b88bf53af2.png)

![registrazione descrizione2](https://cloud.githubusercontent.com/assets/13355694/8797025/3f61247c-2f99-11e5-946b-962be8ea05f6.png)

**Comment by SimoSca** [comment]
Quello è un campo di elgg: devo vedere fino a che punto quelle configurazioni sono personalizzabili.

In ogni caso grazie per la issue: questo dettaglio non l'avevo ancora testato.

**Comment by DDDamage** [comment]
Oggi inserendo altre inserzioni ho notato che anche le funzioni incolla non sono il massimo. Si potrebbe eliminare in toto tutta la barra lasciando solo la formattazione.

Cambio in enhancement
