### ISSUE TITLE
Registrazione - campi inserimento immagini

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#109]
Deve essere oblbigatorio inserire almeno un'immagine (altrimenti la pagina del produttore nn ha una copertina).

Le immagini ulteriori sono facoltative, direi che i campi possono comparire di volta in volta ogni immagine aggiunta.
![registrazione descrizione3](https://cloud.githubusercontent.com/assets/13355694/8797094/99509332-2f99-11e5-8e2a-d172845a0f5f.png)

**Comment by SimoSca** [comment]
sto proprio implementando la comparsa ad ogni immagine aggiunta.
