### ISSUE TITLE
Parametro URL api offerte

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#11]
Inserire l'url radice dell servizio REST api Offerte come parametro fisso di installazione allo start del plugin.

vedi http://reference.elgg.org/1.9/configuration_8php.html#a63430a41ff8276441e36fcfd441eb4e5

**Comment by Panciz** [comment]
Con il commit https://github.com/coder-molok/foowd_alpha2/commit/2b9a4c3893c75118bf97e9eecbfd63c86d0c437d in aprte la problematica e' stata risolta da Simone.

Ora il parametro e' fissato nella classe [Param.php](https://github.com/coder-molok/foowd_alpha2/blob/f41012609d0c0d1742f0f7c2eceeaaf22735ad98/mod_elgg/foowd_offerte/classes/Foowd/Param.php) .

L'ideale sarebbe metterlo come settings del plugin  vedi http://learn.elgg.org/en/1.10/guides/settings.html

**Comment by SimoSca** [comment]
Risolta: ora l'url del servizio API è impostabile dal pannello di amministrazione.
