### ISSUE TITLE
Reset db

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#110]
Potreste resettarmi il database? ..devo registrarmi di nuovo per fare altre prove ma non ho più mail..

**Comment by Panciz** [comment]
Non credo che sia necessario resettare l'utente. Basta loggarsi come amministratore e usare la funzione specifica.

http://blog.arvixe.com/how-to-properly-delete-users-in-elgg/

Appena mi procuro una login da amministratore cancelllo gli utenti.

Davide

**Comment by SimoSca** [comment]
@DDDamage hai provato a rieffettuare la registrazione con i vecchi indirizzi mail? 
Ho controllato nel pannello d'amministrazione di elgg ed in teoria dovresti essere in grado di registrarti anche con indirizzi che avevi già testato, in quanto non confermati e da me cancellati.

Pertanto riprova a svolgere una registrazione e se trovi qualche errore ti chiedo di segnalarlo assegnando il bug direttamente a me.

**Comment by Panciz** [comment]
mi sono connesso ora e ho rimosso tutti gli utenti tranne io simone e predari.

**Comment by DDDamage** [comment]
Ok va bene, le offerte potete pure lasciarle ne creo altre
