### ISSUE TITLE
Board - Link menù a tendina comparsi in basso

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#112]
Credo sia un bug dovuto al fatto che la parte della tendina scura (le tre linette) fosse in modifica mentre stavo navigando.

Infatti fino a poco prima schiacciando sul tasto in alto a destra non compariva niente, poi è comparso questo bug infine la tendina visualizzata correttamente.

Se non si dovesse presentare più, chiudete pure questa issue
![board1](https://cloud.githubusercontent.com/assets/13355694/8986472/a735fab0-36dc-11e5-908b-b321b7988ce2.png)

**Comment by predorock** [comment]
E un errore dovuto al caricamento lento della pagina, di norma non compare
