### ISSUE TITLE
Profilo non trovato.

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#114]
Utente: tommy_test
Sono loggato e riesce ad accedere al mio board

Se provo ad accedere alla pagina profilo, però, mi restitisce la seguente pagina d'errore:
![profilo1](https://cloud.githubusercontent.com/assets/13355694/8986638/581e1d08-36dd-11e5-8e7d-518b5f58d27a.png)

**Comment by predorock** [comment]
Cambiamento fatto oggi. Ci sta lavorando Simone
