### ISSUE TITLE
Pagina produttore - immagini nel carousel non corrispondenti

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#117]
Il carousel carica immagini di base non corrispondenti a quelle inserite in fase di registrazione.

![produttore1](https://cloud.githubusercontent.com/assets/13355694/8986880/903a42a6-36de-11e5-8a3f-bef0089a2921.png)
![produttore1b](https://cloud.githubusercontent.com/assets/13355694/8986888/98c7f38c-36de-11e5-872b-d50df88b7159.png)

**Comment by predorock** [comment]
Avete deciso come devono essere caricate le immagini ? Non saprei come impostarlo altrimenti.

**Comment by SimoSca** [comment]
Questa parte blocca in parte anche me poichè attualmente le immagini ivi utilizzate sono quelle immesse e croppate durante la registrazione: conoscendo i formati posso anche impostare il crop opportunamente.

**Comment by DDDamage** [comment]
Vedi #107

**Comment by DDDamage** [comment]
Il problema ha cambiato forma.

Le immagini che compaiono nel carousel sono le stesse per tutti gli utenti
![carousel2](https://cloud.githubusercontent.com/assets/13355694/9960510/5683094e-5e1b-11e5-81b4-c30f326523ae.png)
![carousel1](https://cloud.githubusercontent.com/assets/13355694/9960511/568a25d0-5e1b-11e5-8339-220011fdb4db.png)

**Comment by DDDamage** [comment]
Questa issue va risolta al più presto e messa in produzione, per poter testare la navigazione tra le pagine dei produttori

**Comment by coder-molok** [comment]
Se non si riesce a risolvere, per ora va tolto il carusel !!!

**Comment by DDDamage** [comment]
Momentaneamente risolto dall'esclusione della pagina produttore
