### ISSUE TITLE
Pagina produttore - caratteri non caricati

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#118]
Nella descrizione compaiono delle stringhe al posto di segni di punteggiatura e caratteri accentati.
Inoltre compaiono <p> e </p> a inizio e fine del paragrafo
![produttore2](https://cloud.githubusercontent.com/assets/13355694/8986952/daaee5f8-36de-11e5-8c8d-4a3581681d33.png)

**Comment by predorock** [comment]
Aggiorna o cambia il tuo browser web

**Comment by DDDamage** [comment]
Non credo sia un problema del browser.. comunque adesso non riesco più a visualizzare la pagina. Vedi #123
