### ISSUE TITLE
Form inserimento Offerta

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#12]
Creare form in ELGG per l'inserimento dell'offerta.

Il form impletemntato all'interno del mod foowd_offerte dovre richiamare la funzione REST delle API offerte per inserire nel DB l'offerta.

In particolare usare gli strumenti action/form di ELGG. http://learn.elgg.org/en/1.10/guides/actions.html

L'interfaccia anche se semplice deve crcare di implementare un minimo di validazione sul formato.

In caso di inserimento andato a buion fine o di errore si dovrea mostrare un errore adeguato.

La validazione dovra' gia in parte essere fatta da ELGG in modo da dare una risposta immedita all'utente prima dell'invio.
In ogni caso la validazione fatta dalle API deve impedire l'inserimento di dati non consistenti.

**Comment by SimoSca** [comment]
Anche se poco estetico, è già possibile testarlo: in fondo alla pagina foowd_offerte/all cliccare sul pulsante crea, e procedere.

**Comment by SimoSca** [comment]
Anche se poco estetico, è già possibile testarlo: in fondo alla pagina foowd_offerte/all cliccare sul pulsante crea, e procedere.

PS: l'avevo chiusa per sbaglio, sorry.

**Comment by Panciz** [comment]
Aggiungere un link a questo form dalla pagina personale utente se e' di tipo produttore

**Comment by SimoSca** [comment]
Appena corretta: attualmente le tipologie sono "standard" e "offerente". I nomi non mi soddisfano, ma lascio scegliere a te.
Per semplicità il pulsante è visualizzabile nella sidebar dell'utente.
