### ISSUE TITLE
Wall - area del tasto "cuore"

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#121]
L'area del tasto è piuttosto ridotta al centro e vicino al cuore che compare.
L'ideale sarebbe mettere un'area di interazione grande come tutta l'immagine

Attenzione però a non sovrapporla ai tasti "dettaglio prodotto" e "produttore", per evitare interazioni.
![wall2](https://cloud.githubusercontent.com/assets/13355694/8987173/fdac7d08-36df-11e5-8237-22324a10c6dc.png)
![wall2b](https://cloud.githubusercontent.com/assets/13355694/8987174/fdaf2a94-36df-11e5-92f3-15a0bf0f6c0c.png)

**Comment by predorock** [comment]
dato che la dimensione delle immagini è dinamica, fare un area click larga tutta la dimensione dell'immagine risultava più complicato e più lungo da scrivere.

**Comment by DDDamage** [comment]
Ok lo lascio come enhancement
