### ISSUE TITLE
Wall - caricamento pagina ad ogni click

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#122]
All'espressione di una singola preferenza la pagina viene ricaricata. Così facendo la posizione delle immagini cambia rendendo difficile ricliccare nello stesso punto per aggiungere preferenze ulteriori. Non è possibile aggiornare solo il campo dell'offerta senza interagire con tutta la pagina?

![wall3](https://cloud.githubusercontent.com/assets/13355694/8987269/70c73238-36e0-11e5-9c93-4019f76fa3d8.png)
![wall3b](https://cloud.githubusercontent.com/assets/13355694/8989467/be6a1206-36ec-11e5-91f7-da79bb546676.png)

**Comment by predorock** [comment]
La generazione delle dimensioni delle immagini e casuale. Quindi se vuoi la stessa dimensione dopo il la ricarica della pagina, o si decide la dimensione delle immagini a priori, oppure resta così(dovrei ricambiare lo script dell'aggiunta preferenza da capo)

**Comment by DDDamage** [comment]
Quindi la causa è lo script di aggiunta preferenza, che ricarica la pagina.

Decidere la dimensione a priori non si può fare, va bene come l'avete fatto ora. Soprattutto considerando la possibilità di mettere filtri e ordinamento del wall.

**Comment by predorock** [comment]
Soluzione che si potrebbe mettere forse nella fase 2, però valutate voi per me è uguale.
Nel momento dell'inserimento dell'offerta inserire un radio button per decidere come deve essere mostrata l'immagine dell'offerta. Questa coa richiese un po di righe di codice, quindi è da valutare, sicuramente per la fase successiva.

**Comment by predorock** [comment]
Sistemato l'algoritmo.
