### ISSUE TITLE
Wall - eliminare vecchie offerte

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#124]
Le vecchie offerte (dalla 1 alla 9) sono buggate in tutte le pagine in cui si presentano, vanno eliminate altrimenti rischio di segnalare problemi che non sono delle pagine in questione.

LASCIARE OFFERTE 10 11 e 12

**Comment by Panciz** [comment]
Ho cancellato brutalmente le offerte. Non essendoci preferenze espresse collegate e' stato semplice.
Ho fatto semplicemente le delete su la tabella offer. spero di non aver creato incongruenze.
