### ISSUE TITLE
Inserimento offerte - copia incolla in campo descrizione

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#127]
Su alcuni testi copiaincollati ci sono degli errori di formattazione.

Ho copiaincollato la descrizione da questo sito:
http://www.vinoecibo.it/commenti/amenita/finocchiona--salume-traditore--per-chi-non-lo-conosce.html
Ho provato ad incollare su txt e compariva del codice relativo ad un'immagine incorporata.

Il risultato è questo nella schermata di inserimento:
![incolla testo formattazione1](https://cloud.githubusercontent.com/assets/13355694/9960039/788fc75a-5e18-11e5-87df-d2bce30e4d07.png)

Che poi rimane anche nel riepilogo: 
![incolla testo formattazione3](https://cloud.githubusercontent.com/assets/13355694/9960038/788a51a8-5e18-11e5-8385-a36c8608e5cc.png)

E nella pagina di dettaglio del prodotto:
![incolla testo formattazione2](https://cloud.githubusercontent.com/assets/13355694/9960040/7893f974-5e18-11e5-9caa-e269ae3dd05b.png)

Lo stesso bug potrebbe causare questo copiaincolla di testo invisibile:
![incolla testo1](https://cloud.githubusercontent.com/assets/13355694/9960119/f2912b34-5e18-11e5-8536-7cacff37a78e.png)
![incolla testo2](https://cloud.githubusercontent.com/assets/13355694/9960123/ffeae374-5e18-11e5-8acc-7ce7e78fbdc0.png)

**Comment by Panciz** [comment]
In realta' la possibilita' di inserire testo formattato e' un plus di quel componente. Cliccando in alto e passando da modalita' normale o html si puo inserire anche testo non formattato.

**Comment by DDDamage** [comment]
Dimensione e colore non dovrebbero essere modificabili..
A me spesso nei form su altri siti capita che incollando del testo mi cancella qualsiasi formattazione.

Potremmo risolverla così che sarebbe la cosa più semplice?

**Comment by SimoSca** [comment]
Vuoi rimuovere la formattazione solo su quello che viene incollato, o su tutto il testo, incluso quello che vi era anche prima dell'operazione di "incolla" ?

Se e' solo per la parte incollata, l'ho appena risolto.

**Comment by SimoSca** [comment]
@DDDamage 

l'utente puo' inserire dei tuoi tag html o puo' inserire solo testo semplice?

Io personalmente suggerirei l'inserimento di testo semplice, in quanto un utente con un minimo di conoscenza di html potrebbe iniziare a scrivere testi colorati e caratteri molto grandi per far risaltare l'offerta.

**Comment by coder-molok** [comment]
Sì, iniziamo con testo semplice. Metti in encode tutti i caratteri
particolari.
Il 24/ott/2015 13:10, "Simone S." <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
@coder-molok 

Per capirci:
vuoi che i caratteri particolari vengano visualizzati e incollati normalmente e salvati nel DB con la loro codifica? 

esempio:

& <p>saluto</p> <br>

durante l'immissione della descrizione cancellare tutti i tag (<p>, </p> e <br>) ma lasciare la visualizzazione normale della "&" in modo che la frase risulti essere solamente

& saluto 

e poi salvare nel DB la codifica:

&amp; saluto

magari sostituendo i newline (\n) con degli a capo html : <br> ?

**Comment by coder-molok** [comment]
Non ho capito bene tutta la tua esposizione perchè il client credo abbia
mascherato alcuni caratteri.

Molto semplicemente intendevo che, se un utente inserisce : "vino < b >
buono <  /b >" dobbiamo scrivere nell'html la codifica "vino & lt; b & gt;
buono & lt; /b & gt;"
(Ho messo spazi qua e la per evitare mascheramenti automatici)

Vanno intercettati i 5 caratteri speciali xml: < > & " '
E convertiti nelle relative entity prima di finire sulla pagina.

A db possono stare come ci è più comodo.

M

**Comment by SimoSca** [comment]
Per "pagina" intendi la pagina del prodotto, non il form stesso in cui inserisci la descrizione, giusto?

In ogni caso proporrei di limitare l'inserimento dei tag, concedendo solamente <b>, <i>, <p>, <u>, <br> e rispettive chiusure.

**Comment by DDDamage** [comment]
Da riaprire se si ripresenta il problema
