### ISSUE TITLE
Inserimento offerte - messaggio quantità massima

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#128]
Se provo ad inserire la quantià massima dell'ordine prima della quantità minima, il numero che scrivo viene automaticamente cancellato e mi restituisce questo messaggio:
![quantita massima](https://cloud.githubusercontent.com/assets/13355694/9991318/5d7879b4-6069-11e5-96a7-26fdb81bf134.png)
Dovrebbe essere "devi prima inserire una quantità MINIMA"

Quindi fa un controllo prima dell'invio del modulo (è davvero necessario?)
Avviene un confronto "real time" che risulta anche in quest messaggio:
![quantita massima2](https://cloud.githubusercontent.com/assets/13355694/9991304/389ffe96-6069-11e5-87cd-850fc4415b4f.png)

**Comment by coder-molok** [comment]
Credo che l'errore si riferisca al fatto che la q. massima è obbligatoria.
Il "prima" è riferito a "prima di salvare", no?

in questo caso il messaggio corretto sarebbe semplicemente "Devi inserire
la quantità massima"

2015-09-18 15:25 GMT+02:00 DDDamage <notifications@github.com>:

**Comment by DDDamage** [comment]
Il messaggio di errore me lo dà se non inserisco la quantità minima.

**Comment by coder-molok** [comment]
Allora è sbagliato anche il campo che viene evidenziato, non solo il
messaggio.

2015-09-19 13:59 GMT+02:00 DDDamage <notifications@github.com>:

**Comment by DDDamage** [comment]
Se la segnalazione non è chiara la scrivo meglio ma non facciamo confusione.. o almeno prova a riprodurre il bug perchè non mi rifersico a quello che dici.

Modifico la descrizione sopra.

**Comment by coder-molok** [comment]
Per riprodurlo avrei bisogno di conoscere i passaggi che hai fatto.
Mi sono limitato ad analizzare i dati forniti (immagine).

Se aggiungi una breve descrizione del giro che hai fatto provo a riprodurlo.

Marco

Il giorno 21 settembre 2015 13:54, DDDamage <notifications@github.com> ha
scritto:

**Comment by DDDamage** [comment]
Devi provare a scrivere nel campo "quantità massima" con il campo "quantità minima" vuoto

**Comment by SimoSca** [comment]
Il messaggio "inserire quantità massima" era sbagliato perchè doveva essere "quantità minima".
Al momento la quantità obbligatoria da inserire è quella minima, in quanto è in base a quella che in teoria verrebbe raggiunto il numero di preferenze per aprire l'ordine di spedizione.
La massima in linea di principio dovrebbe riferirsi alla massima che il venditore vorrebbe vendere in totale (le scorte di magazzino in pratica).

Se volete cambiare queste condizioni (ad esempio non avere obbligatoria la quantità minima) basta dirmelo e provvedo.

Anche i messaggi d'errore e le eventuali scritte ditemi come le volete e sarà mio piacere dare soddisfazione alle vostre richieste.

**Comment by SimoSca** [comment]
Vorrei risolvere questa issue, pertanto vi chiedo di dare risposta al mio ultimo messaggio, grazie.

**Comment by DDDamage** [comment]
Secondo me correggendo il messaggio di errore risolvi ;)

**Comment by SimoSca** [comment]
Il messaggio avevo gia' provveduto a correggerlo, ero in particolare interessato al punto

>I controlli sono realtime per mio gusto, ma se preferite posso impostare tutti i singoli controlli al semplice submit del form.

In generale ho sempre trovato gradevoli i form che svolgono controllo realtime.

**Comment by coder-molok** [comment]
Vanno benissimo i controlli realtime,
però un errore dei controlli realtime non deve permettere l'inserimento di
dati erronei, quindi occorre fare anche una verifica di coerenza lato
server
(non so se c'è già, lo dico per completezza)

Il giorno 1 novembre 2015 14:03, Simone S. <notifications@github.com> ha
scritto:

**Comment by SimoSca** [comment]
Col javascript svolgo i controlli in modo da fare un check prima di inviare il forma alla rispettiva elgg action. Una volta validato via javascript e inviato, anche nella action svolgo dei controlli sui dati: gli stessi dello javascript (pertanto il controllo risulta essere solo di sicurezza).

**Comment by coder-molok** [comment]
Ok, a posto, chiudi pure.
Il 03/nov/2015 10:07, "Simone S." <notifications@github.com> ha scritto:
