### ISSUE TITLE
Recupero password - redirect su wall non necessario

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#132]
Nella procedura di recupero password, sia il successo che il fallimento dell'invio porta al wall senza alcun messaggio di conferma. Il messaggio è visualizzato solo se si torna nella pagina di login.

In sequenza:
![recupero mail1](https://cloud.githubusercontent.com/assets/13355694/9960925/dde483ac-5e1d-11e5-99d4-5a06cc699b1d.png)
![recupero mail2](https://cloud.githubusercontent.com/assets/13355694/9960926/ddeb491c-5e1d-11e5-8c9d-b38edf6d0e4a.png)
![recupero mail3](https://cloud.githubusercontent.com/assets/13355694/9960969/3616b7b6-5e1e-11e5-8c35-b1bb35b3b0ee.png)

**Comment by SimoSca** [comment]
Ora reindirizza al wall, ma visualizzando il messaggio di successo o insuccesso.
