### ISSUE TITLE
Inserimento offerte - errore descrizione mancante

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#133]
L'errore segnalato è generico, ci ho messo un po' a capire che era la descrizione a mancare, perchè avevo provato a mettere un spazio come testo.
![mancata descrizione](https://cloud.githubusercontent.com/assets/13355694/9961062/c2a06934-5e1e-11e5-8bcb-4526c45aba12.png)

**Comment by SimoSca** [comment]
risolta
