### ISSUE TITLE
Ipotesi descrizione/categorie/tag

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#135]
Parlando con Alessandro (UX francese) abbiamo ragionato sull'utilità delle descrizioni dei prodotti in particolare in relazione alla posizione attuale (sotto l'offerta nel wall)

Una nuova ipotesi è:
- la descrizione compare solo nel dettaglio prodotto (ingredienti, metodo di lavorazione, storia, ecc..)
- sotto l'offerta nel wall compaiono solo i tag
- i tag sono scelti da un elenco da spuntare nell'iserimento/modifica offerta
- alcuni tag sono generici (es: BIO, DOC, DOP, Di Montagna, Senza Glutine, Vegano, ecc..)
- ogni offerta appartiene ad una macro-categoria (formaggi, salumi, conserve)
- alcuni tag sono subordinati all'appartenenza ad una determinata categoria (formaggi: stagionato, semistagionato, fresco, stravecchio, di latte ovino, di latte vaccino
- possibilità da parte del produttore di suggerire nuovi tag

**Comment by DDDamage** [comment]
I tag devono sostituire il testo
![descrizione tag](https://cloud.githubusercontent.com/assets/13355694/12381312/be0f66cc-bd87-11e5-8ff4-ee99e091d3d6.png)

**Comment by DDDamage** [comment]
Aggiornamento, questa issue si riassume in:
- tag nel wall al posto della descrizione
- (possibilità di suggerire i tag)

**Comment by SimoSca** [comment]
Meglio avere dei chiarimenti:

* la sostituzione dei tags alla descrizione non e' un problema,  ma sarebbe meglio avere un suggerimento grafico su come visualizzarli: ad esempio un semplice elenco separato da trattini, oppure un insieme di caselle affiancate orizzontalmente, ed i relativi stili/colori.

* La possibilita' di suggerire i tag invece richiede maggiori specifiche:
 
    - chi puo' suggerire?
    - dove dovrebbe richiamare questa skill?
    - gli amministratori devono ricevere una mail per esserne informati?
    - bisognerebbe creare un'opzione nel pannello degli amministratori, ad esempio "tags suggeriti" e di conseguenza una pagina in cui approvarli/disapprovarli?
    - all'approvazione/disapprovazione vogliamo mandare una mail a chi li aveva proposti per fargli sapere cosa e' stato scelto?

**Comment by DDDamage** [comment]
Per quanto riguarda i tag:
akkurat regular 16pt, visualizzati uno in coda all'altro tipo: formaggio_stagionato_sottovuoto

Per quanto riguarda il suggerimento:
- slot "altro" in fondo agli altri tag
- aggiunge campo di inserimento
- l'offerta può essere inserita (il tag suggerito non compare)
- viene mandata mail solo agli amministratori contenente: offerta e tag suggeriti

l'amministratore aggiunge i tag dal pannello amministrazione e modifica manualmente l'offerta aggiungendo il tag inserito. L'offererente sarà avvisato tramite le mail già predisposte per la modifica offerta

**Comment by DDDamage** [comment]
Quindi il singolo tag compare così:

_tag

**Comment by SimoSca** [comment]
Svolta la prima parte.

**Comment by SimoSca** [comment]
Tre punti:

* quanti tag possono essere proposti?

* visto che i tag li scriviamo noi e quindi abbiamo pieno controllo, ho pensato all'opportunita' di inserire anche piu parole. L'utente potra' inserire parole separate da spazi, ma noi che salviamo lato amministratore a questo punto potremmo sostituire gli spazi con underscore, oppure trattini, oppure stile CamelCase, ovvero "verduzzo dorato dop" diventerebbe:

    - verduzzo_dorato_dop
    - verduzzo-dorato-dop
    - VerduzzoDoratoDop

    dimmi quale caso preferisci.

* Quando l'utente propone un nuovo tag, gli manderei una mail di ringraziamento, della serie:

    "gentire utente, ti ringraziamo per i tags suggeriti: -elenco dei tags-. Se verranno approvati saranno automaticamente aggiunti alla tua offerta".

    In questo modo oltre a esprimere cordialita' lo assicuriamo del fatto che ne abbiamo preso coscienza, evitanto che provi continuamente a reinserirli in nuovi post.

**Comment by DDDamage** [comment]
Ribadiamo che i tag vengono inseriti a mano da noi (me), quindi valuterò caso per caso.

1) possono essere proposti quanti tag si vuole: poi sta a noi distinguere quelli che sono tag da quelli che sono il nome stesso del prodotto. Per intenderci approverò soltanto i tag che possono essere usati anche per altri prodotti

2) sì si possono inserire più parole. Poi diventeranno tag separati (a seconda dei casi) o tag unici. Es: Val brembana -> _valbrembana; vino speziato -> _vino e _speziato

3) Vedi 2. Nel caso di tag formati da più parole vengono visualizzati senza spazi (vedi quelli che ci sono già es. mercatoequoesolidale)

4) Ok per la mail. sotituirei la seconda parte con: "Saranno aggiunti alla tua offerta una volta approvati"

**Comment by DDDamage** [comment]
Un appunto sulla ricerca dei tag: il completamento automatico dovrebbe avvenire all'interno di tutta la parola non in ordine di composizione

ES: se cerco solidale mi deve trovare _equosolidale
