### ISSUE TITLE
Registrazione - Lingua - manca traduzione errore username

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#136]
Non ho capito perché mi esca un errore, ma in ogni caso manca la descrizione dello stesso
![errore-username](https://cloud.githubusercontent.com/assets/8371887/9978362/fc065092-5f29-11e5-84fd-f3922be6fa36.png)

**Comment by DDDamage** [comment]
Vedi issue #134.

Ci sono molte parti in inglese che devono essere in italiano. Saranno tradotte in inglese in un secondo momento.

**Comment by coder-molok** [comment]
Non ne dubito, ma in questo caso non è sbagliata la scritta, manca proprio nel catalogo delle frasi.
Quel "foowd:user:username:error" è una chiave generata automaticamente che dovrebbe corrispondere ad una frase in un file di localizzazione.

Non ho tempo di cercare il file, ma se Davide o Simone mi danno il path potrei inserire la frase rapidamente (ammesso di capire qual'è l'errore... campo obbligatorio immagino)

**Comment by SimoSca** [comment]
Risolto.
Quando vi e' una scritta di quel formato, oppure nel caso in cui vediate scritte in inglese nella parte interessata da elgg, e' possibile svolgere la traduzione modificando il file [it.php](https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_utility/languages/it.php).

In ogni caso se si vogliono apportare delle modifiche faccio presente che allo stato attuale il lavoro (e pertanto i miei commit) vengono effettuati sulla branche "dev".

Se eseguite dei commit aggiornatemi che tiro giu i cambiamenti, thanks.
