### ISSUE TITLE
Nuovo utente - preferenze già espresse

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#137]
Mi sono registrato con un nuovo utente (regolare - non venditore), e nel wall trovo delle preferenze già espresse, mentre dovrebbero essere tutte a 0

Nome utente: tommy_user
Pass: dangerous

![preferenze - nuovo utente](https://cloud.githubusercontent.com/assets/13355694/9992115/085333b4-6070-11e5-87be-a587dc7149f8.png)

**Comment by coder-molok** [comment]
Stessa cosa capitata a me sabato... utente molok
Non pensavo fosse un bug... :-s

M

2015-09-21 14:50 GMT+02:00 DDDamage <notifications@github.com>:

**Comment by Panciz** [comment]
il valore visualizzato era quello del totale preferenze espresse da tutti per prezzo

ho modificato l'API perche' ritorni totale preferenze dall'utente, di conseguenza valore visualizzato e' il totale utente per prezzo
