### ISSUE TITLE
Nuovo utente - board vuoto

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#138]
Da utente appena generato, non mi compare nulla nel board tranne che la barra di navigazione

Dovrebbero comparire nome utente e avatar e la scritta "0 prodotti"
![board - nuovo utente](https://cloud.githubusercontent.com/assets/13355694/9992183/84c53168-6070-11e5-99e9-9bcd64fa20ea.png)

**Comment by SimoSca** [comment]
Risolta.

Gli utenti che non hanno ancora inserito l'avatar ora hanno una classica immagine di default, e nel caso non vi siano prodotti viene segnalato "0 products".
