### ISSUE TITLE
Dettaglio prodotti - non carica i contenuti

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#139]
Provando a vedere il dettaglio delle nuove inserzioni, non si vedono i dati inseriti in fase di creazione dell'offerta.
Ordine minimo, nome, descrizione, foto

Inoltre non visualizza neanche i tasti per esprimere le preferenze
![dettaglio](https://cloud.githubusercontent.com/assets/13355694/10124116/25e61734-654d-11e5-9cc5-7c8a10987dc5.png)

**Comment by SimoSca** [comment]
Appena Risolto.
