### ISSUE TITLE
Dettaglio prodotto - pulsanti inattivi

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#140]
Nella pagina dettaglio prodotti i pulsanti per modificare le quantità non sono interattivi

![dettaglio - pulsanti non interattivi](https://cloud.githubusercontent.com/assets/13355694/10262583/8cac695c-69ce-11e5-9414-a930792560e3.png)

**Comment by DDDamage** [comment]
I tasti adesso funzionano ma la barra di avanzamento nel dettaglio non mostra la preferenza espressa

**Comment by coder-molok** [comment]
Ho notato che barra e totale preferenze funzionano con un ritardo molto alto.

**Comment by Panciz** [comment]
non e' prorpio immediata ma non direi che si puo definire molto alto il ritardo.
