### ISSUE TITLE
Board - pulsanti non interattivi

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#141]
I pulsanti di aggiunta/sottrazione della preferenza non sono attivi e clicabili
![board - pulsanti non interattivi](https://cloud.githubusercontent.com/assets/13355694/10392554/553d3ac8-6e88-11e5-9727-00677ba1f975.png)

**Comment by SimoSca** [comment]
Risolta :)

**Comment by DDDamage** [comment]
Riapro perchè si è ripresentata
