### ISSUE TITLE
Pagina preferenze visuallizzazione strana

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#142]
La pagina preferenze entrando con il mio utente

panci
ciboBUONO99

visualizzza una strana schermata , vedi allegato.

P.S. l'immagine e' larga 

![screenshot from 2015-10-17 13-54-08](https://cloud.githubusercontent.com/assets/2254988/10558607/93277d72-74d6-11e5-8151-4c4dab73cc21.png)

**Comment by SimoSca** [comment]
Come avevo scritto nella chat è così perché la sto sviluppando adesso.
Rimuovo la issue per completezza.
