### ISSUE TITLE
Disabilitazione pulsanti se board amici

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#145]
Al momento e' possibile inserire preferenze per conto di altri aprendo una board di un altro utente amico o non.

**Comment by DDDamage** [comment]
Esatto.

Il Board degli amici dovrebbe essere visibile solo in modalità "gruppo", quindi ogni modifica di preferenze influenza la propria e non quella dell'amico in questione

**Comment by coder-molok** [comment]
Tommy, non mi torna.

Se io ti aggiungo come amico, cliccando sul tuo utente posso vedere le tue
preferenze, anche se sono in modalità utente singolo.

M
Il 24/ott/2015 02:18, "DDDamage" <notifications@github.com> ha scritto:

**Comment by DDDamage** [comment]
Partiamo dal presupposto che questo bug deve essere risolto nel senso che non è possibile modificare le preferenze di altri.

Se si eliminano i tasti, diventa inutile guardare il board di un amico
Si può fare che cliccando si aggiungono preferenze proprie (senza visualizzare la propria barra se in utente singolo), ma senza avere sott'occhio l'opzione "di gruppo" è difficile valutare l'esperienza di visualizzazione delle preferenze altrui.

Quindi si potrebbe direttamente eliminare (per ora) la possibilità di visualizzare il board altrui

**Comment by DDDamage** [comment]
Davide? Che ne pensi?

**Comment by coder-molok** [comment]
@DDDamage non capisco il fondamento di questo: "Se si eliminano i tasti, diventa inutile guardare il board di un amico".
Si guarda una board per conoscere i gusti degli altri, farsi invogliare da chi ha la nostra fiducia, dare precedenza a prodotti "vicino al completamento dell'ordine" (per questo si usa anche il wall di gruppo)

**Comment by SimoSca** [comment]
Mi intrometto dando ragione a @coder-molok : 
prima un utente poteva solamente visualizzare la sua board (questo era un lavoro di frontEnd fatto da marco p.), e mentre stavo risistemando alcune parti per aumentare la compatibilita' tra frontend e elgg ho pensato di rendere possibile la visualizzazione della board degli amici proprio per il motivo esposto da molok.
L'unica cosa che avevo tralasciato era la disattivazione dei pulsanti perche' vi sono varie opzioni, ma la piu' semplice e meno equivoca e' disattivare i pulsanti sulla board degli amici.

**Comment by DDDamage** [comment]
Ok.
Il board degli amici si può vedere, con i pulsanti disattivati.
Da quello è possibile raggiungere il dettaglio prodotto e aggiungere preferenze da lì.
Ma rimane aperta la questione di come viene visualizzata la pagina in "modalità di gruppo".

Dovremmo determinare soluzioni ad hoc, per le quali devono essere stabili tutti gli altri elementi (es. filtri nel board). La user experience non va complicata ulteriormente e questa funzionalità non è per ora fondamentale.

Quindi lasciate stare questa sottigliezza e dedicatevi a cosa più importanti.

**Comment by DDDamage** [comment]
@SimoSca togli la possibilità di vedere il board altrui per adesso, poi pensiamo a come introdurlo.

**Comment by SimoSca** [comment]
Appena tolta.
