### ISSUE TITLE
Chiusura offerta

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#147]
Per ora la chiusura dell'offerta da parte dio un utente verra implementata come segue.

Data un utente che per un offerta raggiunge, insieme alle preferenze degli amici,  la quota  minima puo inviare la chiusura offerta. Che comporta quanto segue:

Invio a tutti gli amici coinvolti un messaggio in cui si notifica la chiusura dell'offerta

Invio di un messaggio di spedizione al produttore che ha pubblicato l'offerta

Decurtazione della quota raggiunta insieme agli amici dal disponibile dell'offerta (diminuzione qtMax).

I

**Comment by DDDamage** [comment]
Giro completo nella #156
