### ISSUE TITLE
Quantità Minima e massima offerta multipli della quota.

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#148]
Inserire il controllo in fase registrazione offerta che la quantità minima e massima inseriti siano multipli della quota.

Questo per evitare inultili complicazioni in fase di suddivisione dell'ordine.

**Comment by SimoSca** [comment]
In realta' di recente ho cambiato le etichette nei forms, ad esempio la `quantita' minima` e' diventata `Numero minimo di Quote ` perche' per il momento tutti i calcoli si basano appunto sull'utilizzo di `minqt`, e `qt` , dove il **qt** sta per `quota` e non `quantita`.
