### ISSUE TITLE
Ricerca amicizie con indirizzo email

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#149]
Inserendo nel campo di ricerca un indirizzo email completo, dovrebbe essere visualizzato l'utente se esiste una corrispondenza esatta.

STEP 2
In caso contrario dovrebbe uscire un suggerimento di "invito" dell'amico non ancora registrato sulla piattaforma.

**Comment by SimoSca** [comment]
Appena risolta.
