### ISSUE TITLE
click su cuore-preferenza non centrato su immagini piccole

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#150]
Viene spontaneo cliccare sul cuore che appare, ma sulle immagini piccole, quando appare il cuore il mouse è più in basso e, spostando il mouse verso il cuore, in altro, il cuore scompare e il click non va a buon fine.

Il mouse non si vede negli snapshot, ma fate conto che è sempre molto vicino alla linea tratteggiata inferiore.

![wall-bianco1](https://cloud.githubusercontent.com/assets/8371887/10649925/f60aa3f6-7846-11e5-9b95-74178323c47a.png)
![wall-bianco1](https://cloud.githubusercontent.com/assets/8371887/10649965/24121aea-7847-11e5-8aa1-c278fde738ed.png)

**Comment by SimoSca** [comment]
Ho chiuso la issue #121 perche' affronta il medesimo problema della presente.

**Comment by DDDamage** [comment]
Risolto da eliminazione cuore dall'offerta
