### ISSUE TITLE
Login - tasti social

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#151]
Sono presenti e cliccabili
![login social](https://cloud.githubusercontent.com/assets/13355694/10700073/a499e952-79bb-11e5-9ca7-1c3fa48c56f6.png)

Ma restituiscono errore 
![login social2](https://cloud.githubusercontent.com/assets/13355694/10700084/b09de7b2-79bb-11e5-9b2f-44dfa20f17fc.png)

Quindi le opzioni sono farli sparire o (meglio) restituire messaggio "Questa funzione sarà attivata a breve"

**Comment by coder-molok** [comment]
Cos'è quel dominio che si vede in immagine: http-foowd.ddns.net ?

L'errore del browser è su questo...
Il 23/ott/2015 19:25, "DDDamage" <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
E' un host temporaneo che utilizzo in congiunta a ddns.net per svolgere test sulle social app: 
devo usare questa forzatura per alcuni parametri vincolanti di facebook e google+, ma attualmente questo risulta una delle ultime priorità, me lo confermi?

**Comment by coder-molok** [comment]
Non ti avevo più risposto, comunque si, confermo...

Il giorno 24 ottobre 2015 00:36, Simone S. <notifications@github.com> ha
scritto:

**Comment by DDDamage** [comment]
Trascurabile per ora

**Comment by DDDamage** [comment]
Da inserire assieme ad una maggiore integrazione con i social
