### ISSUE TITLE
Barra navigazione - menù tendina non cliccabile lato elgg

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#154]
Il menù non è cliccabile dalle pagine lato elgg
![menu](https://cloud.githubusercontent.com/assets/13355694/10700474/33e9a73a-79be-11e5-983c-0302fb85a721.png)

**Comment by SimoSca** [comment]
Non sviluppata in quanto attualmente quel tasto è fittizio.
La tengo come promemoria.

**Comment by DDDamage** [comment]
Immagino vada unita in qualche modo all'equivalente elgg in alto a sinistra

**Comment by SimoSca** [comment]
Ora assume lo stesso comportamento del wall.
