### ISSUE TITLE
Barra navigazione - menù tendina contenuti

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#155]
Vi serve il materiale da metterci dentro? Testo piano o vi serve sapere come fare le pagine?
Se dobbiamo chiarire i contenuti ci mettiamo al lavoro (io e Fede) prima che ci lavoriate.

Diteci cosa vi serve.

**Comment by SimoSca** [comment]
La assegno a @Panciz perché in teoria è un lavoro frontEnd, e personalmente non so cosa vada inserito.

**Comment by Panciz** [comment]
Direi che  mi serve sapere cosa metterci dentro.

1) le voci le teniamo tutte (HOME,work,contatct ,clients, about?) 

2) in ogni caso direi che i link porteranno a pagine fisse.

**Comment by coder-molok** [comment]
( testo attuale,	testo nuovo,	URL da linkare )
Home,	Sito web,	http://www.foowd.it/
About,	Su di noi,	http://www.foowd.it/about.html
Work,	Investitori,	http://www.foowd.it/investors.html
Client,	Produttori,	https://www.smore.com/pcm5x
Contact,	Contatti,	http://www.foowd.it/index.html#contatti

**Comment by coder-molok** [comment]
Cambiati i testi e i link
