### ISSUE TITLE
Chiusura ordine - giro di mail

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#156]
1) mail al capogruppo:
"Gentile Utente, grazie della disponibilità a ricevere. Gli altri membri del gruppo stanno confermando i propri acquisti: entro 24 ore riceverai copia dell'ordine inviato al produttore"
2) mail ad altri membri del gruppo
"Gentile utente, sei parte di un gruppo con invio merce a breve! Stai ordinando: [elenco prodotti e quantità]. Collegati se intendi modificare le quantità in ordine.
3) Dopo 24 ore, parte una mail a TUTTI (ogni membro del gruppo e il produttore) con oggetto "Riepilogo Ordine" e l'elenco di tutti i prodotti, di chi li ha ordinati, dei parziali di spesa, dei totali, e coi riferimenti del fornitore per il pagamento.
4) rimozione preferenze

Le ulteriori mail di conferma pagamento e scelta data e ricezione sono gestite personalmente dal capogruppo, dal produttore e dagli utenti.

**Comment by SimoSca** [comment]
1) Gli scrivo solo quelle due righe o inserisco anche una tabella riepilogativa?
2) Vuoi dire che un utente in teoria può modificare l'ordine anche dopo che il "manager" si è preso carico dell'ordine?  se è così devo modificare l'attuale procedura, che provvede subito ad azzerare le preferenze... partivo dal presupposto che una volta premuto il tasto fosse ormai tutto vincolato...
3) questa mail che parte dopo 24 ore DEVE partire dopo 24 ore, oppure può essere tutto ritrattato per decisione di singolo utente/capogruppo/produttore?

inoltre vedo che non viene spedita alcuna mail al produttore... 

Per favore, mandatemi uno schema dettagliato opzioni incluse.

PS:
attualmente le mail giungono a utenti, capogruppo e produttore, ciascuna con una tabella riepilogativa, e le preferenze vengono azzerate immediatamente (il punto 4 mi fa capire che non è così).

**Comment by DDDamage** [comment]
1)no, il riepilogo gli arriva dopo
2)Sì la modifica dell'ordine può avvenire fino a 24 ore dalla presa in carico
3)la mail parte senza altre possibilità, se nn si ha interagito l'ordine è identico al momento della presa in carico

**Comment by DDDamage** [comment]
Come hai notato, non abbiamo incluso la mail al produttore.

Per lo schema dettagliato fai riferimento a molok

**Comment by DDDamage** [comment]
Se hai bisogno di chiarimenti riguardo ai testi da inserire nelle mail, chiedi a fede nella chat foowd_ sviluppo

**Comment by SimoSca** [comment]
2 e 3 ) se pero' uno o piu' utenti decidono di diminuire le preferenze allora potremmo trovarci nella situazione in cui il totale delle quote sia minore del numero minimo di quote per la spedizione: in tal caso come volete che venga gestito?

**Comment by DDDamage** [comment]
Le fasi successive avvengono comunque.

In tal caso l'ordine si chiude con un quantitativo inferiore alla quantità minima. Poi verificheremo se veramente gli utenti riducono le quantità, di quanto, se diventa un problema per il produttore, ecc.. 

Meglio lasciare un'opzione aggiuntiva e piuttosto aggiustare il tiro successivamente (es. se quantità di chiusura < 60% dell'ordine minimo avviso a tutti e blocco ordine), piuttosto che non potersi rendere conto dei limiti per i consumatori.

Per ora facciamo il giro così, poi nei prossimi mesi di test vediamo.

**Comment by Panciz** [comment]
Per ora la soluzione trovata la seguente

Quando un utente raggiunge la quota minima insieme ai propri amici puo richiedere la spedizione e diventa capo gruppo. Vedi Amici

La creazione dell'ordine prevede le seguenti fasi e azioni:

Quando un utente preme la creazione dell'ordine e si prende carico della spedizione viene inviata un mail a tutti i gli utenti suoi amici che hanno data una preferenza per quel prodotto. le preferenze degli utenti coinvolti per quel prodotto passano in stato in invio


Dall'invio della mail c'è un periodo di (DA STABILIRE per ora 24 ore ) in cui viene permesso all'utente di modificare la preferenza espressa. Aumentandola e diminuendola

Allo scadere del periodo l'ordine viene confermato, vengono rimosse le preferenze inserite passano in stato inviate. Viene inviata una mail a tutti gli utenti che hanno ancora almeno una preferenza per quel prodotto, di conferma dell'onvio


Per ora:

ANCHE SE, A FRONTE DI RIMOZIONE PREFERENZE PRIMA DELLA SCADENZA, NON VIENE RAGGIUNTA LA QUOTA MINIMA, L'ORDINE PASSA SEMPRE IN FASE 3
