### ISSUE TITLE
link Gallery nel profilo degli utenti non-produttori

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#157]
Il link "Gallery" si vede ugualmente anche se sto usando un utente regolare,
selezionandolo esce un "Fatal Error" di php.
![wall-bianco1](https://cloud.githubusercontent.com/assets/8371887/10702013/2d6416b2-79c7-11e5-8697-0ffcd69b343a.png)

**Comment by SimoSca** [comment]
La gallery la teniamo a esclusiva opzione per i produttori?

**Comment by coder-molok** [comment]
Direi di sì, è la galleria delle offerte.
Tant'è vero che va in errore se ci entri con un utente normale.

M
Il 24/ott/2015 00:14, "Simone S." <notifications@github.com> ha scritto:
