### ISSUE TITLE
Descrizione prodotto wall inserita direttamente in DIV

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#158]
La Descrizione prodotto nel wall viene posizionata direttamente dentro il div.

Questo comporta tra gli altri che se si inserisce codice html nel testo si sballa la formattazione.

**Comment by coder-molok** [comment]
possiamo correggere in due modi: rimozione di qualunque tag (se non sbaglio php ha anche funzioni già pronte) o escaping dei caratteri che spaccano l'HTML (< > & " ' )

**Comment by SimoSca** [comment]
Questo puo' ricollegarsi alla issue #127 :
gli escaping o l'eliminazione di elementi html a quel punto sarebbe giusto svolgerla direttamente durante riempimento e salvataggio dei form di descrizione.

Credo appunto che sia giusto attuare una scelta PRIMA che i dati vengano salvati nel DB, in modo che successive chiamate API utilizzino solo il formato prestabilito.

**Comment by DDDamage** [comment]
Risolto da modifiche a inserimento testo
