### ISSUE TITLE
Stato preferenza per creazione ordini 

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#159]
Aggiungere una collonna stato alla tabella preferenze per gestire stati 

`inserita`
`in invio`
`inviata`

vedi https://github.com/coder-molok/foowd_alpha2/wiki#creazione-ordini

**Comment by SimoSca** [comment]
Aggiungo secondo quanto segue:

nome colonna: `state`
opzioni: `inserted`, `pending`, `sended`

Implemento il giro di email seguendo esattamente il link inserito?
