### ISSUE TITLE
Aggiungere parametro Stock alle offerte ?

### ISSUE THREAD

**Issue by SimoSca** [coder-molok/foowd_alpha2#161]
Ciao a tutti,

sicuramente non e' una priorita', ma visto che sto' implementando il giro di chiusura completa con tanto di API sul DB esterno, vorrei cercare di sistemare tutto in blocco in modo da predisporre il corretto giro.

Fatta questa premessa passo al punto vero e proprio:

escludendo i parametri base, un' **offerta** attualmente consta dei parametri

- `minqt` , ovvero il numero minimo di quote
- `maxqt`, il numero massimo di quote 

ma detto in questo modo risulta piuttosto vago, pertanto chiedo se l'interpretazione corretta sia

- `minqt` , ovvero il numero minimo di quote PER FAR PARTIRE UNA SPEDIZIONE
- `maxqt`, il numero massimo di quote PER SVOLGERE UNA SPEDIZIONE

in modo che in sostanza si spedisca quando le quote sono tra `minqt` e `maxqt` (in linea di principio).

Se questa mia interpretazione e' corretta, allora credo che un produttore possa essere interessato a fissare un vincolo `stock`, inteso come scorte di magazzino e che rappresenta il tetto massimo di quote che puo' vendere in totale, tra tutte le spedizioni.

Mi spiego meglio con un sempio: 

- stock 1000

se sono gia' state realizzate es 850 quote, allora se ne possono ancora vendere 1000-850 = 150.

Che ne pensate?

**Comment by coder-molok** [comment]
Maxqt è il tuo stock.

In altre parole, un gruppo potrebbe dare fondo ad una offerta.

La spedizione in se non èun problema, se non basta un pallet il produttore
ne prepara due...


M
Il 26/ott/2015 21:42, "Simone S." <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
Ok, pero' se un pallet e' da 100 e se ne ordinano 101 non penso sia certo che il produttore voglia spedire due pallet (magari suddividendoli in uno da 50 e uno da 51).

**Comment by coder-molok** [comment]
Vero, ma per ora non ce ne occupiamo.
(considera che se sono bottiglie o vasetti è un conto, ma se sono quarti di
formaggio il 101-esimo ci sta uguale)

M

Il giorno 26 ottobre 2015 22:08, Simone S. <notifications@github.com> ha
scritto:

**Comment by SimoSca** [comment]
Ok, perfect!

Thanks
