### ISSUE TITLE
Formato Email

### ISSUE THREAD

**Issue by SimoSca** [coder-molok/foowd_alpha2#162]
@coder-molok :

nella sezione relativa alle [email dell'ordine](https://github.com/coder-molok/foowd_alpha2/wiki#creazione-ordini) ho visto il testo delle email. 

Con `php mailer` e' possibile mandare le email in duplice formato: testo piano e testo HTML.
Ho gia' implementato un'interfaccia per poter svolgere l'invio con entrambe le funzioni, pertanto se possibile ti chiederei di fornirmi i testi in entrambe le modalita'. Sembra una sciocchezza, ma a mio avviso il formato delle mail e' un grande indice di qualita' ed accuratezza (per esempio inserendo una tabella riepilogativa ben formattata). Esempi di testi formattati li avevo gia' preparati alla pagina:

[https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_utility/classes/Uoowd/MessageEmail.php](https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_utility/classes/Uoowd/MessageEmail.php)

Sarebbe inoltre comodissimo utilizzare il formato per la funzione [vprintf di php](http://php.net/manual/en/function.vprintf.php).

Questa funzione viene anche utilizzata nei file delle traduzioni (vedi la nostra in [italiano](https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_utility/languages/it.php)), pertanto qualora qualcuno decida di cambiare dei testi, sarebbe assai gradito questo formato.

Eventualmente va bene anche editare a parte i files originali e mandarmene una copia, ma sconsiglio di pubblicare direttamente i cambiamenti nel repo: se uno dei file di traduzione ha un errore (mancanza di una banale virgola, per dire) allora il sito si blocca!

Grazie mille per l'attenzione

**Comment by coder-molok** [comment]
ottimo, appena ricavo 10' converto i testi in piacevole html e ti mando il
codice.

Se mi mandi la lista di parametri che hai usato metto i tag corretti.

M

2015-10-26 22:02 GMT+01:00 Simone S. <notifications@github.com>:

**Comment by SimoSca** [comment]
In

[https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_utility/classes/Uoowd/MessageEmail.php](https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_utility/classes/Uoowd/MessageEmail.php)

ogni funzione e' accompagnata da una lista dei parametri. 

In ogni caso per i parametri non ci sono problemi: l'importante e' il testo formattato coi "%s" e "%d" e loro opzioni (ad esempio "%13s" per fissare le lunghezze).

Grazie,
Simone

**Comment by coder-molok** [comment]
@SimoSca facendo le prove ho visto che al "leader" non viene mandato il dettaglio dell'ordine, ma i dati sono disponibili come per le altre mail destinate ai partecipanti?

(guarderei nel codice, ma al momento sono impossibilitiato)

**Comment by SimoSca** [comment]
@coder-molok 
Dal quarto post in [https://github.com/coder-molok/foowd_alpha2/issues/156](https://github.com/coder-molok/foowd_alpha2/issues/156) si evince che la mail associata all'apertura dell'ordine non viene mandata al produttore. Ad esso, e a chiunque interessato a quell'ordine, giunge una mail definitiva dopo le 24 ore.
I dati sono reperibili mediante API, ma allo stato attuale quelle relative all'ordine riguardano solamente il giro di apertura dell'ordine e di chiusura dopo le 24h.

Il testo e' ancora grezzo perche' preferisco lasciare a voi la decisione su cosa scrivere e come presentarlo (distinzione tra mail HTML e TEXT).

Se non sono stato chiaro, chiedi pure.

**Comment by coder-molok** [comment]
Ciao Simone, ti ho scritto su telegram ma temo tu non sia collegato,
vado avanti qui...

stavo guardando per modificare il testo delle mail,
non mi trovavo con i sorgenti perché nelle mail di test generate il 24 /11
trovo all'inizio :
"(messaggio di test, non quello definitivo) "

nel codice del file MessageEmail.php i testi sono molto più evoluti,
(ho controllato anche su VPS)
approfondendo ho visto che quel testo "guida" si trova nella
*foowd-purchase-leader.php* dove istanzi la MessageEmail.php ma non la usi,
mi pare...

è tutto corretto?
non ti dispiace se ci metto mano per far girare i testi delle email
migliorati?


Fammi sapere
Marco

Il giorno 24 novembre 2015 15:22, Simone S. <notifications@github.com> ha
scritto:

**Comment by SimoSca** [comment]
E' che il sabato sera non guardo molto il cellulare, ma in generale whatsapp, telegram, hangouts e sms li uso equamente.

Ad ogni modo, su "foowd-purchase-leader.php" i testi dei messaggi sono appunto quelli provvisori: per tenere il codice più pulito sarebbe meglio inserire i testi corretti in "MessageEmail.php" e utilizzarli mediante l'istanza già chiamata (ma come giustamente detto, non utilizzata) in "foowd-purchase-leader.php".
Se vuoi puoi mandarmi i testi corretti in una mail, e penso io a inserirli nella classe e richiamarli correttamente nella action.

**Comment by coder-molok** [comment]
Ok, ora è chiaro.
Non ho ancora i testi (stavo preparandomi), quando sono pronti te li mando.
Poi al limite per piccole modifiche posso farle direttamente io in
MessageEmail.php

Dovrebbero essere pronte a breve (domani o lunedì), ti faccio sapere.

Marco

Il giorno 5 dicembre 2015 21:50, Simone S. <notifications@github.com> ha
scritto:
