### ISSUE TITLE
Pagina modifica dati profile errore

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#167]
La pagina modifica dati profile per utente normale rimane con solo il pulsante data.

All'inizio vengon ocaricate e forma che poi scompaioni

vedi allegato 
![screenshot from 2015-10-28 00-17-26](https://cloud.githubusercontent.com/assets/2254988/10775519/62dcc772-7d09-11e5-8dd7-950df76a565b.png)

**Comment by SimoSca** [comment]
Era un bug relativo al tipo di utente.

Ora risolto.
