### ISSUE TITLE
Visualizzazione Carrello e rimozione prodotto nel dettaglio

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#168]
C'e' da decidere come comportarsi nel dettaglio quando si e' in modalita' gruppo 

Posso aggiungere e togliere peferenze? Se arrivo a 0 delle preferenze mie cosa succede?

Io proporrei di togliere la possibilita' di aggiungere e togliere preferenze in modalita' gruppo almeno dalla pagina dettaglio.

**Comment by coder-molok** [comment]
Per il momento togliamo tutte le operazioni sulle preferenze dalla modalità gruppo.
