### ISSUE TITLE
Sostituire azioni che prevedono l'hover, per mobile

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#169]
Per il momento ho rilevato la cosa limitatamente al cuore di selezione dal wall, sui dispositivi mobili non appare se non si clicca e il funzionamento generale resta quindi un po' oscuro.

Andrebbe aggiunta una clausola css per i dispositivi touch che mostri , per esempio, un cuore in trasparenza sulle immagini.

Nel caso ci siano altre funzionalità che si avvalgono dell'hover occorre verificare che non ci siano perdite di UX e nel caso provvedere.

**Comment by DDDamage** [comment]
Da rivedere assieme a tutta la visualizzazione mobile
