### ISSUE TITLE
Prezzi

### ISSUE THREAD

**Issue by SimoSca** [coder-molok/foowd_alpha2#17]
@Panciz 

I prezzi li vanno esposti con la virgola o col punto, per quanto concerne la parte decimale?
Importante perché in mysql i numeri con la virgola in realtà vengono troncati, e devo assestare di conseguenza.

Ho modificato schema.xml per essere compatibile col formato dei numeri a due cifre decimali.

**Comment by Panciz** [comment]
Corretto per memorizzare i prezzi in MySql deve essere usato il tipo NUMERIC o DECIMAL per evitare approssimazioni.[vedi](http://stackoverflow.com/questions/13030368/best-data-type-to-store-money-values-in-mysql). 

Nella documentazione avevo scritto correttamente probabilmente ero andato veloce nel fare lo schema comunque giusta correzione.
In realtà nella ho indicato il DECIMAL anche per la quantità probabilmente in quel caso la parte decimale dovrebbe essere di 3 cifre.

**Comment by SimoSca** [comment]
In realtà nell'ultima commit ho aggiunto delle opzioni relative quel parametro nello schema.xml : 
propel il DECIMAL lo considera automaticamente DECIMAL(10,0) , pertanto troncava i valori.

**Comment by SimoSca** [comment]
scusa, avevo letto di fretta:
per i prezzi ho impostato in modo da avere a disposizione 8 cifre per la parte intera e 2 per la decimale (DECIMAL(10,2)), per le quantità come vuoi che vada fatto?

**Comment by Panciz** [comment]
Direi un Decimal 8,3 proprio per essere precisi

**Comment by SimoSca** [comment]
Risolta nei giorni precedenti.
