### ISSUE TITLE
Ordine chiuso - azzeramento quantità imprevisto

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#172]
A ordine chiuso, provando a diminuire la quantità mi azzera le preferenze. Se poi le provo ad aumentare in un click me le riporta come prima.
Modificare le quote oltre la quantità iniziale, invece, sembra funzionare correttamente.

![modifica quantita](https://cloud.githubusercontent.com/assets/13355694/11614190/e2626830-9c3a-11e5-9e12-069216fa6a45.png)
![modifica quantita2](https://cloud.githubusercontent.com/assets/13355694/11614191/e2678a7c-9c3a-11e5-8e4c-5dc787c09393.png)
![modifica quantita3](https://cloud.githubusercontent.com/assets/13355694/11614200/19ae8efe-9c3b-11e5-9c74-b73177f1f3d4.png)

**Comment by SimoSca** [comment]
@DDDamage 
Per ordine chiuso intendi dopo che le 24h sono concluse e giunge il secondo giro di mail?

**Comment by DDDamage** [comment]
Credo di sì. Alla presa in carico questo problema non si verifica.
