### ISSUE TITLE
Aggiunta rimozione preferenze per prodotto io 19

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#173]
http://5.196.228.146/elgg-1.10.4/detail?productId=29

quando si cerca di aggiungere la prima bvolta mette 8 al posto di 1

lo stesso quando togli

**Comment by DDDamage** [comment]
Credo sia un problema che deriva dalla chiusura ordine. Vedi #172

**Comment by SimoSca** [comment]
@Panciz 

Credo che possa essere dovuto al parametro utilizzato:

dalla console ho controllato la risposta della chiamata

     http://5.196.228.146/api_foowd/public_html/api/offer?type=search&Id=29&ExternalId=54

e credo che nell'interfaccia venga usato il parametro **body.totalQt**, che si riferisce alle preferenze espresse tra tutti gli amici. Probabilmente usando **body.prefer.Qt** dovrebbe segnare le preferenze espresse dal singolo utente.

**Comment by Panciz** [comment]
ho analizato le chiamate che faccio e  mi sembra tutto OK sia in aggiunta che in rimozione chiamo sempre

http://5.196.228.146/api_foowd/public_html/api/prefer

con nel body

in caso di aggiunta

       {OfferId: 29, ExternalId: 79, type: "create", Qt: 1}

incaso rimozione

      {OfferId: 29, ExternalId: 79, type: "create", Qt: -1}

 il problema sembra relativo alla prima preferenza aggiunta da all'ultima olta non viene aggiunta e rimossa una quota ma 8.

Non capita su tutti i prodotti ma su alcuni.

su http://5.196.228.146/elgg-1.10.4/detail?productId=30

ne aggiunge toglie due.

**Comment by SimoSca** [comment]
Quella mi sembra vada bene: probabilmente su DB avviene tutto correttamente.
Penso che l'inghippo stia nella parte dell'aggiornamento: in tale fase viene fatta la richiesta

    http://5.196.228.146/api_foowd/public_html/api/offer?type=search&Id=29&ExternalId=54

e nella riposta di questa chiamata è presente sia la quantità del singolo utente, che la quantità totale: non ho controllato il codice di frontEnd, ma penso che il problema stia in quali parametri della risposta vengono utilizzati.
Se non torna ti chiedo di dirmelo, così controllo.
