### ISSUE TITLE
Form Offerta: info

### ISSUE THREAD

**Issue by SimoSca** [coder-molok/foowd_alpha2#178]
Relativamente al form di creazione/aggiornamento nuova offerta credo sia il caso di iniziare a pensare come dare delucidazioni in merito alle voci che appaiono.

Ad esempio **Quantità per Quota** : non essendo intuitivo il produttore che per la prima volta la incontra dovrebbe poter leggere la spiegazione su cosa sono le quote e dunque cosa rappresenta questo campo.
Accanto a ogni voce inserire una piccola icona (in genere "i") al cui click realizzare alcune tra le seguenti opzioni:

1. aprire un popup che spiega la singola voce
2. aprire una pagina lightbox che illustra tutto il form
3. aprire una nuova pagina che illustra tutto il form

da utente preferirei le opzioni 1 o 3.

**Comment by DDDamage** [comment]
Ma questa pagina rientra nella revisione ai testi che sta caricando @coder-molok ?

**Comment by coder-molok** [comment]
Non mi pare ci fossero segnalazioni sulla pagina del produttore.

Ma se hai rilevato inesattezze, segnalale!

M
Il 14/gen/2016 12:53, "DDDamage" <notifications@github.com> ha scritto:

**Comment by DDDamage** [comment]
Ah se fede non le ha segnalate vuol dire che le voci di per sè vanno bene.

Riguardo al tutorial, ci stiamo attrezzando. (magari facciamo un video demo utilizzando la piattaforma)

**Comment by DDDamage** [comment]
Dovrebbe essere risolto dalla guida all'uso
