### ISSUE TITLE
Menù link - area click per chiusura

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#179]
Il menù del sito (tre lineette in alto a dx) dovrebbe chiudersi cliccando ovunque meno che il testo.
Adesso non è chiaro come chiuderlo una volta aperto

![menu](https://cloud.githubusercontent.com/assets/13355694/12323738/3ae7a19a-babe-11e5-997a-25eb6bdbdc28.png)

**Comment by coder-molok** [comment]
Al prossimo aggiornamento dell'ambiente Sviluppo possiamo controllare se funziona a dovere.
Verifichiamo soprattutto i "side effects", come il click sul logo, sui link, sul bottone di apertura.

**Comment by coder-molok** [comment]
Provato e si chiude, anche cliccando su un link, apre il link in altra pagina e scompare il menu.
