### ISSUE TITLE
Tutorial - Wiki

### ISSUE THREAD

**Issue by SimoSca** [coder-molok/foowd_alpha2#180]
Riprendo velocemente l'idea della wiki suggerita da Fede, ivi rispondendogli:

Se sono semplici pagine e' abbastanza semplice. 
Creare una piccola wiki in se non e' difficile se si decide di inserire dei semplici testi. Inizia a divenire un lavoro piu' oneroso se la vuoi riempire di link. Sicuramente risulta impegnativo a livello di tempo per scrivere i testi.

Se la wiki risulta ben fatta, allora ad esempio si puo' aggiungere la sezione "Form Prodotto" in cui specificare i campi, e dallo stesso form potrei inserire dei link che puntano a sezioni specifiche della wiki. In questo modo si risolverebbe la parte relativa alla issue #178.

**Comment by coder-molok** [comment]
Non credo sia neppure necessario che sia un "wiki" (cioè aggiornabile dalla
pagina stessa).
Ma l'idea di rendere le pagine del tutorial automaticamente "linkabili" sui
campi del sito non è male... però non è urgente.

Per cominciare creiamo un ipertesto con un css molto pulito che permetta
all'utente di avere 2 cose:
al primo accesso una descrizione generale del sito e del suo funzionamento
in 3-6 pagine.
successivamente un riferimento rapido alle descrizioni delle varie sezioni
del sito, ognuna di 1-2 pagine.

M

Il giorno 15 gennaio 2016 12:33, Simone S. <notifications@github.com> ha
scritto:

**Comment by SimoSca** [comment]
La penso proprio come te. Inoltre renderla aggiornabile dalla pagina stessa risulta molto easy una volta scritte le pagine specifiche.
Questa parte puo' essere sviluppata in backend, pertanto vorrei solamente sapere chi pensa di prendersi la briga di scrivere le pagine in modo da sapere con chi interfacciarmi.

Thanks.

**Comment by DDDamage** [comment]
La guida all'uso di due pagine sarà probabilmente scaricabile in pdf. 
Appena terminiamo la revisione (con tanto di veste grafica) serve mettere sia una copia raggiungibile sul sito che la sua versione scaricabile. Probabilmente un link all'inizio della pagina con scritto "scarica in versione pdf"

**Comment by DDDamage** [comment]
Inserisci la guida raggiungibile al link:
[www.tiny.cc/guida_foowd_1](url)

Nel menù generico qui sotto, in prima posizione nell'elenco con la dicitura "guida all'uso"
![posizione](https://cloud.githubusercontent.com/assets/13355694/13536386/e0f81a94-e23f-11e5-90af-72b73956b5a7.png)

**Comment by SimoSca** [comment]
Fatto.

**Comment by DDDamage** [comment]
Ops mi sono spiegato male: in prima posizione intendevo in alto non in basso

**Comment by SimoSca** [comment]
Avevi scritto giusto, sono io che ricordavo male.
In ogni caso ora dovrebbe essere giusto.

**Comment by SimoSca** [comment]
Questa issue possiamo considerarla chiusa?

**Comment by coder-molok** [comment]
Direi di si.
