### ISSUE TITLE
Miglioramento UX

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#181]
Mantenendo l'impostazione corrente delle due modalità, ci sono dei miglioramenti a livello di elementi visualizzati che possono rendere più fluida la user experience. Sono i prossimi miglioramenti da fare, chiusa questa fase. Per quanto riguarda la barra composta di cui scrivo più avanti, ho trovato una variante al plugin utilizzato, dovrebbe essere facilmente implementabile:

https://github.com/j-ulrich/jquery-ui-multiprogressbar
qui una demo di come appare ( http://jsbin.com/tazacocefe/edit?html,css,js,output )

WALL:
- spostare barra di completamento sotto la foto,
- le quote (€) visualizzate sopra le offerte sono sempre quelle del consumatore singolo, anche in modalità gruppo
- le quote pari a zero non devono essere visualizzate
![miglioramenti wall](https://cloud.githubusercontent.com/assets/13355694/12371681/e08d1750-bc3b-11e5-8268-1eeb9f5201d8.png)

BOARD (gruppo) e DETTAGLIO (gruppo):
- barra composta da preferenze personali + quelle degli amici
- n. prodotti e totale sempre riferiti all'utente singolo
- pulsanti modifica quote sempre attivi (devono modificare le preferenze personali) 
- è possibile la chiusura dell'ordine come singolo o in gruppo, a seconda della modalità attivata, purchè in entrambi i casi si raggiunga la quantità minima
![miglioramenti dettaglio gruppo](https://cloud.githubusercontent.com/assets/13355694/12371687/22fbfa84-bc3c-11e5-84df-8c4dfda0acab.png)
![miglioramenti board gruppo](https://cloud.githubusercontent.com/assets/13355694/12371686/22fb3c8e-bc3c-11e5-8c20-05c51a56ba55.png)

**Comment by DDDamage** [comment]
Praticamente la modalità di gruppo diventa un toggle delle preferenze degli amici.

**Comment by DDDamage** [comment]
Ignorare questione barra, vedi  #194

**Comment by DDDamage** [comment]
@SimoSca

**Comment by SimoSca** [comment]
La chiudo perche' attualmente abbiamo sviluppato molte modifiche.
