### ISSUE TITLE
Colori elgg

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#182]
Ho messo questa pagina credo ci siano tutti colori da correggere
![colori elgg](https://cloud.githubusercontent.com/assets/13355694/12379073/069fa972-bd53-11e5-9ce1-a7579ad0a7d4.png)

**Comment by DDDamage** [comment]
Altra schermata (per il colore del testo segui lo schema della paletta):
![colori elgg2](https://cloud.githubusercontent.com/assets/13355694/12389700/acfbc03a-bdda-11e5-836b-fc6dc384e0ee.png)

**Comment by SimoSca** [comment]
Svolto. Il color sabbia della seconda immagine l'ho reso leggermente piu' scuro per renderlo maggiormente leggibile su sfondo bianco.
Sicuramente ora dovro' impiegare un po di tempo per rimpiazzare tutti gli stili, pertanto man mano che capita di visualizzare look che non piaciono, chiedo di segnalarmi quantomeno le pagine, thanks.
