### ISSUE TITLE
Board - Assenza contorno bianco pulsanti

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#183]
Così si confondono con lo sfondo.
![pulsanti board](https://cloud.githubusercontent.com/assets/13355694/12379157/5aa2de30-bd54-11e5-8ecf-d188251afdf2.png)

**Comment by DDDamage** [comment]
Lo stesso contorno che c'è ora per il + serve anche alle altre icone. 

![contorno board](https://cloud.githubusercontent.com/assets/13355694/12549507/03039452-c35e-11e5-9eba-ca3455a1e8e4.png)

**Comment by SimoSca** [comment]
@Panciz 

vedo che ora funziona, pertanto penso che l'abbia risolta te.
