### ISSUE TITLE
Privilegi admin ai produttori

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#186]
Sarebbe possibile aggiungere limitati permessi da amministratore ai venditori?
Limitatamente a questa schermata:
![amministrazione](https://cloud.githubusercontent.com/assets/13355694/12381219/00ca1ff4-bd86-11e5-8554-ee0e5b5e986e.png)

E quindi poter accedere a questa, ma soltanto relativa alle proprie prenotazioni.
![prenotazioni](https://cloud.githubusercontent.com/assets/13355694/12381275/c8318b18-bd86-11e5-99ba-2dff7bfb037b.png)

Sarebbe un modo semplice e indolore per permettere ai venditori di vedere se gli devono arrivare ordini, ed eventualmente contattare il leader (tramite elgg), per sapere se l'affare si fa o no.

**Comment by SimoSca** [comment]
Premessa:
i produttori hanno permessi di utente, e personalmente lato elgg eviterei di dare permessi d'amministrazione ai non amministratori.

Risposta:
sul database agli utenti associamo un "genre", attualmente "standard" o "offerente", pertanto posso implementare la tua richiesta. In tal caso però lascio sottinteso quanto segue: 

- se l'utente è un produttore, allora può visualizzare solo i suoi ordini ancora da chiudere
- se l'utente è un'amministratore, allora può visualizzare TUTTI gli ordini ancora da chiudere

Se vuoi posso aggiungere un pulsante "visualizza storico" che carica dinamicamente l'elenco di tutti gli ordini di competenza.

**Comment by DDDamage** [comment]
se l'utente è un produttore, allora può visualizzare solo i suoi ordini ancora da chiudere
    se l'utente è un'amministratore, allora può visualizzare TUTTI gli ordini ancora da chiudere

Esatto. La mia proposta era per mantenere esattamente la stessa impostazione grafica (con prenotazioni in alto in evidenza)
Lo storico non è necessario.

PS: Viceversa, potrebbe servirmi (da amministratore)  accedere a TUTTE le offerte e poterle modificare. Ad esempio per sistemare i tag quando vengono aggiornati

**Comment by SimoSca** [comment]
> Esatto. La mia proposta era per mantenere esattamente la stessa impostazione grafica (con prenotazioni in alto in evidenza)

cosa intendi con "prenotazioni" in alto in evidenza? intendi quella che c'e' gia' nella pagina `<sito elgg>/panel` ?


> PS: Viceversa, potrebbe servirmi (da amministratore) accedere a TUTTE le offerte e poterle modificare. Ad esempio per sistemare i tag quando vengono aggiornati

in un secondo tempo si puo' impostare, ma bisogna entrare nel dettaglio perche' per dei casi speciali probabilmente e' meglio se e' uno sviluppatore a svolgere i cambiamenti direttamente da mysql.

**Comment by DDDamage** [comment]
Intendo la parte prenotazioni che mi è comparsa con i privilegi da amministratore, quella in alto sopra la riga rosa (prima immagine in questa issue)

Ok per gli aggiornamenti offerte lato DB.

**Comment by SimoSca** [comment]
Appena terminata: 
puoi testare quelle pagine sia come utente normale, sia come produttore, che come amministratore.

Se il risultato ti garba, lascio a te il piacere di chiudere la issue.

**Comment by DDDamage** [comment]
Sì va bene per la funzionalità. Magari centrato sta meglio ma è un dettaglio

**Comment by SimoSca** [comment]
Io adesso l'ho spostato a sinistra per mio gusto, pertanto se mi dici come vuoi allinearli lo faccio subito.

**Comment by DDDamage** [comment]
Ah ok va bene.. chiudiamo qui, massimo vediamo in futuro in un ipotetico restyling
