### ISSUE TITLE
Board - conteggio prodotti

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#187]
Il conteggio dei prodotti mi appare uguale a zero.
Non sempre, ieri mi ricordo distintamente che appariva "11 products"
Quindi non riesco a riportare esattamente il procedimento per riprodurre il bug

![conteggio prodotti](https://cloud.githubusercontent.com/assets/13355694/12393154/2ff6e3f2-bdf4-11e5-8bec-93b33a607cd7.png)

**Comment by DDDamage** [comment]
Ho fatto diverse prove arrivando al board:
- dall'esterno del sito
- da altre pagine di foowd
- aggiornando la pagina (da browser o cliccando ripetutamente sull'icona board)

A volte visualizza "0 prodotti" a volte il conteggio corretto
![conteggio prodotti2](https://cloud.githubusercontent.com/assets/13355694/12466486/4f3370d6-bfd5-11e5-8572-9dcd0e8473b1.png)

**Comment by SimoSca** [comment]
Appena risolta:

in `UserBoardController.js` bisognava sostituire

    "likes" : $('.preference').length,

con 

    "likes" : $('.user-preference').length,
