### ISSUE TITLE
Visualizzazione Internet Explorer sballata

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#188]
Browser: Internet Explorer 9 - 64 bit edition
Versione 9.0.8112.16421
Versioni aggiornamento: 9.0.42
Livello di codifica: 256-bit

Non lo uso normalmente stavo facendo delle prove per visualizzare le icone. La pagina è tutta sballata:
- mancano gli elementi di navigazione in alto a dx
- la griglia è spostata a dx (stesso problema su mobile)
- il logo foowd_ non è posizionato sulla barra
- altri problemi sulle altre pagine (raggiungibili solo dalla barra indirizzi)

![explorer 1](https://cloud.githubusercontent.com/assets/13355694/12512004/d509705c-c115-11e5-9b1f-df76f579e440.png)
![explorer 2](https://cloud.githubusercontent.com/assets/13355694/12512022/f22565ec-c115-11e5-82ba-2d3cfea55d79.png)

**Comment by coder-molok** [comment]
Esattamente come fa a me su Midori. Che sia il web-kit?

Il giorno 22 gennaio 2016 14:39, DDDamage <notifications@github.com> ha
scritto:

**Comment by Panciz** [comment]
Potrebbero esserci alcune cose non funzionanti con IE9 non credo che web-kit centri in quanto non l ousa IE.

**Comment by DDDamage** [comment]
Quindi è un problema di compatibilità non risolvibile? ..credo che la maggiorparte degli utenti "illetterati" utilizzi IE :(

**Comment by coder-molok** [comment]
Purtroppo sì, ci lavoro su appena ho tempo


Il giorno 25 gennaio 2016 22:21, DDDamage <notifications@github.com> ha
scritto:

**Comment by SimoSca** [comment]
Per il momento per gli utenti con IExplorer 9 e precedenti si potrebbe inserire una piccola barra con un messaggio tipo: "questo sito non e' compatibile con la tua versione di IE. Per la corretta visualizzazione si suggerisce di passare a IE 10 o superiori oppure di utilizzare un altro browser".

Per il frontend IE e' il male!

**Comment by DDDamage** [comment]
Se è una semplice questione di versione non è così grave

**Comment by SimoSca** [comment]
Negli utlimi tempi sono stati fatti alcuni cambiamenti... visto che non ho IE 9 e lo strumento di compatibilita' della mia versione in realta' non produce errori, vi chiedo gentilmente di ripetermi gli errori attuali.

PS: probabilmente ho risolto il posizionamento orizzontale del wall, almeno per i tablet.

@DDDamage (x quando tornera') : 
per questi problemi di compatibilita' suggerisco di aggiungere il label "compatibilita" e di nominare le issue con semplicemente il nome del device.

**Comment by coder-molok** [comment]
Qui in ufficio ho Midori che dava lo stesso problema, appena ho un minuto
verifico.

Non ho IE9, provo a chiedere in giro...
Il 16/feb/2016 12:28, "Simone S." <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
Rivisto vari aspetti. Ora dovrebbe essere accettabile.
Inoltre ho anche risolto alcuni problemi di risposte javascript che sui brower microsoft tendono a non aggiornare i dati, come il clic dei pulsanti + o - .
