### ISSUE TITLE
icona lente per sito produttore

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#189]
Ho avuto parecchi problemi a caricare questa icona come ho fatto per le altre in svg 
usando il before del css cosi:

.foowd-icon-group:before {
 	  background-image: url('../../img/icone/gruppo.svg');
    background-size: 40px 40px;
    width: 40px; 
    height: 40px;
    content:"";
}

infatti solo in questo caso, non capisco perche' con content vuoto tutto lo span non viene visualizzato.
mettendo qualcosa in content funziona.
Non si puo metterci direttamente l'immagine altrimenti e' impossibile farci il resize.

Provero a mettere il link in un altro modo .

**Comment by SimoSca** [comment]
quel codice e' il css finale generato da stylus?
Probabilmente non centra, ma una volta con stylus mi era capitato un problema simile perche' dopo i due punti non avevo lasciato lo spazio, come vedo ora per la proprieta' "content".

**Comment by SimoSca** [comment]
Ho appena controllato: in realta' carica tutto bene.

La classe:pseudo .foowd-icon-group:before mi appare normalmente, mentre quando si passa alla modalita' gruppo .foowd-icon-group-white:before non si vede perche' nell'immagine originale (gruppo_white.svg) sia lo stroke che il fill sono white.

Non sapendo come dovrebbe essere il risultato finale magari sto dicendo una cosa ovvia, e nel caso scusa per il tempo che ti ho fatto perdere.

**Comment by SimoSca** [comment]
Se ho ben capito quello che non si visualizza e' la lente nel wall, che dovrebbe apparire in basso all'immagine, a sinistra.
Se e' cosi' su google chrome impostando alla classe .foowd-icon-len:before l'attributo

    display: block;

dovrebbe funzionare tutto normalmente.
