### ISSUE TITLE
Definizione Capo gruppo

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#19]
Definire i dettagli della funzionalita'

**Comment by DDDamage** [comment]
Il capogruppo è quello che sceglie per primo di fare un ordine sulla base delle preferenze sue e degli amici.

Quando si ha la possibilità di fare un ordine (perchè le quantità minime sono raggiunte), chi crea il gruppo accetta di essere il capogruppo e di ricevere la merce a casa sua.
