### ISSUE TITLE
Board - Icona gruppo attiva non visualizzata

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#190]
L'icona correttamente visualizzata nel wall:
![gruppo giusto](https://cloud.githubusercontent.com/assets/13355694/12549598/987e03e6-c35e-11e5-8936-644581553dc7.png)

L'icona mancante nel board
![gruppo board](https://cloud.githubusercontent.com/assets/13355694/12549602/a1a23bcc-c35e-11e5-9726-a7e6d20f8706.png)

**Comment by SimoSca** [comment]
ho inserito la risposta nella iss#189.

Di che colore deve essere quella attiva?

**Comment by SimoSca** [comment]
quando si switcha passando alla modalita' gruppo in

    id="groupBtn"

la classe `fw-menu-icon` non si aggiorna a `fw-menu-icon-group`

**Comment by SimoSca** [comment]
@Panciz :

ho visto che ora non lo fa piu... l'hai risolta te?
