### ISSUE TITLE
Registrazione - immagine obbligatoria produttore

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#191]
Togliere campo obbligtorio "carica immagine" (non essendoci più il carousel nn serve)

**Comment by coder-molok** [comment]
Facciamola mettere lo stesso, non c'è il carusel adesso, ma quando
metteremo qualcosa è bene avere subito almeno una immagine...
Il 26/gen/2016 20:29, "DDDamage" <notifications@github.com> ha scritto:

**Comment by DDDamage** [comment]
In quel caso la faremo inserire tramite la galleria.

Sempre che il carousel sarà reintrodotto. Gli utenti odiano i carousel.

**Comment by SimoSca** [comment]
Ditemi voi.

Al limite se poi si decide di introdurre questa opzione, allora si può mandare una mail a tutti i produttori per aggiornarli.

Volevo solo capire:

1. va solamente tolto il fatto di essere obbligatorio, o vogliamo rimuovere del tutto la possibilità di inserire delle immagini all'iscrizione?

2. se rimuoviamo del tutto l'inserimento di immagini allora credo che vada rimossa anche la pagina `foowd_utenti/gallery` raggiungibile da `foowd_utenti/profilo`, o quella la vogliamo lasciare?

Thanks

**Comment by DDDamage** [comment]
In effetti le necessità di:
- immagine
- descrizione azienda
 
Vengono meno in fase di registrazione data l'eliminazione della pagina produttore.
Puoi toglierle dalla registrazione, ma lasciarle nel profilo (sia gallery che descrizione), così da poterle inserire se tornassero necessarie.

Altre sistemazioni dei dati sono:
- Denominazione società invece che ragione sociale
- inserire "Nome e cognome titolare" come campo obbligatorio
- Nome titolare e partita iva non modificabili dopo la validazione del profilo

**Comment by SimoSca** [comment]
Della validazione del profilo non si è ancora parlato, pertanto vorrei sapere come dovrebbe procedere... In tal senso probabilmente potrei fare una pagina accessibile solo agli amministratori, in cui inserire la lista dei produttori in sospeso, con un pulsante del tipo "approva", in modo da cambiare il suo stato in approvato.
In sostanza una cosa simile a quella per la chiusura delle prenotazioni.
Anche in questo caso quando il produttore viene approvato, si potrebbe mandargli una mail di notifica (come al solito il testo dovreste scrivermelo voi).

Che ne pensi?

**Comment by DDDamage** [comment]
A me sembra ci sia già (ho validato l'altro giorno Ale Poletti)

Cmq intendevo "non modificabili dopo la registrazione"

**Comment by SimoSca** [comment]
Chiedo scusa per il tempo trascorso e cito @coder-molok e @Panciz per consulto:

per il momento il DB contiene delle voci semplici come

* `name` in cui si salva la username

Pensati per i produttori:

* `location` che attualmente non viene utilizzato e in teoria dovrebbe contenere un riferimento geografico

* `address`, ovvero l'indirizzo: forse sarebbe da spezzettare in campi piu elementari come cap, provincia, via, civico e paese ?

Allo stato attuale i campi `Nome e Cognome` Titolare non esistono, pertanto se li devo creare penso possa essere utile suddividerli, magari denominandoli `HolderName` e `HolderSurname` ?

@DDDamage : 

prima di fare nuovi test di registrazione e recupero password voglio chiarire i punti sopra citati.

**Comment by DDDamage** [comment]
Sono dei campi che servono a noi come riferimento dell'azienda, per fare dei controlli.

Il tuo suggerimento di spezzettarli in campi più piccoli è corretto, per evitare errori di inserimento, ma poi alla fine dei conti vengono utilizzati tutti insieme (vengono collassati in un unico campo?)

**Comment by SimoSca** [comment]
@DDDamage  mi spiego meglio:

mi stavo concentrando sul come salvarli nel DB.

La presentazione del form spezzettando, come hai sottolineato, penso sia la piu' adeguata, ma ero interessato alla rispettiva gestione nel DB: ad esempio unendo `nome` e `cognome` in un unico campo (ad esempio `holder`) e stesso discorso per l'indirizzo, o se tenere separati i campi anche nel DB, onde poterli maneggiare piu' agilmente qualora si decida di svolgere delle operazioni sui dati.

@coder-molok e @Panciz 
Allo stato attuale maneggiamo solo gli utenti e nel DB i dati, azienda inclusa, sono campi dell'utente.
Potrebbe forse essere utile creare una tabella in cui salvare esclusivamente i dati relativi all'azienda, e legarla in una relazione gli  utenti? Ad esempio due soci della stessa azienda potrebbero entrambi iscriversi con un proprio account e creare delle offerte: in tal caso tutti i dati relativi all'azienda sarebbero in condivisione.

**Comment by SimoSca** [comment]
Ho posto ora questo problema perche' allo stato attuale questa scelta non va a incidere in nessuna API , ne quelle da BackEnd ne da FrontEnd, pertanto chiarire ora le idee non andrebbe ad intaccare alcun lavoro, se non quello di salvataggio dei dati al momento dell'iscrizione.

**Comment by Panciz** [comment]
Simone sono d[accordo con te che mettere assieme utente e azienda e' abbastanza limitativo.
Condivido anche che sia un attivita' separabile dal resto e non avrebbe molto impatto.

Al momento non la ritengo fondamentale pero direi di concentrarsi su altro.

**Comment by SimoSca** [comment]
Non voglio spenderci tempo, pero' devo sapere come vogliamo salvare i dati: chiarita questa idea ci ritroveremo con un form di registrazione fatto adeguatamente, e a quel punto penso che si sia raggiunta un'altra pietra miliare nello sviluppo.

Chiedo a @coder-molok e @DDDamage di darmi delucidazioni in merito al salvataggio di questi dati,
tenendo presente che creare una tabella e una api per il salvataggio dei dati secondo quanto indicato, non mi dovrebbe comportare un eccessivo impiego di tempo.

**Comment by DDDamage** [comment]
Salvali come dati uniti (es. holder)

Per quanto riguarda la divisione dati utente/azienda, non è necessario ora

**Comment by SimoSca** [comment]
Ho aggiornato tutto, pertanto riepilogo i casi di registrazione:

* se si iscrive un utente standard allora tutto avviene in automatico (validazione inclusa)

* se si iscrive un utente che si propone come "offerente":
- egli riceve una mail per confermare la sua iscrizione al sito (come anche l'utente standard)
- quando clicca/apre il link per confermare puo' accedere alle funzionalita' degli utenti standard, e agli amministratori giunge una mail per essere informati della richiesta di un nuovo produttore
- gli amministratori dal pannello possono raggiungere la pagina [http://5.196.228.146/elgg-1.10.4/foowd_utenti/evaluatingUsers](http://5.196.228.146/elgg-1.10.4/foowd_utenti/evaluatingUsers): in questa pagina cliccando sul link possono accedere alle impostazioni utente e modificarle: in fondo trovano il select per far divenire l'utente un'offerente
- se l'utente diventa un'offerente, allora viene notificato del fatto che viene accettato

Anche in questo caso i testi delle mail dovreste suggerirli voi.

@DDDamage : 
Ho provveduto a unificare tutti i dati utenti in una sola pagina.
Inoltre mi confermi che cosi' l'iter va bene?

**Comment by SimoSca** [comment]
Extra per @DDDamage 

elgg ad ogni utente associa, tra i vari, due campi: `username` e `name`: il secondo sarebbe semplicemente la visualizzazione con la quale l'utente puo' apparire sul sito. 
Per esempio lo username deve essere univoco, mentre il name no: potrebbero esserci piu' utenti che vogliono essere visualizzati semplicemente come 'Simone'.

Allo stato attuale per tenere tutto snello ho fatto in modo che username e name siano sempre gli stessi e NON modificabili. Puo' andare bene?

Inoltre dalle impostazioni utenti ho tolto la possibilita' di modificare la password: quella vogliamo lasciarla, o va bene cosi'?

Conta che quanto riguarda quest'ultimo post consta di operazioni per me modificabili a tempo zero, pertanto controproponi pure.

**Comment by coder-molok** [comment]
Mi sembra tutto ok, aspettiamo comunque la conferma di @DDDamage su iter e una mail di testi da Fede (gli scrivo io).

Aggiungo questo dettaglio: sarebbe complicato mettere nella mail di notifica agli admin un link automatico come l'esempio che segue?

L'utente con id 223 si e' iscritto proponendosi come produttore. 
Puoi visualizzare i dati da lui immessi andando nell'apposita sezione del sito. 
 http://5.196.228.146/elgg-1.10.4/foowd_utenti/evaluatingUsers/223

in modo che apra direttamente il dettaglio del soggetto? (magari l'URL corretto è diverso... non ho controllato)

**Comment by SimoSca** [comment]
No, per nulla.
Quando scrivete i testi delle mail (suggerisco come gia' fatto di implementare pensando alla funzione php vsprintf(...) ) tenete tranquillamente conto del fatto che lo posso aggiungere.

**Comment by SimoSca** [comment]
Inoltre nel corpo della mail che riceve l'utente si potrebbero inserire i links al pannello utente, alla pagina per la creazione offerte e ai propri settings. Pertanto basta che mi preparate il modello della mail, e la generazione dei links è assolutamente easy per me.

**Comment by DDDamage** [comment]
Appena supero un messaggio a cui rispondere sbabbio.. comunque mi sa che mi devo pronunciare solo su due cose:
- l'iter è corretto
- odio la dualità tra username e name. Non si può fare che venga utilizzato ovunque sempre e solo lo username? Con le stesse regole di modifica (es. non posso avere uno username già preso) che si possono trovare in molti siti (es. istagram)

**Comment by SimoSca** [comment]
* Non uso instagram, quindi un elenco delle modifiche me lo dovresti scrivere.

* Sono in pieno accordo: elgg questa duplicita' ce l'ha intrinseca, pertanto per non incombere in questo problema ho provveduto a forzare il fatto che il campo `name` deve essere uguale allo `username`, cosi' di fatto sovrascriviamo questa dualita'. Io per completezza nel sito e nelle email faccio sempre uso dello username.

**Comment by DDDamage** [comment]
In sostanza istagram (non ce l'ho neanche io) ti identifica con lo username e il name è solo di contorno. 
- Puoi modificare lo username, a patto che non sia già preso.
- Per il login utilizzi lo username
- Il tuo riferimento visualizzato è sempre lo username (ed è quello utilizzato per le ricerche)

Sempre in istagram, il name compare in chiaro sotto allo username ed è utilizzato per scrivere il proprio nome completo.. è un'informazione secondaria. 

Ad ogni modo, ci conviene ragionare sul name nel momento in cui si sistema la parte di ricerca amici. Serve solo ed esclusivamente per rendere la ricerca più agevole per chi conosce il tuo nome reale ma non lo username su foowd.

**Comment by SimoSca** [comment]
@DDDamage 
Il form di registrazione e' completato.
Se ho ben capito quello che manca per completare questa parte e' il fatto che quando si cercano amici, oltre allo username bisogna anche fare un controllo sul nome?

**Comment by DDDamage** [comment]
Non riesco ancora a capire cosa sono "user name" e "nome visualizzato"

Fai così:
- Nel form scrivi solo "nome utente", come primo campo. Deve essere il riferimento unico dell'utente, utilizzato per il login.
- Sotto metti un campo con "Altri nomi", usato unicamente come campo aggiuntivo per la ricerca tra amici

Per quanto riguarda la ricerca (scusa se "inquino" questa issue):
- cambia l'intestazione della ricerca in "Cerca (Nome o Email)
- per ora non funziona con ricerche parziali (es. cerco "tommy" non mi trova "tommy_user")
- attento che se mi cerco da solo e clicco sul mio nome mi accede alla seguente schermata
![ricerca amici](https://cloud.githubusercontent.com/assets/13355694/12946475/0aac81a2-cff5-11e5-95da-aefc852f1809.png)
con possibilità accedere alla pagina elgg standard di modifica profilo

**Comment by SimoSca** [comment]
Ma non mi avevi detto di fare come in instagram?
Username è il nome univoco monoparola, mentre nome visualizzato è una qualsiasi stringa... Ad esempio io mi possoo iscrivere come  superfigo84 ma poi inserire simone sca come nome visualizzato: in questo modo se qualcuno mi conosce può eventualmente cercarmi come simone sca, come quando cerchi le amicizie di facebook.

**Comment by SimoSca** [comment]
La ricerca:

Quella è la pagina base di elgg: in teoria quando cerchi qualcuno ti rinvia a quella pagina.

Per il momento della ricerca e di come deve avvenire mi sembra non si fosse ancora parlato in dettaglio, e tantomeno delle pagine profilo.
Mi dovreste spiegare più in dettaglio cosa volete, ma in una issue a parte per favore.

**Comment by DDDamage** [comment]
Ok

**Comment by SimoSca** [comment]
>* Nel form scrivi solo "nome utente", come primo campo. Deve essere il riferimento unico dell'utente, utilizzato per il login.
>* Sotto metti un campo con "Altri nomi", usato unicamente come campo aggiuntivo per la ricerca tra amici

Questi li ho svolti. Penso che questa issue si possa chiudere.
