### ISSUE TITLE
Invio mail di iscrizione anche se avviene un errore

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#193]
Ho provato a creare un utente sulla mia installazione, mentre non funzionava correttamente la connessione lato api_foowd.
Non è stato creato l'utente, ma la mail di conferma è partita ugualmente.

Verifichiamo se è possibile intercettare l'errore (qualunque) ed evitare di conseguenza l'invio mail.

**Comment by SimoSca** [comment]
pazzesco... per risolvere questo bug, ho dovuto spendere un tempo abnorme... sia lodato elgg!

In ogni caso ora funziona: l'utente in caso di errore (mancanza comunicazione con servizio API) non riceve la mail e viene rinviato a una nostra pagina d'errore.
