### ISSUE TITLE
Wall - posizionamento minibar

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#194]
Ho fatto un po' di prove spostando la barra in una posizione più sensata. Facendolo mi sono però accorto che il suo posizionamento era difficoltoso nei post ridotti nel wall.
![problema barra fuori area offerta](https://cloud.githubusercontent.com/assets/13355694/12848872/aeb04ad6-cc1c-11e5-9352-0d72a1135502.png)

Soprattutto considerando che era all'interno dell'header del post..
Quindi l'ho messa nel post container (modificando l'html solo per quel post) e ho cambiato qualche parametro dello stile css per avere l'effetto ricercato.
![spostamento barra](https://cloud.githubusercontent.com/assets/13355694/12848972/3ad9a75a-cc1d-11e5-97c3-264126effcdf.png)

**Comment by DDDamage** [comment]
Lo stile corretto è:

.mini-progress-bar {
height: 20px
right: 8px
bottom: 6
}

**Comment by SimoSca** [comment]
@DDDamage 

Ho dovuto impostare il bottom a 31px, ma credo che cosi' vi sia l'effetto desiderato.
Se cosi' va bene direi che questa si puo' chiudere.

**Comment by DDDamage** [comment]
Non so come mai, ma sembra che i tag siano comunque persi in considerazione per il posizionamento.
![minibar](https://cloud.githubusercontent.com/assets/13355694/12945040/381ba50a-cfeb-11e5-81d9-24b7cd106863.png)

Credo che 31px funzioni solo per i post con le offerte su una riga

**Comment by SimoSca** [comment]
Ok, allora il problema e' il posizionamento mi sto alle sue dimensioni... ora provo ad applicare un paio di trick.

**Comment by SimoSca** [comment]
Ora dovrebbe andare.

**Comment by DDDamage** [comment]
Giusto per essere pignoli:
`.mini-progress-bar {   margin-top: -28px; }`

**Comment by SimoSca** [comment]
Finish!

**Comment by DDDamage** [comment]
Purtroppo l'errore di posizionamento persiste quando i tag occupano più righe.

![Uploading minibar1.png…]()

![minibar](https://cloud.githubusercontent.com/assets/13355694/12984371/a8a3c7f0-d0ed-11e5-9e7e-1414f362c76a.png)

**Comment by SimoSca** [comment]
ok, ora dovrebbe andare...

**Comment by DDDamage** [comment]
Yes!
