### ISSUE TITLE
Wall - area dettaglio prodotto e tag

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#196]
I tag devono essere spostati fuori dal post container, altrimenti sarà impossibile assegnar loro una funzione diversa dal "vedi dettaglio propotto"

![tag fuori click dettaglio prodotto](https://cloud.githubusercontent.com/assets/13355694/12849214/b1d71eae-cc1e-11e5-9404-ebc9e499f8a1.png)

Ho anche cambiato lo stile dei tag 
.product-post-body {
font-size: 10pt;
}
..e del contenitore del post per visualizzare la manina quando si passa sopra le offerte:

.post-container {
cursor: pointer;
}

Non comprendo la dicitura <wbr> </wbr> e non so quali azioni si possano assegnare ai tag. L'ideale è che al click il tag singolo venga aggiunto alla barra di ricerca e il wall venga ricaricato filtrato. Ad ogni modo questa cosa si rimanda alla issue relativa ai miglioramenti della barra di ricerca.
![strano formato tag nel wall](https://cloud.githubusercontent.com/assets/13355694/12849284/346f3432-cc1f-11e5-829b-ddbe67886bb4.png)

**Comment by DDDamage** [comment]
Non so se spostando i product-post body ci siano dei problemi a livello di "a capo" o in generale del posizionamento del testo sotto le immagini. Certo è che non voglio che i tag ti portino al dettaglio del prodotto.

**Comment by SimoSca** [comment]
> I tag devono essere spostati fuori dal post container, altrimenti sarà impossibile assegnar loro una funzione diversa dal "vedi dettaglio propotto"

Non e' cosi'... o per meglio dire: attualmente e' cosi' perche' va bene in questo modo, ma quello non e' un problema... non ho organizzato quella ramificazione, ma mi sembra sensata, pertanto cosi' va bene. Ti suggerisco di pensare solo agli stili, non alla gestione della tree: se ci sara' bisogno di dare delle azioni ai tags, si puo' fare senza problemi. I css hanno tantissime opzioni (una chiamata z-index in questo caso), pertanto e' tutto ampliamente plasmabile, se generato da noi.

**Comment by SimoSca** [comment]
> Non so se spostando i product-post body ci siano dei problemi a livello di "a capo" o in generale del posizionamento del testo sotto le immagini. Certo è che non voglio che i tag ti portino al dettaglio del prodotto.

Similmente a quanto scritto prima, ma vorrei capire una cosa: adesso come adesso ti va a capo in automatico?
A me lo fa, e volevo sapere se anche a te funziona come dovrebbe.

**Comment by DDDamage** [comment]
Sì va a capo in automatico. 

A me interesserebbe che il post-body nn interagisca come se fosse il corpo vero e proprio dell'offerta (richiamando il dettaglio). Ho pensato di tirarlo fuori altrimenti per sistemare questa cosa bisogna anche aggiungere la funzionalità ai tag, quindi alla barra di ricerca, quindi ai filtri nel wall, ecc..

**Comment by DDDamage** [comment]
Ah.. inoltre spostarlo fuori mi è servito a ottenere il riposizionamento della  #194.

Altrimenti il post-body mi faceva da spessore e non riuscivo a posizionare la barra avendo come unico riferimento l'area dell'immagine del post

**Comment by SimoSca** [comment]
Ho appena aggiornato i due stili qui richiesti.

Inoltre:

> Altrimenti il post-body mi faceva da spessore e non riuscivo a posizionare la barra avendo come unico riferimento l'area dell'immagine del post

anche in questo caso e' solo un fattore di stili: si puo' lavorare su css o sulla tree, va semplicemente a gusti/conoscenza.
Io la tree non la tocco: non conoscendo profondamente tutto il codice non so se rischio di andare a modificare alcuni hook.

**Comment by DDDamage** [comment]
Credo che il post-container sia la parte trasformata (rimpicciolita) se si tira fuori può causare problemi nel posizionamento e dimensione (larghezza) dei tag messi sotto. Si può risolvere nello stesso modo creando un altro contenitore all'interno del post container

post- container
       **post-contenitore nuovo**
               post image thumbnail
               post header
       post body (TAG)

**Comment by DDDamage** [comment]
Riguardo all'andare a capo, tag vanno a capo finchè rimangono all'interno del post-container

**Comment by SimoSca** [comment]
Se ho ben capito: post-contenitore-nuovo e post-body devono essere allo stesso ilvello, e post image, post header e mino progress li posiziono dentro a post-contenitore-nuovo?

Inoltre fatto questo applic gi stili delle iss#194 ?

**Comment by DDDamage** [comment]
Sì, questo è il modo che avevo individuato io per risolvere la posizione della barra..
La modifica alla gerarchia serve a non causare errori di a capo nei tag (il ridimensionamento dei post opera sul post-container, a quanto sembra), una volta tirato fuori il tag dal "corpo" del post.

In questo modo sono possibili anche futuri riarrangiamenti della barra all'interno del post.

**Comment by DDDamage** [comment]
Se questo procedimento ti va bene per risolvere la #194, allora cambio la milestone anche di questa

**Comment by SimoSca** [comment]
Appena aggiornata.
Va bene cosi'?

**Comment by DDDamage** [comment]
Ok, chiudo questa perchè comunque la vera issue da risolvere è la #194.

Se questa ti ha aiuta a risolverla bene, altrimenti ti ho dato delle indicazioni fuorvianti e mi spiace.
