### ISSUE TITLE
Wall - aggiunta nome azienda di fianco a lente

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#197]
Stavo provando ad creare un'anteprima di questa cosa ma firefox ha iniziato a bloccarmisi un po' spesso.
![aggiunta nome aziende a dx della lente](https://cloud.githubusercontent.com/assets/13355694/12849936/76194320-cc22-11e5-8095-55a771c543b8.png)

Ad ogni modo, vorrei che il nome dell'azienda che ha postato l'offerta appaia di fianco alla lente (e sia parte dell'area di click che porta al sito del produttore). Credo che si possa usare direttamente lo stile .product-post-name che è quello valido per le scritte sopra

**Comment by DDDamage** [comment]
Se hai problemi con il posizionamento della scritta (ho visto dei riarrangiamenti) e il problema è causato anche dalla minibar, avvisami che troviamo la soluzione più comoda

**Comment by SimoSca** [comment]
Si ho avuto problemi, ma credo che cosi' com'e' adesso dovrebbe andare bene...

**Comment by DDDamage** [comment]
Ricorda di mettere lo stile della scritta uguale a quelle altre presenti nell'offerta (perlomeno il carattere AkkuratBold)

**Comment by SimoSca** [comment]
quel font deve essere solo per il nome dell'azienda o per tutto il post?

**Comment by DDDamage** [comment]
Per tutto il post, lo usiamo ovunque

**Comment by DDDamage** [comment]
Anzi no, i tag sono in AkkuratRegular

**Comment by SimoSca** [comment]
Giusto per capire... TUTTO il sito deve avere quel font? perche' se e' cosi' lo inserisco nel body e via!

Te lo chiedo perche' vedo che il font e' specificato in varie classi, e non so se e' stata una scelta dovuta a ragionamenti che avete fatto voi o altro...


Se veramente tutto deve essere in quello stile, allora inserendolo nel body ogni cosa si aggiusta senza pensieri per il futuro....

**Comment by DDDamage** [comment]
Credo sia dovuto più al fatto che marco abbia aggiustato il font man mano dove serviva.

Nel progetto grafico tutti i font sono AkkuratRegular o AkkuratBold
[foowd_web specifiche.pdf](https://github.com/coder-molok/foowd_alpha2/files/126626/foowd_web.specifiche.pdf)
Quindi procedi pure a metterlo in tutto il sito.

**Comment by DDDamage** [comment]
Ne approfitto che questa issue è ancora aperta e che hai già aggiunto il nome azienda nel wall.
Se è possibile con poco sforzo, aggiungi il Nome Azienda anche nel Board e nel Dettaglio Prodotto, sotto al nome del prodotto. Avendo tolto la pagina personale del produttore queste informazioni mancano in entrambe le pagine.

Style AkkuratRegular dimensione 66% del nome del prodotto

**Comment by SimoSca** [comment]
#### Wall:
Ho messo tutto cio' che e' sovrapposto all'immagine (che per comodita' chiamo main frame) in akkuratbold.

Tutto il resto, quindi i tags, in akkuratregular

#### Board e dettaglio prodotto

ho aggiunto i nomi, ma ti chiedo la cortesia di scrivermi esattamente lo stile da applicare: come vedi gli allneamenti sono molto ravvicinati. Ora che li ho inseriti dovrebbe essere facile testare l'effetto che desideri.

**Comment by DDDamage** [comment]
Board:  AkkuratRegular 12px
Dettaglio: AkkuratRegular 12px

Per quanto riguarda l'interlinea non c'è problema, cambiando lo stile vengono incasinate anche le altre parti del menù.
