### ISSUE TITLE
Funzionalità barra

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#201]
Nella issue #199 issue sono state anticipate delle funzionalità di filtro di ricerca con i tag, e  ricerca in generale, attualmente non richiesti.. è necessario ripristinare alcuni aspetti allo stato precedente, per evitare alcuni problemi tra cui l'impossibilità di trovare un prodotto cercandolo direttamente per nome.
![bagoss](https://cloud.githubusercontent.com/assets/13355694/12877035/7e0d1764-ce0c-11e5-8d4a-06a22ca73585.png)
 

Le seguenti indicazioni si riferiscono riferimento alle necessità **attuali** della barra di ricerca, per quanto riguarda la **messa online del sito**:
- rimuovere invio automatico dei dati ad ogni digitazione
- la ricerca avviene quando si preme invio
- rimuovere variazioni di colore
- modifica in cursore di testo al passaggio del mouse
- lasciare la ricerca nei campi come era in precedenza
- inserire autocompletamento in fase di digitazione da elenco tag

EDIT l'autocompletamento può anche essere rimandato alla milestone successiva

**Comment by coder-molok** [comment]
Simone, occorre anche bloccare la ricerca se la barra è mostrata nelle pagine elgg, in quanto intercetta il focus e blocca i form.

Inoltre controlla il form di inserimento offerta, se funziona dopo la correzione: al momento non mi si apre la pagina.

**Comment by DDDamage** [comment]
A volte anche le mie indicazioni possono essere fuorvianti. Quando ho parlato di cursore verticale intendevo quello del mouse, per intenderci:
![24_cursor_styles](https://cloud.githubusercontent.com/assets/13355694/12914142/f455f2ee-cf22-11e5-9b4e-06fd16152db9.gif)

Non capisco perchè adesso sia comparso un altro cursore fisso che ha la stessa funzione di quello orizzontale. Non ha molto senso.
![cursore](https://cloud.githubusercontent.com/assets/13355694/12914170/17868de6-cf23-11e5-9e0d-526a0a9406cf.png)

La mia indicazione `.foowd-brand { cursor: text; }` si riferiva esattamente a quello stile e a quel parametro. Nel senso che quando il mouse passa sopra la barra di navigazione da freccina diventa barra verticale. **Il mouse** non un altro elemento aggiunto nella pagina

**Comment by SimoSca** [comment]
@coder-molok 

Sistemato il bug: ora si possono creare nuove offerte e modificare quelle gia' presenti.

Preciso che attualmente non viene svolta alcuna chiamata alla digitazione della ricerca:
visto che le offerte sono gia' caricate nel wall, allo stato attuale mi limito a fare un'ispezione veloce via jquery, e ai tag metchanti aggiungo un background associato al colore del tag: risulta istantaneo e praticamente a onere zero.

Riprendendo i punti:

>rimuovere invio automatico dei dati ad ogni digitazione
>la ricerca avviene quando si preme invio

vuoi che li realizzi o in base a quanto spiegato va bene cosi'?

> rimuovere variazioni di colore

ok, ma vorrei capire meglio: 

che effetto si dovrebbe ottenere nel wall per le offerte coi tag matchanti?

> modifica in cursore di testo al passaggio del mouse

fatto

> lasciare la ricerca nei campi come era in precedenza

come era fatta in precedenza?


> inserire autocompletamento in fase di digitazione da elenco tag

questo e' abbastanza piu complicato... visto che lo devo sviluppare da zero, vorrei che mi spiegaste esattamente che effetto volete: dove devono apparire i suggerimenti, evidenziare il primo, usare freccia alto e basso per muoversi sui suggerimenti, etc.

**Comment by SimoSca** [comment]
@DDDamage :

avevo capito la tua idea, ma personalmente reputo che in un campo input un cursore verticare per capire dove viene inserito il carattere ci vuole... ad esempio se mi accorgo che il terzo tag e' scritto male, posso usare il mouse per andarci sopra, e quindi il puntatore verticale mi fa capire esattamente dove sto scrivendo.

Condivido con voi questo pensiero. Se mi dici che non serve provvedo a eliminarlo, ma tieni presente che cosi' si limita molto il campo di input.

Ah per inciso: in realta' quello non e' un campo di input... ho creato un modulo javascript che ne imita il funzionamento. Con un normale campo di input gli effetti colorati e sopratutto le azioni al click sono impossibili da generare...

**Comment by DDDamage** [comment]
Ok, troviamo una soluzione: la necessità che hai segnalato è corretta, ma la barra verticale vanifica un po' la coerenza a livello di brand/stile

Sarebbe possibile svolgere lo stesso compito con una barra orizzontale tale e quale all'underscore solito?
In pratica aggiungi all'underscore le funzionalità della barra verticale che hai aggiunto.
Quando ci si sposta dalla posizione terminale, l'underscore intermittente si sposta assieme al punto in cui viene inserito il testo.

**Comment by SimoSca** [comment]
Mo me la meno: immaginando questa richiesta, per mantenere tutto il piu generale possibile ho implementato facendo in modo di poter inserire qualsiasi cosa al posto della barra verticale!
Ci possiamo mettere immagini, underscore e qualsiasi altro simbolo vogliate. Devo solo fare un paio di assestamenti al codice, ma e' un'inezia.

**Comment by DDDamage** [comment]
Sembra molto fico! 
Ocho che se torno a metà del testo e provo ad inserire uno spazio non lo fa nella posizione attuale ma alla fine della stringa

**Comment by SimoSca** [comment]
Si, quello l'ho fatto apposta: ho pensato che se uno inserisce uno spazio in genere vuole scrivere un nuovo tag, pertanto lo mando in fondo.
Altrimenti si puo' pensare che quando inserisci uno spazio puoi decidere di spezzare la stringa in due, come se avessi generato due tag... l'importante e' avere le idee chiare, in quanto la suddivisione in tag, e tutte le skill richieste per i click, richiedono comportamenti ben piu complessi di quelli inerenti un semplice campo di input.

**Comment by DDDamage** [comment]
Sì non stiamo a complicare la cosa.. in ogni caso i tag sono semplicemente le uniche parole che vengono autocompletate, per il resto dovrebbe essere una barra di ricerca normale

**Comment by SimoSca** [comment]
Si, ma guarda che per realizzarla ho dovuto usare 300 righe di codice... a primo acchito sembra banale, ma dovendo essere sviluppata per interazioni specifiche, ha richiesto non poco lavoro... se vedi con l'inspector oltre al testo ho dovuto continuamente generare e spostare contenitori e ricreare tutti gli effetti tipici di un campo input.
In ogni caso, ora che e' implementata si puo' farci praticamente di tutto.

**Comment by SimoSca** [comment]
Escludendo la mia digressione...
cosa manca per completare questa issue? 
In particolare non ho ricevuto risposta per quanto concerne il mio [commento](https://github.com/coder-molok/foowd_alpha2/issues/201#issuecomment-181814702)

**Comment by DDDamage** [comment]
Immagino sia stato un bel lavoro.. bene se ti è servito a mettere una buona base.
1) rimuovere invio automatico -> ok
2) la ricerca avviene quando si preme invio -> non ancora. I risultati non vengono filtrati
3) rimuovere variazioni di colore -> non so bene quale effetto mettere con i tag matchanti, è difficile trovare dei colori che stiano bene sia sulla barra che a sfondo bianco, e comunque temo sia una corrispondenza che nessuno noterebbe
4) modifica in cursore di testo al passaggio del mouse -> ok quando si passa sulla stringa inserita, ma il puntatore dovrebbe avere lo stesso stile anche nel resto della barra. Se ti ci devi mettere a risolvere questo dettaglio, va bene così
5) lasciare la ricerca nei campi come era in precedenza -> di base la ricerca veniva effettuata nei campi dell'offerta (titolo, descrizione). In questo modo si può trovare un prodotto per nome specifico (es. produttore che vuole vedere la sua offerta o i concorrenti). Quindi ricerca nei campi e/o tramite tag
6) inserire autocompletamento in fase di digitazione da elenco tag -> ok, lascia stare. Per ora va bene così e basta che ci sia la base per inserirlo in seguito. Ti servono troppi dettagli e lavoro per realizzarla, apro una issue con milestone avanzata

**Comment by SimoSca** [comment]
3) forse basta scegliere un colore unico: personalmente penso che un minimo di riscontro possa aiutare l'utente.
Ad esempio se match a il titolo si potrebbe mettere il background verde o viola e idem per i tag.
Un'altra opzione spartana potrebbe essere magari di mettere un bordo, ad esempio verde, con ombreggiatura ai post che matchano. In questo modo si risolverebbe il fatto che il testo non si vede e quindi non si può evidenziare.

4) l'avevo pensato cosi perché la scritta foowd è cliccabile e porta al wall... In generale tutto ciò che al click apre una pagina ha la mano come puntatore. Dimmi cosa preferisci.

5) ora controllato solo i tag... Dunque mi confermi che i match funzionano su titolo, descrizione e tags?

Gli altri punti li considero risolti

**Comment by DDDamage** [comment]
3) tienile buone come idee, per adesso lascia stare ho aperto la #203 
4) non fraintendermi: va bene il dito sulla scritta foowd.. è la parte a dx che deve mostrare il "cursore testo". Per ora lo mostra solo sulla parte di stringa scritta _tag_tag_tag, ma nn sulla parte vuota a dx
5) Sì i match funzionano su titolo, descrizione e tag

**Comment by SimoSca** [comment]
4) il cursore testo per ora é l'underscore lampeggiante... Se non stai modificando nulla all'interno del testo, il puntatore dovrebbe appunto essere l'underscore finale, in teoria lampeggiante.

**Comment by DDDamage** [comment]
ARGH
Non riesco a non generare incomprensioni su questa cosa.
Mi riferisco al mouse. Al puntatore, a forma di 
![index](https://cloud.githubusercontent.com/assets/13355694/12958458/27bac852-d032-11e5-92f8-b77408e96397.png)
Quando con il mouse passi sopra alla parte marrone della barra di navigazione

**Comment by SimoSca** [comment]
Ora come ora dovrei aver sistemato quanto richiesto.

Riassumendo: per ora nella search, che funziona solo nel wall, le parole immesse vengono ad essere colorate se sono dei tag. La ricerca avviene nella descrizione, titolo e lista tags, cercando SOLO i tags.

Allo stato attuale, se trova i tag, non abbiamo alcun riscontro grafico.

**Comment by DDDamage** [comment]
Ok buono. Quando riprendiamo in mano tutto valutiamo bene cosa mettere.

Considera che la strategia nel pubblicare il sito sarà far vedere le cose più importanti ma inserire gradualmente le "chicche" a livello di brand.

**Comment by coder-molok** [comment]
Per il funzionamento della barra, aggiungo una semplificazione da fare quando riprendiamo in mano il tutto: una volta inserito un tag (riconosciuto a livello di autocompletamento: vedere specifiche in futuro) questo diventa indivisibile/immodificabile: o si lascia o si toglie.
(( quindi il discorso dello spazio che porta in fondo (per cominciare un nuovo tag) lo toglierei, perché forza un comportamento che potrebbe non essere chiaro all'utente ))

**Comment by SimoSca** [comment]
Probabilmente un compromesso, ma che deve essere ben delinato a livello di interfaccia, potrebbe essere di eliminare il tag ma appenderlo sotto alla search, e renderlo cliccabile per l'eliminazione.
Un po come l'effetto che adesso abbiamo quando in un'offerta vogliamo aggiungere/rimuovere il tag.

**Comment by DDDamage** [comment]
Ho provato a digitare delle chiavi di ricerca e schiacciare invio:
I risultati non vengono filtrati nè inserendo tag nè parole contenute negli altri campi

**Comment by SimoSca** [comment]
come ho scritto:

> Allo stato attuale, se trova i tag, non abbiamo alcun riscontro grafico.

Filtra, ma non mi avete spiegato quale effetto vorreste... in teoria devono apparire solo i post che matchano? 
Mi sono sentito con davide perche' attualmente la gestione del wall avviene con l'impiego di strumenti che non conosco e personalmente vorrei trovare una soluzione: adesso come adesso si continua a ricaricare tutto da zero, e nell'idea che i prodotti non siano poche decine, ma di qualche centinaio, e' sostanzialmente un impiego di risorse che per l'utente potrebbe gravare non poco.
Intanto faccio avvenire il ricaricamento del wall. 
Vi avviso quando finisco.

**Comment by DDDamage** [comment]
Sì devono apparire solo i post che matchano.
Adesso che hai reso la barra fica e accattivante non possiamo lasciarla lì senza alcuna funzione ;)

**Comment by SimoSca** [comment]
Ora visualizza i post che in qualche modo matchano i tag, ed ho inserito un piccolo effetto fadeout-fadein per rendere tutto piu semplice.
E' da buona parte della serata che lotto con lo switch alla modalita' gruppo, in quanto la lunghezza della barra non viene riscalata bene, ma se non ci fai caso manco si nota.
Purtroppo questo e' il solito problema di prendere mano al codice non proprio... sviscerare e andare a trovare il punto esatto a volte richiede un dispendio pazzesco di energia.

In ogni caso visto che dovro' rivedere anche le API quando decideremo esattamente come deve avvenire la search, direi che grossolanamente questo punto si puo' chiudere, aprendo eventualmente una issue per quanto segnalato.

**Comment by DDDamage** [comment]
Molto fico.
Con dei tag un po' sensati nelle offerte può già funzionare bene
