### ISSUE TITLE
Ricerca utenti

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#204]
Dalla issue #191 
Per quanto riguarda la ricerca:
- cambia l'intestazione della ricerca in "Cerca (Nome o Email)"
- deve con ricerche parziali (es. cerco "tommy" non mi trova "tommy_user)
- attento che se mi cerco da solo e clicco sul mio nome mi accede alla seguente schermata 
![ricerca amici](https://cloud.githubusercontent.com/assets/13355694/12980752/29eef9fc-d0de-11e5-8729-3ee6f855b502.png)
- effettuare matching sia su username che su altri nomi

**Comment by SimoSca** [comment]
Ora visualizza gli utenti che contengono la parola all'interno della mail o del nome o dello username.
Dal risultato viene escluso l'utente stesso (ovvero se cerco me stesso).

Per il momento vengono visualizzati anche coloro che sono gia' amici.

**Comment by DDDamage** [comment]
Non so per quale ragione alcuni utenti me li trova (es. molok, simo), altri no (es. CybTroll, alessandro).

**Comment by SimoSca** [comment]
Prova ora

**Comment by DDDamage** [comment]
Certi risultati sono duplicati:
![ricerca2](https://cloud.githubusercontent.com/assets/13355694/13284478/ca91888c-daf4-11e5-862b-55ed0cb657d7.png)
![ricerca](https://cloud.githubusercontent.com/assets/13355694/13284479/ca978c64-daf4-11e5-9043-3d8c95f9c780.png)

**Comment by SimoSca** [comment]
Risolta.
