### ISSUE TITLE
Spostare gestione offerte in pannello produttore

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#206]
Spostare due sottemenu "crea" e "modifica offerte" nella parte alta della pagina vicino alle prenotazioni, sopra la linea verde.

![elgg produttore](https://cloud.githubusercontent.com/assets/13355694/12985157/658feeea-d0f1-11e5-9c4c-ea9eba4d9a41.png)

**Comment by SimoSca** [comment]
Fatto.
