### ISSUE TITLE
Conteggio quote non chiaro

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#208]
Con alcuni miglioramenti la pagina di dettaglio potrebbe migliorare:
- sostituire "carrello" con "quote"
- sostituire "tot" con "carrello"
- aggiungere altra sezione sopra "carrello" e "quote" che riporta la dimensione della quota (come nel wall)

**Comment by SimoSca** [comment]
Fatto, suggerisco di guardare.
Quale icona bisogna utilizzare nella nuova sezione con l'unita' di misura?

**Comment by DDDamage** [comment]
Ho visto. Ti posto un'anteprima di come sistemarlo:
![dettaglio](https://cloud.githubusercontent.com/assets/13355694/13249905/2d6f3856-da27-11e5-8926-aaf8b5e5b13a.png)

Per ora va bene così. Successivamente potremo sistemare la posizione delle varie informazioni nel dettaglio e nel wall per renderle più chiare

**Comment by SimoSca** [comment]
credo che cosi' possa andare.

**Comment by DDDamage** [comment]
.commercial-menu-item .item-container .item-data
{ letter-spacing: 0pt; }

Con -1 i caratteri sono troppo appiccicati

**Comment by SimoSca** [comment]
Per tutti o solo per quello contenente le unita' di misura?

**Comment by DDDamage** [comment]
Per tutti direi.. già l'Akkurat è un carattere compatto non serve ridurre la spaziatura

**Comment by SimoSca** [comment]
Fatto.
