### ISSUE TITLE
Messaggio di errore in inglese

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#209]
Se provo ad inviare un messaggio senza oggetto o contenuto del messaggio, mi restituisce (correttamente) un errore, però è in inglese:
![messaggio errore](https://cloud.githubusercontent.com/assets/13355694/12985671/1d39b7ae-d0f4-11e5-9acf-ccc1fb2c05d5.png)

**Comment by SimoSca** [comment]
Risolto.
In generale se possibile scrivetemi anche il testo con cui sostituire.

La traduzione di elgg e' composta da circa 1000 vocaboli, pertanto penso sia sensato che si continui ad aprire issue man mano che si incontrano testi non tradotti, a meno che qualcuno non voglia prendersi la briga di tradurre a testa china, ma penso sia uno spreco di tempo.

**Comment by DDDamage** [comment]
Ok per quelli corretti.

Altri messaggi nello stesso ambito:
"Your message was susccessfully sent" -> il tuo messaggio è stato inviato con successo
"You did not selected someone to send this to" -> inserisci un destinatario

**Comment by SimoSca** [comment]
Ora dovrebbero andare.

PS:
in merito alla ricerca automatica dell'utente: i messaggi e la sidebar appartengono a due plugin diversi, per questo nei messaggi e' presente questa gradita skill.
Come ogni cms elgg e' un mondo vasto!
