### ISSUE TITLE
wall url ad API tramite valore configurato 

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#21]
Come per il plugin offerte sarebbe importante che anche la parte base degli url richiamati dal plugin theme fosse configurata com opzione del plugin Vedi issue https://github.com/coder-molok/foowd_alpha2/issues/11

**Comment by predorock** [comment]
Se nel client Javascript lo prendiamo dalle impostazioni di `foowd_util` tramite `elgg_get_plugin_setting('api', \Uoowd\Param::uid()` è ancora necessario impostarlo all'interno del tema foowd_theme?

**Comment by Panciz** [comment]
No non e' p[iu necessario. Lo impostiamo nel plugin utility perche' e' un parametro comune a tuttu i nostri plugins.
