### ISSUE TITLE
Chiusura ordine

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#210]
Dal board non riesco a chiudere l'ordine. Il click sul carrello non sortisce alcun effetto (nè in modalità singolo che di gruppo)

**Comment by SimoSca** [comment]
Sempre parte della GUI: mi devi specificare esattamente cosa deve avvenire... solo chiudere il gruppo, aggiornare l'interfaccia, visualizzare un messaggio? quale testo? etc.

**Comment by DDDamage** [comment]
Il pulsante "action buy-group" non reagisce quando provo a cliccarci sopra. Si tratta del pulsante per chiudere l'ordine, il "carrello".

![pulsante chiudi ordine](https://cloud.githubusercontent.com/assets/13355694/12995750/0eeffb0a-d12a-11e5-8048-693caa0fc8ea.png)

**Comment by SimoSca** [comment]
Risolta. Anche in questo caso non so che resa grafica si deve avere all'avvenuta ordinazione.
Sia qui nella board che nel dettaglio prodotto, a livello grafico mi dovete dire cosa vorreste inserire.
Ad esempio al posto del carrello potrebbe apparire un lucchetto, e la barra potrebbe diventare tutta gialla o un colore simile, sostituendo i dato con un trattino per far capire che l'offerta e' bloccata.
Al click si puo' porre un allert del tipo "Proddotto gia' prenotato", oppure qui nel board farlo sparire del tutto.
Direi che se mi volete dare dettagli, potete aprire una issue o scrivere ancora su questa e su quella del singolo prodotto.

**Comment by DDDamage** [comment]
Ok ci pensiamo

**Comment by coder-molok** [comment]
Mi sono allineato con @DDDamage, per la board andiamo avanti in questa issue:

Al click della conferma ordine il comportamento dovrebbe essere il seguente:
+ messaggio di conferma avvenuta registrazione dell'ordine:
   "L'ordine è stato preso in carico, ti stiamo inviando una mail con i dettagli."
Questo messaggio va lanciato col normale strumento di notifica sulla pagina (il messaggio che scompare da solo dopo alcuni secondi)
+ dissolvenza della riga relativa all'ordine (indicativamente in 5'', da verificare)
+ collassamento delle righe che rimangono in modo da colmare il "vuoto" che si viene a creare.
        (questo può cominciare due o tre secondi dopo la dissolvenza e avvenire rapidamente,
         comunque verifichiamo l'effetto una volta pronto)

In questo modo l'utente non può più interagire con la riga in questione, ma per sicurezza blocchiamo le interazioni dopo il click dell'ordine, in modo da evitare side-effects.

Tutte le animazioni si possono ottenere con transizioni CSS, eviterei di usare sistemi diversi.
Se qualcosa è complicato per via della struttura della pagina avvisaci prontamente che valutiamo il da farsi.

**Comment by SimoSca** [comment]
per il momento ho impostato la dissolvenza a 5s e anche l'effetto slide a 5s.
Magari lo slide lo porterei a 2 o 3 s.

**Comment by coder-molok** [comment]
Io direi di portarlo a 2, altrimenti il tutto dura troppo, ma hai messo lo
slide DOPO la dissolvenza? Perché io intendevo tutto assieme, se non è
possibile accorcia la dissolvenza a 3'' e slide a 2'' così fanno 5'' in
tutto.

Seconda cosa: dopo il click passano comunque alcuni attimi (dal mio pc
siamo sui due secondi, che sembrano lunghissimi) senza che accada nulla...
servirebbe almeno cambiare immediatamente cursore a clessidra (o orologio,
quello che rappresenta l'attesa, insomma) per dare il feeling che qualcosa
è stato attivato.

M

2016-02-20 16:13 GMT+01:00 Simone S. <notifications@github.com>:

**Comment by SimoSca** [comment]
Risolto la seconda.

La prima si puo' fare, ma visto che @DDDamage mi aveva detto che andava bene, quando l'ho svolta, vorrei sapere se anche per lui devo applicare questi change.

**Comment by DDDamage** [comment]
Sì, io mi stavo "accontentando" :P

**Comment by SimoSca** [comment]
Hehehe mai! Specialmente se lavoriamo in sinergia: sul momento mi e' strafacile modificare il codice, e se non si puo' almeno lo giustifico subito.
Ho impostato a 5s.

Se non vi piace, suggerisco di usare gli strumenti da sviluppatore del browser e fare le prove sul parametro "animate" della classe ".preference-fadeOut".

**Comment by DDDamage** [comment]
Come da chat

.preference-fadeOut {
animation: hide 1s forwards linear, enfold 2s forwards linear; 
}

Rende l'effetto più leggero e apprezzabile

**Comment by SimoSca** [comment]
anche per molok?

**Comment by coder-molok** [comment]
Provato, confermo i tempi suggeriti da @DDDamage, modificato.

**Comment by SimoSca** [comment]
Ho visto che hai gia' svolto un commit, quindi chiudo la issue.
