### ISSUE TITLE
Errore imprevisto chiusura ordine

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#211]
Quando chiudo l'ordine in modalità di gruppo, mi visualizza il seguente errore, anche se l'ordine sembra essere chiuso correttamente (le quote vengono scalate a me e agli amici)
![messaggio errore](https://cloud.githubusercontent.com/assets/13355694/12986042/93668ed8-d0f5-11e5-9651-b7e9e15284d9.png)

**Comment by coder-molok** [comment]
@DDDamage , l'immagine che hai messo mi pare sia la stessa dell'errore del messaggio #209

**Comment by SimoSca** [comment]
Concordo... inoltre quell'errore dev'essere proprio lato elgg, in quanto per il momento i messaggi nn li ho toccati nemmeno di striscio.

**Comment by SimoSca** [comment]
In ogni caso qualunque errore appaia specifico che fa parte dell'interfaccia grafica, pertanto mi ci vuole tempo per poter colmare certi problemi.

**Comment by DDDamage** [comment]
Ops
![errore](https://cloud.githubusercontent.com/assets/13355694/12995628/28e92802-d129-11e5-98d4-40aff208b812.png)

**Comment by DDDamage** [comment]
Ma credo che funzioni, è la notifica in rosso che è strana..

**Comment by SimoSca** [comment]
Ora funzia.
La gui non so come dovrebbe comportarsi alla convalida dell'ordinazione.

**Comment by DDDamage** [comment]
Intendi il messaggio?

**Comment by coder-molok** [comment]
La UI deve aggiornarsi: in questo modo mi aspetto che, avendo cambiato stato delle preferenze, il prodotto scompaia dalla board.

**Comment by SimoSca** [comment]
Come scritto, ditemi voi che effetto volete...
Se farla sparire oppure cambiargli colore etc.
Ad esempio io la sovrasterei con un giallo pastello semitrasparente, e inserirsi una scritta del tipo "in avanzamento" e applicherei questo stile a tutte le offerte che sono appunto in stato di avanzamento, così per il momento la board funge anche da riepilogo. Eventualmente quelle bloccate perché in una prenotazione non ancora chiusa, possono essere visualizzate in fondo.

**Comment by DDDamage** [comment]
Senza aggiungere effetti particolari rendiamo piu chiaro quello che c'è. Sostituirei il messaggio con:
"Prenotazione inviata e quote rimosse dalle preferenze.
A breve riceverai una mail di riepilogo"

Come diceva molok deve sparire, con una dissolvenza (se si mantiene lo stesso effetto delle altre pagine)?

**Comment by coder-molok** [comment]
Io intendevo semplicemente: Forzare un refresh della board.
Con l'aggiunta del messaggio, se possibile, passando al refresh il messaggio da visualizzare, in modo che si veda dopo o assieme alla scomparsa del prodotto.

**Comment by SimoSca** [comment]
Dunque dalla pagina dettaglio prodotto, una volta svolta la prenotazione eseguire un redirect alla board? 
Se e' cosi' per comodita' fare in questo modo: se la prenotazione e' andata a buon fine, manderei un allert del tipo: "Ordine avvenuto con successo! ora verrai reindirizzato alla tua board." e fare un redirect alla board dopo diciamo 5 secondi.
Che ne dite?

**Comment by coder-molok** [comment]
Direi di no, meglio non fare alcun cambio pagina.

Se l'utente chiude l'ordine dalla Board aggiorniamo la board,
se l'utente chiude l'ordine dal dettaglio prodotto aggiorniamo il prodotto 
(oltretutto, @DDDamage nel caso apriamo una nuova issue, ma la disponibilità residua non viene mostrata?)

**Comment by SimoSca** [comment]
Per la board sono daccordo, ma per il dettaglio prodotto, questi puo' essere aggiornato portando tutto a zero, ma senza bloccare tasti o altro e' forviante. Io da utente mi chiederei: "e ora che ho fatto partire l'ordine perche' ho ancora dei tasti da cliccare?"

**Comment by coder-molok** [comment]
Bhè... se uno ha letto la guida lo capisce che il + è per aggiungere nuove preferenze e il - per rimuoverle... il carrello dovrebbe scomparire, non avendo più il numero di preferenze minimo richiesto.

In generale, è meglio se non si cambia "pagina" all'utente.

Eventualmente modificheremo il messaggio chiarendo che "ora puoi esprimere nuove preferenze per questo prodotto".

**Comment by SimoSca** [comment]
Si, ma se hai appena fatto un'ordinazione quel prodotto e' bloccato fino a quando non viene chiusa la prenotazione, pertanto questi tasti non comportano alcun effetto... probabilmente non ero stato chiaro, sorry.

**Comment by coder-molok** [comment]
Lo chiedo qui (invece che in mail privata) apposta perché rimanga: mi chiarisci 

> quel prodotto e' bloccato fino a quando non viene chiusa la prenotazione

??
Ero certo che in questo momento, alla conferma, parta immediatamente la mail di conferma e le preferenze passano subito in stato "sended".

**Comment by DDDamage** [comment]
vedi #223.

Comunque vi pregherei di fermarvi un attimo prima di fare troppe proposte. In molti casi sono problemi rimandabili, aggirabili o trascurabili. Altre volte è meglio analizzare bene la questione, perchè magari le idee non sono molto chiare. Se ognuno parte subito a proporre soluzioni le issue diventano kilometriche e caotiche.

**Comment by SimoSca** [comment]
D'ora in poi certe issue non le risolvero' fin quando non avro' esplicitamente il benestare sia di @DDDamage che di @coder-molok . 
Non fraintendetemi: so che rimanere aggiornati su tutto e' difficile, ma non posso prendermi briga di rispiegare certe decisioni. Per questo penso sia meglio che continuiate ad aggiornarvi tra di voi.

Thanks.

**Comment by SimoSca** [comment]
### Ciclo di Chiusura:

Allora... premettendo che non ricordo chi mi aveva detto di fare cosi', ma ho ricevuto specifiche su come ESATTAMENTE un'ordine doveva essere gestito ed ora lo riepilogo:

1. quando viene raggiunta la quota minima del prodotto (puo' essere il singolo utente o il gruppo) un utente decide di cliccare per prendere in carico l'ordine: tutte le preferenze bloccate passano in stato "pending" e l'utente non puo' creare nuove preferenze su quel prodotto. Inoltre nel database si crea una nuova purchase in stato "opened"
2. parte istantaneamente un primo giro di email per avvisare che un utente si e' reso disponibile a gestire l'ordine. Da questo momento in poi tutto passa nelle mani di capo gruppo e produttore e gli utenti non possono piu' modificare la preferenza (bloccata in quanto "pending")
3. il capogruppo o voi amministratori decidete di chiudere l'ordine perche' il produttore o il capo gruppo hanno avvisato (questa parte penso che avverra' tra di voi tramite giri di mail o telefonicamente) che l'ordine e' evaso. A questo punto la purchase e le preferenze passano in stato "solved" e tutto viene concluso.
4. solo ora che non vi sono piu preferenze in stato pending l'utente puo' nuovamente esprimere una preferenza su tale prodotto e partecipare ad altri gruppi.

Mi era stato detto di fare cosi', e credo che possa avere senso, perche' altrimenti io come utente potrei dimenticarmi di aver ricevuto la mail di notifica e di essere parte di un gruppo, ed attualmente non esiste nessuna pagina "storico" che mi faccia capire se su qualche prodotto avevo gia' ordinazioni o meno. 

Allo stato attuale le preferenze e l'ordinazione in terminate (solved) NON vengono cancellate: visto che si e' agli inizi, suggerisco di conservare i dati in modo da poterli riprendere qualora in futuro si vogliano aggiungere skill come storici, o statistiche base per i venditori. Per deformazione accumulo sempre dati se possibile. Se poi i dati inzieranno ad essere troppi si puo' pensare di scremarli.
E' proprio in luogo a questo pensiero che i check avvengono sugli stati.

Se qualcosa non e' chiaro chiedete, perche' queste fasi sono importanti.

**Comment by DDDamage** [comment]
Puoi semplicemente far sparire i tasti?

**Comment by SimoSca** [comment]
si, ma cosi' un utente potrebbe chiedersi come mai non ci siano i tasti.
Senza fare cose ricercate, al posto dei tasti si potrebbe visualizzare un testo tipo "offerta scaduta" per le scadute e "offerta gia' presa in carico" per quelle facenti parte di un'ordine ancora da chiudere.

**Comment by DDDamage** [comment]
Puoi lasciare i tasti e mettere il popup con gli avvisi che hai appena citato, "offerta scaduta" e "offerta già presa in carico", al click sui tasti + e -

**Comment by SimoSca** [comment]
Risolta.

**Comment by DDDamage** [comment]
Non ho avuto modo di testare bene. Mi sembra che i messaggi nel dettaglio non vengano mostrati

**Comment by SimoSca** [comment]
Prova questa:

http://5.196.228.146/elgg-1.10.4/detail?productId=56

Naturalmente si sta parlando della pagina dettaglio: se mi confermate che gli allert fatti cosi' vanno bene, provvedo poi ad aggiornare la Board con gli stessi criteri.

**Comment by DDDamage** [comment]
Ok ho testato anche "offerta già presa in carico"
