### ISSUE TITLE
Protezione chiamate API

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#213]
Evitare usi impropri delle funzionalità del sito.

Le chiamate backend devono solo avvenire dal forntend e da utenti registrati. 

@Panciz sapevi già come fare?

**Comment by SimoSca** [comment]
Sistemato: ora abbiamo il controllo dell'origine lato Slim Frameword/Api e tutte le chiamate del sito vengono filtrate lato backend via Elgg EXPOSE.

D'ora in poi tutto verra' filtrato da elgg.
