### ISSUE TITLE
Errore della barra di ricerca

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#214]
(provato sul sito di sviluppo) se scrivo x es. "Montasio" e premo spazio o invio non succede nulla, nonostante il Montasio ci sia.
In ogni caso mi aspetterei che il wall si svuotasse non trovando nulla, piuttosto che rimanere uguale.

**Comment by SimoSca** [comment]
Non e' un bug: [commento iss#201](https://github.com/coder-molok/foowd_alpha2/issues/201#issuecomment-183121419)

>Ora visualizza i post che in qualche modo matchano i tag[...]

@DDDamage e @coder-molok 
Come ho scritto, tutto e' attualmente basato sui tag. Se volete altri criteri, vi chiedo prima di accordarvi tra di voi e poi di citarmi una volta giunti a un accordo.

**Comment by coder-molok** [comment]
Ok, ma hai citato un tuo commento... 
Forse c'è una incomprensione: rileggendo la #201 vedo che Tommy ha riportato che "I risultati non vengono filtrati nè inserendo tag **nè parole** contenute negli altri campi", ma in seguito si parla solo di un generico "match".
La ricerca per un generico termine (esempio lampante il nome proprio di un prodotto) deve rimanere come ricerca base.

Probabilmente, dato che era così inizialmente, io e Tommy abbiamo dato per scontato che dovesse continuare a funzionare la "ricerca libera".
-- @DDDamage correggimi se non è così, ma mi sembrerebbe un assurdo --

**Comment by DDDamage** [comment]
Sì molok confermo quello che dici, forse non sono riuscito a spiegarmi, o non sono riuscito a formalizzare correttamente il concetto.

La ricerca deve mostrare:
- Tutte le offerte che contengono almeno uno dei tag contenuti nella ricerca
e
- Tutte le offerte che hanno in un campo qualsiasi almeno una parola inserita nella ricerca.

In realtà la seconda condizione include la prima, in quanto i tag sono parole contenute in un campo dell'offerta.

**Comment by SimoSca** [comment]
Ok, mi pare giustissimo.
Ho solo bisogno di capire come volete formalizzarla, pertanto spiego in dettaglio:

adesso la ricerca veniva fatta solamente ogni volta che si otteneva un tag, pertanto non avveniva ad ogni digitazione di tasto... chiedo nello specifico:

la ricerca deve partire ad ogni digitazione di singolo tasto, o soltanto dopo aver lasciato un spazio, in quanto cosi' considerata parola intera?

ad esempio, se nella search ho

1. `bag` -> per il momento nulla perche' e' una parola parziale
2. `bagoss` -> per il momento nulla perche' potrei continuare a inserire altri caratteri
3. `bagoss_`-> vuol dire che dopo bagoss e' stato premuto uno spazio, pertanto bagoss e' esattamente la parola che voglio cercare.

oppure basta che la parola, se non e' un tag, superi ad esempio 3 caratteri?

Punto su questo fatto perche' la ricerca, nel momento in cui vi saranno molti post, potrebbe divenire piuttosto onerosa. Per il momento sto lavorando sul wall al fine di ridurre il numero di chiamate superflue e dare un rendering grafico adeguato. Ad ora portava quello che a mio avviso era un grave problema di fondo, ovvero caricava tutti i post in una volta sola, cosa che diviene chiaramente onerosa qualora si inizi ad avere gia' qualche centinaio di post.
Per ora sto lavorando per fare in modo che i caricamenti e le search avvengano a blocchi di 20 post (numero a caso).

**Comment by DDDamage** [comment]
Per ora la ricerca può benissimo essere effettuata solo schiacciando "invio" una volta terminata la digitazione.

**Comment by SimoSca** [comment]
Ok!
Mi piace. In ogni caso se vengono digitati dei tags la faccio partire automaticamente o rimane tutto vingolato alla pressione dell'invio?

**Comment by DDDamage** [comment]
Lascia solo con l'invio, tranquillo

**Comment by SimoSca** [comment]
Ok! 
In ogni caso nella ricerca utilizzo solo le parole con almeno tre lettere, altrimenti diviene troppo vaga.

**Comment by coder-molok** [comment]
A parte il lancio della ricerca, riesci a mantenere la colorazione automatica dei tag mentre si digita?

mi spiego:
foowd_ lombardi                       <- non succede nulla
foowd_ lombardia                     <- riconosce il tag, lo colora, ma NON parte la ricerca
foowd_ lombardia_cacio           <- viene aggiunto "cacio" in nero, ma NON parte la ricerca
foowd_ lombardia_cacio[invio]  <- lancia la ricerca con cacio e il tag lombardia

Se **non** richiede lavoro aggiuntivo è comunque un buon feedback all'utente

**Comment by SimoSca** [comment]
In linea di principio dovrebbe fare proprio cosi'... ti chiedo di riprovare e confermare o meno questo bug.

**Comment by DDDamage** [comment]
La ricerca e la colorazione dei tag funziona.

Faccio solo notare che un tag appena inserito (nella stessa sessione) non viene colorato. A chiusura e riapertura del browser funziona correttamente.
