### ISSUE TITLE
Stile nome azienda non caricato correttamente

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#218]
Lo stile del nome dell'azienda dovrebbe essere Regular, mentre appare come Bold
![stile produttore](https://cloud.githubusercontent.com/assets/13355694/13033613/a09b8dcc-d31d-11e5-92e9-e7887a097756.png)

**Comment by SimoSca** [comment]
Impostato a AkkuratRegular, con font-weight normal.
Credo che cosi' possa andare.
