### ISSUE TITLE
Correzioni minori form di inserimento offerta

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#219]
Facendo la guida ho trovato di dover correggere alcuni testi per rendere più chiaro il form di inserimento dell'offerta:
- invertire posizione quantità/unità di misura
- "quantità per quota" -> "dimensione quota"
- "quote minime per spedizione inclusa"
- "numero massimo quote" -> "disponibilità in quote"
- "scadenza" -> "offerta valida fino a"

**Comment by SimoSca** [comment]
Cosi' dovrebbe andare,

**Comment by DDDamage** [comment]
Quando clicco su diversi campi (senza digitare nulla), mi iniziano a comparire i flag su tutti i campi, uno per volta, e rimangono

![offerta](https://cloud.githubusercontent.com/assets/13355694/13056022/fe9b9bba-d412-11e5-861e-7f13c0878e1b.png)

**Comment by SimoSca** [comment]
Sono campi obbligatori, pertanto non possono essere vuoti.
Ho inserito un controllo in simultanea per renderlo dinamico, perche' per esperienza e' comodo.
Vi chiedo di dirmi che condizioni volete, perche' questa parte e' ricca di venti.. mouseover/mouseout/onclick/onfocus etc...

**Comment by DDDamage** [comment]
- Il check dei campi obbligatori è sufficiente quando si fallisce ad inviare il form.
- Il controllo in simultanea /onfocus è sufficiente. Nel senso che mi visualizza il flag solo quando sto digitando

**Comment by SimoSca** [comment]
Cosi' dovrebbe andare.
Anche se esce dal contesto di questa issue, ti chiedo di controllare anche il form di registrazione e modifica dell'utente: anche li ho inserito vari controlli, e se non piaciono li rimuovo senza problemi.

**Comment by DDDamage** [comment]
Va bene
