### ISSUE TITLE
Correzioni minori form registrazione

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#221]
Compare un flag "nome inserito non corretto" quando si seleziona il campo "Nome utente", e non va più via anche se il nome è valido
![nome registrazione](https://cloud.githubusercontent.com/assets/13355694/13048368/b03d1714-d3e5-11e5-8e7b-3093c634e0b0.png)

Il campo "sito internet" accetta solo domini. Serve che prenda anche indirizzi di pagine perchè potrebbe essere che i produttori vogliano linkare la propria pagina facebook.
![nome registrazione](https://cloud.githubusercontent.com/assets/13355694/13048392/dd2b3986-d3e5-11e5-993f-46dee5d881ea.png)

**Comment by SimoSca** [comment]
Ora dovrebbe andare.
