### ISSUE TITLE
Prodotti caricati solo se loggati

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#222]
Il wall appare vuoto se l'utente non è loggato.
![wall vuoto](https://cloud.githubusercontent.com/assets/13355694/13048488/75d0126a-d3e6-11e5-914f-168b0fcdfdf3.png)
Abbiamo bisogno di rendere visibile i prodotti anche da utenti non loggati. Ci sono ragioni di brand (trasparenza e accessibilità)

**Comment by coder-molok** [comment]
Scusa @DDDamage , in quale ambiente hai provato?
Su sviluppo non ho questo comportamento, 
su produzione non ho prodotti...

Sto sistemando un problema di invio mail, dopodiché potrai registrarti e provare.

**Comment by SimoSca** [comment]
Era dovuto a degli aggiornamenti che ho fatto al wall. Ora dovrebbe funzionare.
