### ISSUE TITLE
apertura link con tasto destro

### ISSUE THREAD

**Issue by SimoSca** [coder-molok/foowd_alpha2#224]
@coder-molok e @DDDamage 

premetto che questa e' assolutamente marginale, ma se senza pensieri potrei prendermene cura man mano che provvedo alle altre issues.

E' una questione di design e di utilizzabilita' del Wall. Ad ora i bottoni e le immagini  si aprono al click come e' giusto che sia, ma per esempio non e' possibile aprirli in altre tab col tasto destro.
Questo perche' gli elementi non sono posizionati nel tag `<a href="...">`, di conseguenza un'utente non ha neppure la preview sul link a cui si rimanda.

Questo non e' un problema, ma e' un fatto di praticita'. Quando giro su siti come amazon e ebay, sono abituato a usare la ricerca per filtrare, e poi ad aprire i link in altre tab per non perdere la ricerca. Questa e' la mia esperienza utente, che non so se e' confrontabile con voi altri, ma ho voluto condividerla.

Ripeto, non e' importante, ma e' una skill sulla quale mi confronto con altri siti e che detesto se mancante.

EDIT:
questa issue ha un riscontro anche a livello di posizionamento: per com'e' adesso i parser delle pagine vedono il wall come una pagina piatta e senza link, proprio per la mancanza di questi tag.
In genere avere link non ripetuti aiuta in parte il posizionamento. Non sono un esperto, pero' rammento che questo e' un fattore piuttosto utile. 
Ad esempio i bot di google non rintracciano le pagine e i contenuti generati via javascript: e' uno dei motivi per i quali ad ora i siti che hanno bisogno di visibilita' utilizzano javascript in maniera ponderata.

**Comment by coder-molok** [comment]
In effetti concordo, potresti rinominare la issue: "apertura link con tasto
destro" o simili?

Dovremmo creare un documento di "Best practice foowd" di dettagli tecnici
da applicare ovunque (se non c'è già) e inserire questo.

Per la modifica, portala pure avanti "man mano che ti imbatti" nei vari
link.

Marco
Il 16/feb/2016 15:07, "Simone S." <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
In realtà da backend, essendo principalmente PHP ho sviluppato tutto coi classici tag, pertanto questo riguarda solamente la gestione di wall, board e dettaglio prodotto. A dire il vero mi ha spiazzato perché era da tempo che non vedevo dello JavaScript direttamente nei tag. Ma questo riguarda più che altro gusti personali.

Penso che non sia il caso di scriverlo in un documento (che io sappia per ora non esiste nemmeno uno di best practice), anzi se vuoi credo che questa issue potremmo gia chiuderla.
