### ISSUE TITLE
Localizzazione utenti/produttori/prodotti

### ISSUE THREAD

**Issue by SimoSca** [coder-molok/foowd_alpha2#226]
Tempo fa si era parlato della localizzazione, ma tra le tante faccende da sbrigare il discorso è stato un poco accantonato.

Partendo dal presupposto che ora il filtro di ricerca è basilare, probabilmente un'opzione utile in futuro potrebbe essere ad esempio la ricerca dei prodotti filtrando per regione.
Un'altra cosa che da utente, in futuro, mi potrebbe interessare, è la ricerca dei produttori a me vicino, pertanto anche senza impazzire potrei voler cercare per regione/provincia/città, e discorso simile per le amicizie.

Con quest'idea in mente, mi chiedo se sia il caso di inserire un campo "località" quando:

* un utente si registra, specifica la sua localita' 

* produttore, un produttore potrebbe specificare sia la sua localita' che quella dell'azienda che rappresenta (potrebbero anche non coincidere, pertanto farei due campi). In quest'ultimo caso il produttore in realta' ci darebbe l'indirizzo dell'azienda, pertanto potremmo risalire noi all'opportuna localita' (ma non posso farlo con un filtro: dovrebbe poi essere inserito manualmente).

* ad un prodotto e' possibile associare una localita': un'azienda lombarda potrebbe anche vendere dei prodotti veneti.

Tutti questi campi inoltre potrebbero semplicemente essere opzionali.

In questo caso sarebbe opportuno decidere se la localita' e' solo una regione, una provincia, una citta', etc. Se ad esempio fosse una citta', con poco sforzo si puo' impiegare una selezione multipla in cui scelta la regione mostra l'elenco delle provincie, e dopo le provincie mostra un elenco dei paesi. Da sviluppare sarebbe molto semplice.

Rammento che per ora non viene utilizzata, ma potrebbe essere utile iniziare gia' a raccogliere i dati man mano che le persone si iscrivono e le offerte create.

Come abitudine le mie proposte non le inserisco in nessuna milestone, lasciando che siate voi a decidere se sono utili o meno.

**Comment by DDDamage** [comment]
Per la localizzazione con funzione di ricerca dei prodotti, cerchiamo di usare i tag. Se fosse necessario, potremo facilmente risalirci tramite l'indirizzo dell'azienda. Esempio: si aggiornano i tag "origine" in maniera più specifica?  - val camonica, lodigiano, oltrepo - si vanno ad aggiornare i tag delle offerte in base all'indirizzo dei produttori che le hanno pubblicate

La localizzazione degli utenti era stata ipotizzata per rendere possibile la creazione di gruppi tra persone sconosciute ma vicine. Con il fatto che ora i gruppi si creano solo tra amici, è diventata superflua.

**Comment by SimoSca** [comment]
Se e' superflua, catalogala pure come risolta: ben venga!
Come detto adesso non e' per nulla indispensabile, ma mi stavo chiedendo se fosse gia' il caso di raccogliere i dati come opzionali.

In ogni caso specifico:

1. non e' detto che il luogo del produttore e del prodotto coincidano. In generale penso che sara' cosi', ma non mi viene da lasciarlo per scontato

2. per l'azienda, visto che nel form l'indirizzo e' una semplice stringa, non e' scontato riuscire a risalire automaticamente al luogo. In tal caso comunque si potrebbe fare manualmente quando si verificano i dati, pertanto su quello concordo.

In ogni caso per le offerte l'utilizzo di tag per regione ci puo' stare.

**Comment by DDDamage** [comment]
Sì, chiudo.

Un giorno foowd sarà un social in cui sconosciuti faranno la spesa assieme, a quel punto la localizzazione sarà fondamentale. Soprattutto la nostra localizzazione in qualche isola tropicale ;)
