### ISSUE TITLE
Sulla maschera ai post (sfondo testo)

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#227]
Dalla #203, che è naufragata dal suo titolo

Ho verificato che in effetti la maschera c'era, infatti l'immagine bagoss originale era questa:
![formaggio bagoss](https://cloud.githubusercontent.com/assets/13355694/13174904/043228ae-d707-11e5-9e67-a8e5fc3f581c.jpg)
Mentre questo come appare nel wall (disattivando le ultime modifiche da css)
![wall](https://cloud.githubusercontent.com/assets/13355694/13174972/8b32dc18-d707-11e5-9908-d68676ab5c4c.png)

Quindi la maschera c'era e aveva l'effetto voluto.
I problemi di leggibilità (che io comunque non ho rilevato) possono essere trattati in un'altra issue e si trovano soluzioni coerenti con il resto.

ELIMINA dal css
.tint  {
background: rgba(0, 0, 0, 0.2) none repeat scroll 0% 0%; 
}

Altrimenti abbiamo due maschere sovrapposte, e così le immagini appaiono troppo scure.

**Comment by SimoSca** [comment]
Mea culpa!
in alcuni test avevo tolto tint in locale, dunque ti do completamente ragione: effettivamente marco l'aveva inserita.
Provvedo nel primo pome a inserirla, comunque chiudo la issue.
