### ISSUE TITLE
Barra ricerca prodotti in altre pagine

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#231]
Ma la barra di ricerca potrebbe avere le stesse funzionalità in tutte le pagine? Riportando al wall nel caso non ci sia già?

Inoltre ti segnalo che ho trovato una barra non desiderata nella pagina ricerca utenti:
![barra](https://cloud.githubusercontent.com/assets/13355694/13284512/0a012e82-daf5-11e5-938b-b0c0cc7d4711.png)

**Comment by SimoSca** [comment]
Dalla chat su telegram:

> Sto facendo delle prove per risolvere i problemi di keyboard coi dispositivi touch, pertanto per il momento non vi conviene fare test. Quando finisco vi avviso.
 
Solo per quello vedi l'errore: stavo facendo degli esperimenti.

**Comment by SimoSca** [comment]
Scusami, avevo scritto di fretta. Il primo commento e' relativo alla barra non desiderata.

Invece per quanto riguarda

> Ma la barra di ricerca potrebbe avere le stesse funzionalità in tutte le pagine? Riportando al wall nel caso non ci sia già?

Mi dovresti spiegare meglio cosa intendi, please.

**Comment by SimoSca** [comment]
In base a quanto stabilito:
* il wall continua a comportarsi come fatto sinora
* nelle restanti pagine se si va sul brand sinistro il puntatore e' una mano e al suo click si reindirizza al wall.

**Comment by DDDamage** [comment]
Ok

**Comment by SimoSca** [comment]
L'ho gia' implementato: come al solito ti chiedo di verificare.

**Comment by DDDamage** [comment]
Perfetto
