### ISSUE TITLE
Profilo - campi non corrispondenti a registrazione

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#233]
Nella pagina di modifica del profilo i campi "Nome visualizzato" e "username" devono corrispondere con quelli inseriti in fase di registrazione:
- Nome utente
- Altri nomi
![profilo](https://cloud.githubusercontent.com/assets/13355694/13400585/c64057a0-df08-11e5-998c-ce039ce3e894.png)
Mettere le stesse etichette per evitare confusione

**Comment by SimoSca** [comment]
Corretto.
