### ISSUE TITLE
I pop-up sovrastano il menù

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#234]
Questa issue si riferisce a:

Cookie policy -> spostare in basso alla pagina.
![policy](https://cloud.githubusercontent.com/assets/13355694/13435520/00feb08a-dfdb-11e5-8289-0496e4d01347.png)

Avvisi elgg -> aggiustare posizione in modo che non copra il menù. Può essere un po' più in basso, pur mantenendo la posizione generica "in alto a destra", che rimane la posizione maggiormente rilevante nelle pagine.
![popup](https://cloud.githubusercontent.com/assets/13355694/13435530/0aa58d84-dfdb-11e5-8fb8-fae0da90df05.png)

**Comment by SimoSca** [comment]
Sistemato
