### ISSUE TITLE
Condizioni d'uso e accettazione esplicita

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#236]
Create già la pagina per le condizioni generali, il link relativo e il check di accettazione nel form di registrazione.

Due punti da dipanare:
1) se l'utente sceglie "offerente" le condizioni generali devono essere affiancate anche da quelle specifiche (concettualmente). Possiamo farlo mettendo una dicitura specifica tra il link e i check che cambia da "dichiaro di accettare le condizioni generali d'uso e in particolare i paragrafi xx, yy, zz"
a "dichiaro di accettare le condizioni generali e le condizioni specifiche per gli offerenti in ogni loro parte."

2) nella pagina predisposta con il Lorem ipsum, è semplice mostrare un PDF? magari in Iframe? in questo modo chi lo legge lo può anche salvare/scaricare.
Se è complicato copio il testo e poi aggiungo un link al PDF, ma sarebbe meglio tenere il tutto "univoco"

**Comment by SimoSca** [comment]
1) 
una volta specificati esattamente i testi, mi e' semplice aggiungere dinamicamente alle condizioni generali quelle specifiche per l'utente qualora questi selezioni la tipologia "offerente".

2)
non ho mai provato, ma cercando su internet ho visto che basta usare il tag `embed`. 
A inizio pagina ho inserito un semplice pft di test, e sembra funzionare. Il file e' stato salvato in **FoowdStorage/Public** ma dimmi pure in quale path vorresti salvare l'originale.

**Comment by coder-molok** [comment]
L'idea di base sarebbe di avere un unico PDF con tutte le condizioni separate in sezioni diverse, quindi alla voce di presa visione si dovrebbe specificare quali sezioni in particolare si devono accettare, posto che l'utente abbia preso visione di tutte le condizioni d'uso.
Questo perché di fatto un offerente potrà fare anche acquisti, un utente qualunque può diventare Capo Gruppo (che ha una sezione apposita nelle condizioni) o addirittura un utente, facendo richiesta a noi, potrebbe diventare offerente.

Quindi: un link fisso a una pagina che mostra il pdf, da cui si può anche scaricare e salvare in locale.
Un testo variabile tra utente semplice e offerente con la specifica delle sezioni che in particolare si intende accettare; i testi precisi li posso fornire sono a Condizioni d'Uso completate.

**Comment by SimoSca** [comment]
Una volta forniti i testi provvederò a inserirli.

**Comment by coder-molok** [comment]
[Condizioni_di_uso-foowd.it.pdf](https://github.com/coder-molok/foowd_alpha2/files/210668/Condizioni_di_uso-foowd.it.pdf)

Ecco il PDF definitivo.

Le frasi di flag sono, per l'utente semplice:
"Accetto le **Condizioni generali d’utilizzo** e le **Condizioni specifiche** disponibili al seguente link, in particolare accetto le condizioni delle sezioni **Generale** e **Disposizioni relative ai CapiGruppo**"
mentre per l'utente offerente:
"Accetto le **Condizioni generali d’utilizzo** e le **Condizioni specifiche** disponibili al seguente link, in particolare accetto le condizioni delle sezioni **Generale** e **Disposizioni relative ai Professionisti**"

**Comment by SimoSca** [comment]
Sulla VPS di sviluppo puoi visualizzare le modifiche apportate: per ora il check dell' accettazione delle condizioni avviene solo via frontend, inoltre il file viene salvato in **FoowdStorage/Public/Files/**.

1) Ti chiedo di dirmi se cosi' funziona come volevi, e se l'estetica e' di tuo gradimento.
 Una volta ricevuta tua conferma provvedo a inserire anche un secondo check lato backend ed a svolgere il commit.

2) In ultimo ti chiedo anche conferma del seguente fatto: l' "accettazione" e' solo un passaggio formale che serve a procedere con la registrazione, ma di fatto NON SALVO alcun cookie e tantomeno alcun dato nel database. Per questo iter mi sono limitato ad aggiungere la data in cui l'utente viene creato, che di fatto coincide con la data di registrazione.

**Comment by coder-molok** [comment]
1) Funziona bene, l'estetica va bene, solo dovresti correggere il tag *emph finale ( Generale e Disposizioni relative ...) separandolo in due: Generale, Disposizioni ... lasciando la 'e' in testo normale.

2) Confermo che non serve salvare alcun check (valore booleano), ma rimane necessario bloccare la registrazione se non c'è l'ACCETTO e salvare la data di creazione che vale come data di accettazione delle condizioni (come già fai).

**Comment by coder-molok** [comment]
Una domanda: il pdf va posto nei files statici di elgg in FoowdStorage/Public/Files/
ma viene visualizzato incluso in una pagina o viene fatto scaricare all'utente?

**Comment by SimoSca** [comment]
si, va incluso nel path che hai scritto e si, viene visualizzato nella pagina che si apre in una nuova tab se clicchi sulla parola "link".

**Comment by coder-molok** [comment]
ok, sto integrando il messaggio 'popup' di informativa sui cookies con l'accettazione tacita delle condizioni d'uso per i non iscritti, volevo mettere un link e copiando quello della cookie-policy trovo nel food-main.js questo:
  link: elgg.get_site_url() + 'cookie-policy'
ma apre una pagina apposta.
Hai vatto una pagina anche per le condizioni (questo intendevo)? o il link rimanda direttamente al file?
nel caso come genero il link corretto per il pdf?

**Comment by SimoSca** [comment]
Per il momento non avevo pensato di unificare la cookie policy con le condizioni di iscrizione, pertanto rimandano a due file/page distinte.
Se vuoi mettere tutto in un solo PDF basta solo modificare il link.

**Comment by coder-molok** [comment]
No! Voglio tenerli separati, per questo mi serve l'altro link.

Ho pensato che avendolo inserito nella pagina di iscrizione tu potessi darmi il link al volo.

**Comment by SimoSca** [comment]
Faccio un punto della situazione, perché riguardando lavori svolti mesi fa giustamente sorgono incertezze:

* in fondo alle pagine di backend compare il link "Privacy Policy", che rimanda ad un link esterno alla VPS, nello specifico [http://www.foowd.it/disclaimer.html](http://www.foowd.it/disclaimer.html): questa pagina non l'ho creata io, pertanto mi ero limitato ad aggiungerla ai link

* il popup come da te giustamente scritto rimanda invece al link `elgg.get_site_url() + 'cookie-policy'` : questa pagina l'avevo creata io estrapolando dei dati da un mio plugin personale, che raccoglie una selezione di cookie policy, un po come fa il servizio "iubenda".

* alle due sopra citate, va aggiunta la pagina che punta al pdf che citiamo nella registrazione.

Non essendo informato su come si debbando gestire "cookie policy" e "termini d'accettazione" posso solamente dire che la soluzione ideale (se legalmente accettabile) sarebbe di riunire tutto in un unico file pdf. Questo semplificherebbe tutto, e a quel punto tutti i link dovrebbero semplicemente puntare a quel file.

Il PDF dovrebbe dunque essere suddiviso in due paragrafi:

* cookie policy, che devono essere accettati da chiunque navighi all'interno del sito, registrato o non
* utenti registrati, che a sua volta sara' suddiviso in base al fatto che l'utente sia un offerente o un utente standard.

Spero di averti descritto un quadro comprensibile della situazione. 

Fammi sapere come vuoi che vengano gestiti questi aspetti.

**PS**: per generare il pdf quale programma usi? te lo chiedo perche' se non erro alcuni consentono l'esportazione sia in pdf che in html, cosa che sarebbe a mio parere molto comoda per l'integrazione al sito (ma e' soltanto una frivolezza).

**Comment by coder-molok** [comment]
Hai fatto bene a farmelo notare, la discrepanza tra le due cookie policy mi era sfuggita.

dovremo unificare in futuro, ma per il momento limitiamoci a far vedere le Condizioni d'uso che sono fondamentali, anche dal popup.

La URL del PDF quindi qual'è?
Hai già collegato il pdf definitivo al codice?

**Comment by SimoSca** [comment]
Le condizioni generali d'utilizzo, ovvero il PDF, è raggiungibile al link 

    <sito elgg>/foowd_utenti/legal

ed è già presente nel form di registrazione nuovo utente; inoltre risulta caricato sulla VPS di sviluppo nel path precedentemente indicato, mentre sulla vostra VPS stabile non ho svolto alcuna operazione. 

In generale lato codice non inserisco quasi mai il link direttamente, ma uso un semplice modulo in cui ho raccolto l'elenco di tutte le pagine del sito: [foowd.pages.amd.php](../blob/dev/mod_elgg/foowd_utility/js/rewrite/foowd.pages.amd.php).

A questo punto ti chiedo:
1. vuoi che il link al PDF venga inserito anche nel popup della cookie policy?
2. visto che attualmente abbiamo due differenti cookie policy (una raggiungibile tramite popup, e l'altra da fondo pagina di backend) continuiamo a mantenerle entrambe o ne usiamo solo una?

**Comment by coder-molok** [comment]
Mi piace che le pagine non siano nel codice (ma nel policy-popup mi pare ci sia quindi nel caso possiamo sistemare anche l'altro).
Per risponderti:
1. Ho già modificato il popup e committato questa modifica parziale (commit 8ab5bc7) così puoi integrarla.

2. Andrebbe unificata, ma chiedo a Federico di verificare le differenze e fare il punto, poi ti aggiorno.

**Comment by SimoSca** [comment]
Ok, per il momento mi limito a integrare il tuo commit attendendo successivi aggiornamenti.

**Comment by coder-molok** [comment]
Facciamo questa modifica: metti il "Privacy Policy" di fondo pagina (pagine elgg) che punta alla stessa pagina delle "cookie policy" del banner iniziale.

Poi committa anche la parte di registrazione che aggiorno produzione.

**Comment by SimoSca** [comment]
Cosi' dovrebbe andare, ma ti chiedo di controllare per sicurezza.

NB: avevo modificato il DB API, pertanto ora devi fare i soliti aggiornamenti via propel e composer update.

**Comment by coder-molok** [comment]
Esclusivamente dalla pagina http://5.196.228.146/elgg-1.10.4/foowd_utenti/legal non funzionano correttamente i link a fondo pagina.

Per il resto è ok.
