### ISSUE TITLE
Link a fondo pagina non funzionano (condizioni e privacy)

### ISSUE THREAD

**Issue by coder-molok** [coder-molok/foowd_alpha2#237]
Con riferimento alla modifica riportata in #236,
esclusivamente dalla pagina http://5.196.228.146/elgg-1.10.4/foowd_utenti/legal non funzionano correttamente i link a fondo pagina.

**Comment by SimoSca** [comment]
Risolto e committato:

nel modulo contenente la lista delle pagine ho inserito i path relativi alla root del sito, e i link li richiamano in modo relativo. Generalmente i CMS impostano in `.htaccess` la condizione `RewriteBase`, cosa che Elgg non svolge di default.

Dato che non voglio modificare le configurazioni del file `.htaccess` autogenerato da Elgg, man mano che scrivo il codice aggiungero' il path assoluto, ora che so di questo fatto.

PS: se pur piu semplice e immediato, non modifico il `.htaccess` per evitare di aggiungere passaggi facilmente dimenticabili qualora si dovesse reinstallare tutto da zero (anche se abbiamo il buon tutorial di sviluppo che ci guida passo per passo).
