### ISSUE TITLE
Link dal wall

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#24]
mettere i link nell wall per raggiungere

la priprio pagian utente elgg
la lista delle preferenze inserite

**Comment by Panciz** [comment]
va bene la login per il non loggato se si e' loggati pero ancora non porta al profile

profile/:username

**Comment by SimoSca** [comment]
Dovrebbe farlo.

**Comment by coder-molok** [comment]
nel senso che a te, Simone, funziona?
o hai verificato il codice?

2015-06-08 16:21 GMT+02:00 Simone S. <notifications@github.com>:

**Comment by Panciz** [comment]
Sul server funziona direi tutto a posto
