### ISSUE TITLE
API foowd errori e messsaggi 

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#28]
Non considerare errore una ricerca con lista vuota

Migliorare errore ricerca per publisher non esistente 

   {"Foreign":"local ExternalId e Publisher passato non combaciano"}}

non e' chiaro

**Comment by SimoSca** [comment]
Sostituito la frase con "L'id passato non e\' associato a nessun utente API".
Anche il bug e' stato corretto.

Se la frase va bene, si può chiudere.
