### ISSUE TITLE
Dettaglio offerte

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#29]
Pagina dettaglio offerete secondo indicazioni del documento del grafico foow_pages.pdf pg8

**Comment by predorock** [comment]
Fatto anche questo

**Comment by Panciz** [comment]
Quello che vedo nel server (vedi allegato) non mi sembra completo.

Manca sicuramente l'immagine e il caricamento dei dati corretto.

E' un problema dell'upload sul server?


![screen_foowd-0](https://cloud.githubusercontent.com/assets/2254988/8171883/cf85ddee-13bb-11e5-856e-c20278db07d3.png)

**Comment by predorock** [comment]
Direi che questa la possiamo chiudere
