### ISSUE TITLE
Protezione  chiamate API 

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#30]
protezione per evitare che le chiamate alle API avvengano da dominio differente di quello su cui sono state caricate.

In particolare prestare attenzione alle chiamate Ajax

**Comment by predorock** [comment]
Altra cosa riguardo alla sicurezza delle API. Se voglio ottenere la lista delle preferenze dell'utente perché devo specificare l'id dell'utente? Da quello che ho capito la lista dei prodotti sui quali ho espresso una preferenza la ottengo solo se sono loggato. Quindi perché specificare in chiaro nella richiesta il mio id utente? (potrei essere loggato e richiedere le preferenze di qualcun'altro). Secondo me va modificata l'API in modo tale che il parametro `ExternalId` sparisca e che il server capisca a che id utente fa riferimento il client che fa la richiesta.

**Comment by Panciz** [comment]
Il problema e' verificare che l'external id fornito sia effettivamente quello dell'utente che ha eseguito l'operazione.

Siccome non "vediamo" la sessione Elgg dalle API non possiamo effettuare questo controllo direttamente.

Dovrebbe essere abbastanza evitare che qualunque persona possa chiamare direttamente le API se non da gli script caricati dalla nostra pagina. In cui l'id dell'utente loggato viene forgiato all'interno.

Cerchero di indagare che questa soluzione sia abbastanza.

**Comment by SimoSca** [comment]
@Panciz e @coder-molok  , senza fretta, ma credo sia il caso di considerare il lato sicurezza (per elgg sottindendo che egli stesso sia sicuro, pertanto lato utenti elgg e sue autenticazioni dovremmo stare tranquilli (altrimenti cosa e' stato scelto a fare ?! ;-p ).

***

Per quanto concerne la sicurezza lato API credo che una soluzione buona e rapida sia anzitutto quella di svolgere un controllo sull'origine delle chiamate. Ad esempio ho appena provato a inserire nel file .htaccess di "slim framework" il comando

````
Require local
````

che consente l'accesso solo all'host locale (ho usato quello locale perche' allo stato attuale `elgg` e `API DB` lavorano sullo stesso server). Provando dal mio PC a svolgere una chiamata sulla VPS di sviluppo tramite `postman` effettivamente mi ritorna un `403 forbidden`.

Oltre all'`.htaccess` sottolineo che tali configurazioni possono essere inserite ad esempio nella directory `sites-enabled` presente dentro ad `apache2`:

essendo una directory al di fuori del path di `foowd_alpha2` potrebbe risultare comodo per avere delle configurazioni personali (ricordando che ogni server potrebbe voler implementare un proprio set di configurazioni).

Per chi gestisce una VPS e volesse rendere sicuro l'accesso al file system consiglio questo semplice tutorial: 

[http://www.petefreitag.com/item/505.cfm](http://www.petefreitag.com/item/505.cfm)


***

Sempre per quanto concerne le chiamate API, avrei anche trovato ed impelentato gia' da qualche tempo un metodo grezzo contro i [replay attack](https://en.wikipedia.org/wiki/Replay_attack) (o `back attack`) basato su una chiave e un delay temporale. Il file  e' [HttpBasicAuth.php](https://github.com/coder-molok/foowd_alpha2/blob/master/api_foowd/app/routes/actions/HttpBasicAuth.php) .

**Comment by SimoSca** [comment]
Scusatemi, la configurazione dell' `htaccess` con l'opzione

````
Require local
````

non sempre funziona... chiedo venia e do una spiegazione:

Quando ho detto che funzionava era perche' ho provato su delle pagine di test in php che svolgono la chiamata tramite `curl`: visto che il php gira in locale, anche il curl che esso richiama gira in locale.

Invece le pagine di `frontend` svolgono delle chiamate ajax al servizio API, pertanto risultano partire dal browser dell'utente, ovvero dall' IP del client, e non da quello dell'host.

Ho gia' in mente la soluzione per questo problema, ma preferisco non esporla qui in pubblico.
Quando vorrete/potrete affrontare la faccenda possiamo sentirci in privato o magari su asana, visto che e' da un pezzo che non lo usiamo.

**Comment by Panciz** [comment]
I lproblema non è tanto che si possano chiamare le API dall'esterno, ma che si possa farlo dichiarando di essere un altro utente, forgiando l'id.

Secondo me tutte le chiamate che prevedono specificamente il parametro utente corrente, dovrebbero passare per attraverso un pagina Elgg che inserisce làutente corrente loggato.
Bisognerebbe quindi separare le API che richiedono questa operazione e vincolarle al localonly. potrebbe essere un lavoro non facile propongo di rimandare questo lavoro fondamentale ma non essenziale per la presentazione del prodotto.

Non capisco invece come i CORS riguardano questo problema. In generale non non dobbiamo mai dare la possibilità di accesso ad Ajax cross site in quanto tutti gli Ajax che possono accedere per ora sarebbero quelli delle nnostre pagine.

**Comment by SimoSca** [comment]
Esattamente!
avevo iniziato una reply su asana e si, reindirizzare le chiamate a una pagina elgg che si prendera' in carico di svolgere le chiamate all ' API e' a mio parere la scelta migliore, in quanto:

- nell' htaccess delle API a quel punto ha sensissimo impostare un `Require local` o simili

- sfruttando una pagina elgg possiamo garantire che le chiamate `post` siano fatte da utenti effettivamente loggati e in ogni caso un domani sarebbero facilmente utilizzabili dei filtri lato php per controllare alcuni parametri, cosa gia' valida quantomeno per le action create finora (che svolgono una validazione dei dati prima di inviarli).

Se dovessi proprio fare il pignolo, a quel punto il problema sarebbe il fatto che ogni volta viene fatta una richiesta a elgg, questi ogni volta carica tutti i plugin e i suoi eventuali hook, ma questo in realta' e' un fatto di tutti i `CMS` .

**Comment by SimoSca** [comment]
Chiudo in quanto spostata su un desk più adeguato alla sensibilità dell'argomento trattato.
