### ISSUE TITLE
Pagina modifica Offerte

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#31]
- precaricare i dati attuali dell'offerta.

- in caso di errore di validazione non viene piu visualizzato l'errore

- togliere i print di Debug

**Comment by SimoSca** [comment]
> precaricare i dati attuali dell'offerta.
fatto.

> in caso di errore di validazione non viene piu visualizzato l'errore
vuoi che non vengano più visualizzati gli errori come *"massimo 8 cifre + 2 decimali..."*, oppure il popup *"Non riesco a caricare l'offerta"* o entrambi?

> togliere i print di Debug
era riferito ai messaggi come *"Non riesco a caricare l'offerta"* ?
