### ISSUE TITLE
Ricerca offerte risultato esteso a preferenze

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#34]
frevedere una api avanzata di ricerche che

1. prenda come argomento un external UserId 
2. ritorni oltre che le offerte matchate anche la preferenza offerta da quell'userid

Questa query complessa permette di visualizzare subito dalla ricerca se e' stata fatta gia una preferenza per quell'offerta.

**Comment by Panciz** [comment]
Ok tutto bene, vedo anche che la preferenza viene sommata se gia esistente.

L'unica cosa che l'oggetto che ritorna mi sembra sbagliato:

{
"body": {
"response": true,
"body": [
.....
]
},
"response": true
}


perche' due body con due response innestati?


Inoltre ho docuto cambiare lina 431 di API da 

      				$match = \Foowd\Fapi\ApiPrefer::search($ext);
a

               				$match = \ApiPrefer::search($ext);

altrimenti mi dava errore.

Davide

**Comment by SimoSca** [comment]
Non avevo fatto il commit dei miei ultimi cambiamenti, sorry.
Ora dovrebbe andare tutto.

Per quanto riguarda il richiamo a 

` $match = \Foowd\Fapi\ApiPrefer::search($ext);`

se  uso `$match = \ApiPrefer::search($ext);`, con lo slash davanti non mi funziona, senza invece va bene, ed ha senso.
In ogni caso avrebbe dovuto funzionare anche nella versione originale col namespace che parte da `\Foowd`: e' strano che non ti funzioni...
Magari potresti provare a lanciare un `composer dump-autoload` dalla directory `api_foowd/app` , anche se in teoria non era necessario.
