### ISSUE TITLE
Filltro per nome

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#36]
Aggiungere filtro per nome nella pagina. la ricerca viene fatta inserendo il valore nella barra di fianco scritta "foowd_" . Vedi pagina 6/7  https://github.com/coder-molok/foowd_alpha2/blob/master/doc/Grafics/foow_pages.pdf

**Comment by predorock** [comment]
Tramite API come si fa a ricercare per nome? Ho guardato la documentazione per un ora e giuro non ho capito come fare.

**Comment by Panciz** [comment]
Ok la ricerca ora e' implementata, dovrebbero essere aggionata la documentazione ora.
