### ISSUE TITLE
Ricerca per nome offerta

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#37]
la funzione di ricerca dovrebbe prendere anche come argomento un valore nome per effetture la ricerca delle offerte per nome.

**Comment by SimoSca** [comment]
intendi una ricerca per parole chiave contenute nel titolo?

**Comment by Panciz** [comment]
si

**Comment by Panciz** [comment]
In realta basterebbe anche farla semplice tipo porzione di stringa


Ad Esempio se nome

"formaggi d'alpeggio"

lo trovo sia con

"formaggi"
"alpeggio"
"alpe"


magari imposta che la string sia almeno 3 caratteri.


senno se uno mette a trova tutto!!



2015-05-12 10:32 GMT+02:00 Davide Poletti <dav.poletti@gmail.com>:

**Comment by SimoSca** [comment]
pienamente d'accordo!

L'ho appena completata.
