### ISSUE TITLE
Ricerca per tag tutti i valori se lista vuota

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#38]
Se si passa la lista dei tag vuota si ottiene che tutte le offerte matchano con la ricerca.

**Comment by SimoSca** [comment]
Per rendere più solide le API ho fatto in modo che qualora i parametri passati risultino nulli (o di lunghezza nulla) il servizio ritorni un errore: questo include anche l'impossibilità di usare una lista di "Tag" vuota nella funzione search.
