### ISSUE TITLE
Quantita totale preferenze

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#39]
i record ritornati dalla funzione cerca offerte dovrebbe anche contenere il numero totale di preferenze inserite per quell'offerta.

Sia la funzione cerca che cerca con preferenze per utente dovrebbe ritornare questo valore.

In questo modo diventa facile visualizzare quanto manca rispetto alla qt minina.

**Comment by SimoSca** [comment]
Risolta aggiungendo alla singola offerta la chiave "totalQuantity" qualora vi siano preferenze associate ad essa.
