### ISSUE TITLE
Miglioramento API Rest  ricerca

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#40]
A questo punto credo che sia conveniente semplificare il metodo di ricerca.

Terrei un solo metodo che prende come prametro opzionale ExternalID, se l'external id non e' presente non vengono inclusi anche le preferenze, se e' presente si pocede come se fosse un type="searchPrefer"

Un altro cosa, direi che per chi sviluppa l'interfaccia e' molto comodo avere oggetti uniformi come risultato.

Quindi se per esempio non ci sono prefereze la totalQt dovrebbe cmq essere presente a 0.

Lo stesso anche per quanto rigarda i tag, le preferenze di un utente (oggetto a null se per quell'offerta l'utente non ha messo preferenze) ed eventualmente altro.

In questo modo chi usa la api non deve fare meno controlli.

**Comment by SimoSca** [comment]
Risolto.
Vedere https://github.com/coder-molok/foowd_alpha2/blob/master/doc/simone.md#18052015
