### ISSUE TITLE
memorizzazione delle immagini

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#41]
Da decidere come gestire le immagini se memorizzarle su un servizio esterno vedi 

http://insights.dice.com/2014/02/10/cloudinary-vs-blitline-cloud-image-services-compared/

oppure memorizzarle all'interno del db.

**Comment by coder-molok** [comment]
Troppo complicato upload in cartella dedicata sul server?

**Comment by SimoSca** [comment]
Probabilmente il metodo migliore è la memorizzazione all'interno del DB.
Porrei un limite alle dimensioni in MB dell'immagine, e implementerei la creazione di una thumbnail per un'eventuale preview.

**Comment by coder-molok** [comment]
Occorre verificare le librerie php, per la gestione delle immagini,
disponibili sul php del server, perchè non modificabili (host, non server).
Il 20/mag/2015 19:42, "Simone S." <notifications@github.com> ha scritto:

**Comment by Panciz** [comment]
Proponevo l'idea di esternalizzare per evitare di dover sobbarcarci questa
implementazioni.
Possiamo iniziare cosi intento.

Davide

2015-05-21 7:08 GMT+02:00 Marco Colombo <notifications@github.com>:

**Comment by SimoSca** [comment]
Chiudo perche' risolta da tempo con l'introduzione di una apposita directory lato server elgg.
