### ISSUE TITLE
Togliere pulsante Submit ed eseguire search sulla pressione enter nell'input

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#42]
Togliere pulsante Submit ed eseguire search sulla pressione enter nell'input.

In pratica come se fosse linea di comando .

Dovresti aggiungere una cosa del genere 

("#id_of_textbox").keyup(function(event){
    if(event.keyCode == 13){
        foowd.search()
    }
});

vedi 

http://stackoverflow.com/questions/155188/trigger-a-button-click-with-javascript-on-the-enter-key-in-a-text-box

**Comment by Panciz** [comment]
Il pulsante e' stato rimosso  pero la ricerca non viene lanciata affatto!??

**Comment by predorock** [comment]
Fatto
