### ISSUE TITLE
Descizione visualizzare considerandola come html non come testo normale.

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#44]
La descrizione dell'offerta viene salvata html. questo correttamente in quanto permette di mettere anche del testo formattato.

quando viene visualizzata dovrebbe essere inclusa nella pagina tenendo conto di questo.

Ad esempio usando [JQuery.append()](http://api.jquery.com/append/)

**Comment by SimoSca** [comment]
Svolta: dovevano solo essere cambiati i template di Handlebars sostituendo {{...}} con {{{...}}} in modo da fargli svolgere il parser html.
