### ISSUE TITLE
Gestione errore ricerca offerte e preferenze

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#45]
Mostrare popup o comunque evidenziare errore nel caso la API non risponda con un true al request di ricerca e di aggiunta preferenze.

**Comment by predorock** [comment]
Ho impostato un pop up che appare quando avviene l'aggiunta di una preferenza. In caso positivo dice, "la preferenza è stata aggiunta correttamente" altrimenti "c'è stato un errore durante l'aggiunta della tua preferenza"
