### ISSUE TITLE
Problema plugin utility su server

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#46]
Il plugin utenti su server sembra non funzionare nel senso che  non riesco a cambiare il valore dell'url base che al momento dfunziona solo perche' abbbiamo riconfigurato allo stesso modo del locale il server.

Inoltre ci sono un sacco di warning deprecated vedi allegato
![screen_foowd-1](https://cloud.githubusercontent.com/assets/2254988/7692006/a2604b86-fdbf-11e4-8bc2-8a56a2f3e288.png)

**Comment by Panciz** [comment]
Ho gia provato a attivare e disattivare il plugin. Sul server abbiamo elgg versione 1.10

**Comment by SimoSca** [comment]
Quei Warnings dovrebbero essere dovuti a un problema nel richiamare la variabile 'api' del plugin. Le funzioni citate nei warning hanno tutte la forma

````
<function>($name, $plugin_id = null, $default = null
````

e se il secondo parametro risulta null (nel nostro caso è la variabile 'api') allora elgg restituisce i "warning deprecated" di cui sopra.

**Comment by SimoSca** [comment]
Risolti tutti i bug relativi a creazione, modifica ed eliminazione offerta.

Era tutto dovuto al metodo `\Uoowd\Param::pid()`, che conteneva una regular expression che metchava www.foowd.eu (naturalmente col localhost non dava problemi).

Altri errori erano dovuti ad alcuni files che non erano ancora stati aggiornati sul server.
