### ISSUE TITLE
Problema aggiunta offerta da interfaccia .

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#47]
In locale non vedo lo spinner.

Sul server vedo lo spinner ma non riesco a postare la creazione.

Ti allego il print della scherIn locale non vedo lo spinner.

Sul server vedo lo spinner ma non riesco a postare la creazione.

Ti allego il print della schermata di errore sul server.

![screen_foowd2-0](https://cloud.githubusercontent.com/assets/2254988/7692243/2820bba0-fdc2-11e4-9958-e06e574daaf7.png)

**Comment by SimoSca** [comment]
Probabilmente l'errore è dovuto alla cache di Elgg. Prova a ad andare su 

`<sito elgg>/upgrade`

In teoria dopo questa procedura dovrebbe aver caricato la view.

Mea Culpa: non l'avevo scritto nel commit, ma lo aggiungo affinche' rimanga per i prossimi.

**Comment by SimoSca** [comment]
Risolta con https://github.com/coder-molok/foowd_alpha2/issues/47
