### ISSUE TITLE
Creazione automatica utente non funzionante su versione online

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#50]
Creazione automatica utente su db modulo offerte non funzionante su versione online.

Probabilemnte legata a bug sul dominio https://github.com/coder-molok/foowd_alpha2/issues/48

**Comment by coder-molok** [comment]
che è diventato #49

Il giorno 20 maggio 2015 00:00, Davide Poletti <notifications@github.com>
ha scritto:
