### ISSUE TITLE
Navigazione Sito

### ISSUE THREAD

**Issue by predorock** [coder-molok/foowd_alpha2#51]
Ho trovato alcune difficoltà a mettere i link per la navigazione del sito. Dato che la navigazione è gestita lato server da elgg, non ho capito bene a livello di client come collegare le pagine. Ovvero ad ottenere URL radice del sito, in modo da creare dei link dinamici.

**Comment by Panciz** [comment]
Ok per ora lascia stare quell'aspetto, continua con la pagina di dettaglio
e a completare gl ialtri aspetti della pagina Wall.



2015-05-20 11:14 GMT+02:00 Marco <notifications@github.com>:

**Comment by SimoSca** [comment]
Puoi fare un esempio specifico?

**Comment by Panciz** [comment]
Un primo problema mi sembrava fosse mettere un link all'icona omino in altro a dx sul wall.
Per ora c'e' solo se l'utente e' sloggato e porta alla login. Vorrei che quando l'utente e' loggato porti alla pagina profilo.

**Comment by SimoSca** [comment]
Ho fatto alcune prove, ed attualmente il fatto sta nel template: bisogna richiamare alcuni script per generare uno HEAD opportuno.
Questo permette ad esempio di introdurre in javascript una variabile globale "elgg" mediante la quale è possibile recuperare il guid dello user ed altre informazioni, senza bisogno di generarle tramite PHP.

come inoltre scritto in [http://learn.elgg.org/en/latest/guides/javascript.html](http://learn.elgg.org/en/latest/guides/javascript.html) , sarebbe più opportuno pensare di utilizzare javascript in AMD, cosa che ad esempio ho fatto per il mio script di crop.

Con questa premessa generare quanto chiesto da @Panciz è molto semplice, ma a questo punto prima di procedere inizio a passare l'idea. Ho fatto alcuni test sul mio pc e la cosa non è totalmente banale, specialmente perchè non conosco handlerbars e non so per cosa abbia utilizzato bootstrap. 
In ogni caso prima di mettere mano a questa parte, vorrei sapere se ho il benestare.

**Comment by predorock** [comment]
Si ho letto anche io riguardo alla parte JS di elgg. Il problema sta che puoi utilizzare gli AMD soltanto se utilizzi il sistema di view di elgg, cosa che io non ho utilizzato perché mi rendeva la personalizzazione estetica abbastanza complicata

**Comment by SimoSca** [comment]
Su quello ti do pienamente ragione: il sistema di view di elgg è molto vincolante.
In ogni caso  gli AMD si possono caricare a, ad esempio nella funzione init di start.php.
Stavo provando sul template e così sono riuscito a caricare una libreria di test.

Visto che non ho usato bootstrap e handlebars non so se il passaggio ad AMD risulti piuttosto liscio (per handlebars sicuramente, dato che è anche dotato dei files .amd.js ).

**Comment by predorock** [comment]
Ho provato a fare anche quello e i file js venivano caricati correttamente. Ma se non fai `elgg_print_view()` (ovvero usi il sistema di view di elgg) non li hai a disposizione nella tua pagina.

**Comment by SimoSca** [comment]
Stanotte ho implementato una versione AMD.
Per non cambiare il lavoro fatto da @predorock ho creato dei files nuovi, che contengono la stringa *AMD*.
L'unico file che ho modificato è lo `start.php` di `foowd_theme`.
