### ISSUE TITLE
Ultime Modifiche Pagina Inserimento e Modifica, lista TAG

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#52]
Inserimento TAG prelevandoli da lista.

Come si era detto i tag all'inizio non verrano inseriti dagli utenti ma ne metteremo un po noi di default.
L'ideale sarebbe che nella creazione delle offete i tag venissero scelti da una lista.

**Comment by SimoSca** [comment]
Ho appena committato questa implementazione: l'elenco può essere inserito tramite il pannello settings di Utility Foowd.
