### ISSUE TITLE
Inserimento Offerta aggiunta immagine

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#54]
Sarebbe perfetto inserire un immagine in accompagnamento all'offerta da visualizzare nel wall.

I problemi sono 2:

1 La memorizzazione : dove si effettua ? nel file o direttamente nel db. Inoltre come gestire la grandezadel file. 

2 La foto deve avere delle dimensioni standard come procedere. Fare il resize della foto perdendo magari il rapporto e mostrandola magari distorta. Proporre al momento dell'upload un modo per tagliarla?

Io avevo proposto a tal proposito di risolvere questi problematiche affidandoci ad un servizio esterno. Vedi https://github.com/coder-molok/foowd_alpha2/issues/41
Questo pero ci vincola quindi proviamo a fare un esperimento e vedere quanto fare tutto da soli.

Per manipolare le foto proporrei queste due opzioni

http://wideimage.sourceforge.net/2011/02/wideimage-11-02-19-released/

o 

http://stefangabos.ro/php-libraries/zebra-image/#documentation

entrambe fanno quello che serve a ni principalmente il crop dell'immagine.
Le ho preferite   imagick perche' mi sembrano piu facile da installare e usare.
L'unico requirements e' che sia abilitato il modulo GD che sul server c'e'.

Entrambe prevedono che il file sia caricaricato locamente direi che il flusso dovrebbe essere:

1. Caricamento Immagni su disco in cartella temporanea.
2. Rezise immagine
3 Memorizzazione in DB immagine resize

per mostrarla

1. Caricare immageni da DB
2. mostrarla embeddata direttamente nell'html vedi http://stackoverflow.com/questions/1207190/embedding-base64-images

un tutorial per fare questo in php senza la fase di resize

http://stackoverflow.com/questions/26757659/how-to-store-images-in-mysql-database-using-php

**Comment by SimoSca** [comment]
Questa l'ho risolta settimana scorsa, implementando l'upload, crop delle immagini e la loro memorizzazione.

Rimane appunto da decidere come svolgere il salvataggio delle immagini, nel senso che per ora tutto avviene salvando nella cartella `OfferImg` sorella di quella dell'installazione Elgg, nello specifico vengono salvati il file originale, e due immagini ritagliate: 100X100 e 300X300. 

Volendo si potrebbe salvare tutto nel DB, ma ho pensato che per una piu' rapida fruibilita' delle immagini, probabilmente sia meglio tenerle sullo stesso server dell'installazione Elgg (cartella OfferImg appunto).
Al limite si potrebbe pensare di salvare solo l'immagine originale ne DB, in modo che rimanga come copia di backup.

**Comment by Panciz** [comment]
Discussione rimane aperta su bug memorizzazione immagini

memorizzazione delle immagini #41
