### ISSUE TITLE
Link aggiunta offerte da profile

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#55]
Aggiungere Link a pagina gestioen offere nella pagina profilo utente se utente e' offerente

**Comment by SimoSca** [comment]
Appena svolta.

Come sempre guardare su [simone.md](/coder-molok/foowd_alpha2/blob/master/doc/simone.md#03062015), ed in particolare ricordarsi di fare il refresh delle views

**Comment by SimoSca** [comment]
Riaperta perchè non funziona?

da `<sito_elgg>/profile/username` si dovrebbero visualizzare i pulsanti "crea nuova" e "Mie Offerte", se si e'  **offerente**.

Spiegami l'eventuale bug, please.
