### ISSUE TITLE
Ricaricari Pagina dopo aggiunta preferenza

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#56]
Ricaricari Ricerca dopo aggionta preferenza in modo da vedere aggiornato il valore totale aggiunto e il cuore rosso dopo aver premuto.

**Comment by Panciz** [comment]
Mi sbagliavo la problematica non e' ancora stata risota, il pulsante si colora di rosso ma:

1 Non si aggiorna le preferenze espresse totali
2 Se si ricarica kla pagina si aggiornao le preferenze totali ma il pulsante ritorna bianco. Mi piacerebbe visualizzare se sono loggato per quali offerte ho messo le rpeferenze

**Comment by predorock** [comment]
Ora il cuore si colora, e lo vedi colorato anche se ri-aggiorni la pagina. Manca da aggiornare il numero di preferenze espresse, l'idea e di cercare un sistema di data-binding

**Comment by Panciz** [comment]
Beh non ti incastrare ad inserire un nuovo livello di librerie o altro, al
massimo fallo in maniera "artigianale" .

L'iterazione dovrebbe essere solo quella con il wall non è fondamentale
avere un sistema di binding completo.





2015-06-11 18:04 GMT+02:00 Marco <notifications@github.com>:

**Comment by predorock** [comment]
Ho fatto in modo che il wall si ricarica non appena viene espressa una preferenza.
