### ISSUE TITLE
timestamp nella creazione delle offerte

### ISSUE THREAD

**Issue by predorock** [coder-molok/foowd_alpha2#57]
Ho notato che nella richiesta di creazione di una offerta bisogna specificare il timestamp. Ecco questa cosa andrebbe tolta in quanto per principio crea dei problemi di inconsistenza. Gli orologi dei client, non sono sincronizzati tra di loro, di conseguenza nel database si possono scrivere degli orari del tutto casuali. L'assegnazione del timestamp dovrebbe essere fatta lato server.

**Comment by Panciz** [comment]
Si ha ragione Marco. Il created mettilo o da PHP o addirittura direttamente nel DB mettendo il valore DEFAULT (vedi)[http://stackoverflow.com/questions/168736/how-do-you-set-a-default-value-for-a-mysql-datetime-column] . In questo modo eviti possibili problemi con diversi fusi orari dei client.

**Comment by SimoSca** [comment]
Avevo già preso in considerazione questo fatto aggiungendo in ApiOffer.php 

````
if(!isset($data->Modified)) $data->Modified = date('Y-m-d H:i:s');
````

come suggerito da @Panciz ho impostato l'immissione direttamente  da MYSQL.

> NB: per rendere funzionante il tutto, guardate il mio solito changelog [simone.md](https://github.com/coder-molok/foowd_alpha2/blob/master/doc/simone.md)

**Comment by SimoSca** [comment]
@Panciz 

per quanto riguarda le date, mi stavo chiedendo se non fosse il caso di aggiungere il campo "scadenza" nella tabella delle offerte e "data-iscrizione" per i nuovi utenti (nel caso più avanti si voglia decidere di lanciare iniziative rivolta agli utenti anziani, o viceversa ai nuovi arrivati)
