### ISSUE TITLE
messaggio specifico se ricerca non hga ritornato nulla

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#58]
L'utente dovrebbe cmq avere un feedback in caso di messaggio manante.

**Comment by SimoSca** [comment]
Quale sarebbe il messaggio mancante?

**Comment by Panciz** [comment]
Il concetto è far capire bene all'utente che non c'è nessuna offerta che
match con quello ricercato.

Direi fare apparire una scritta con nessun offerta trovata.

**Comment by SimoSca** [comment]
Essendo parte del Wall, mi sono sentito con @predorock e abbiamo pensato che sia meglio la faccia lui, pertanto ti chiedo di assegnargliela, thanks.

**Comment by Panciz** [comment]
ok perfetto, oggi quando ti ho scritto non potevo accedere a github ma solo alla mail, e quindi non riuscivo a riassegnare direttametne io.

**Comment by predorock** [comment]
Ok ho impostato un messaggio in modo tale che se la ricerca non produce risultati non viene aggiornato il wall, e viene mostrato un messaggio di errore in alto a dx che dice "La ricerca non ha prodotto risultati"
