### ISSUE TITLE
Pick dei tag in creazione modifica offerta

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#60]
Pick dei tag in creazione modifica offerta.

In caso di molti tag la check box diventerebbe un po scomoda sarebbe meglio una multiselezione o qualcosa di questo tipo.queste

http://harvesthq.github.io/chosen/#multiple-select

mi piaciono molto

**Comment by SimoSca** [comment]
yes, sono daccordissimo!

Infatti avevo pensato, una volta ottenuta l'approvazione del lavoro svolto, di proporti questa:
[http://www.jqueryrain.com/?CAzyZKvP](http://www.jqueryrain.com/?CAzyZKvP)

Diciamo che mi ero focalizzato sulla creazione di "gruppi" di tags, dato che si spaziera' un'ampia gamma di prodotti.

**Comment by coder-molok** [comment]
Ok.

Non è prioritario.

M

Il giorno 6 giugno 2015 00:35, Simone S. <notifications@github.com> ha
scritto:

**Comment by SimoSca** [comment]
Appena risolto.
