### ISSUE TITLE
Problematiche wall

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#61]
Warning deprecated in basso vedi print
![screen_foowd-0](https://cloud.githubusercontent.com/assets/2254988/8044402/9fad15c2-0e2c-11e5-88e5-d115e1261bef.png)

**Comment by predorock** [comment]
Questa funzione non viene usata da nessuna parte nel progetto. Ho fatto una ricerca tramite sublime e non mi ha dato nessun match.

**Comment by SimoSca** [comment]
Guardando il [link](https://community.elgg.org/discussion/view/1846396/what-is-the-correct-way-to-customize-the-index-page-in-elgg-19)

ho visto appunto che il caso speciale della index e' stato rimosso.

Basta, nello start.php del theme, sostituire

````
elgg_register_plugin_hook_handler('index', 'system', 'foowd_wall_page_handler');
````
con
````
elgg_register_page_handler('','foowd_wall_page_handler');
````

**Comment by predorock** [comment]
Da ancora questo errore?

**Comment by SimoSca** [comment]
@predorock 

l'errore lo da ancora: ho appena aggiornato il mio repo locale, ed ho notato che nello start.php di foowd_theme è ancora presente il plugin_hook_handler.

Basta fare quella sostituzione che ho scritto nel mio post precedente: l'ho testa in locale e funziona. Tale modifica non l'ho poi committata perchè essendo parte del plugin che stai gestendo te, preferisco non toccare codice ove possibile.

**Comment by SimoSca** [comment]
Risolta con mio commit del 22/06/2015

**Comment by Panciz** [comment]
ok aspetto che marco faccia l'upload prima di chiudere il bug. e di non vedere le immagini piccoline, vedi allegato. (avevamo risolto il problema giusto??)

![screen_foowd_1-0](https://cloud.githubusercontent.com/assets/2254988/8317462/05560c6c-19fe-11e5-8708-6855cfad8630.png)

**Comment by coder-molok** [comment]
Aggiornato, cache "flush-ata", Elgg "upgrade-ato"... potete verificare.

M

Il giorno 23 giugno 2015 23:17, Davide Poletti <notifications@github.com>
ha scritto:

**Comment by SimoSca** [comment]
yes, la dimensione delle immagini era stata sistemata da Marco la sera stessa dell'ultimo incontro, mi sembra rimuovendo un'opportuna classe css.
