### ISSUE TITLE
Errore su ordinamento  Wall

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#62]
Funzionalita' non sembra piu funzionare

**Comment by predorock** [comment]
Fixed

**Comment by Panciz** [comment]
io lo vedo ancora sul server, e' solo un problema di agigornamento?

**Comment by coder-molok** [comment]
Yess. Spero. Ora aggiorno, domattina controllate.
Il 12/giu/2015 21:47, "Davide Poletti" <notifications@github.com> ha
scritto:

**Comment by predorock** [comment]
In locale funziona

**Comment by coder-molok** [comment]
In locale, Marco, potresti anche già avere tutta la piattaforma definitiva
e funzionante, ma come sai (e se non lo sai te lo dico ora), al cliente non
interessa quello che hai nel retrobottega, ma ciò che si porta a casa.

Verificate se è a posto dopo l'aggiornamento, per cortesia.
Il 14/giu/2015 17:20, "Marco" <notifications@github.com> ha scritto:
