### ISSUE TITLE
Creazinre offerta modifiche minori

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#63]
Upload immagini impossibile inviare file che hanno estenzione JPG.
Il controllo sull'estensione (se c'e' ) da fare case insensitive.
tipo con regex [j][J][p][P][g][G]

Controllare Maggiore sia > di Minore

Non vedo piu i controlli per formattare il testo descrizione.

**Comment by SimoSca** [comment]
Appena risolto la regex (non avevo inserito lo "/i" per l'opzione case insensitive.

> Controllare Maggiore sia > di Minore
 Potresti spiegarmi meglio?

Provvederò per i controlli d formattazione: a volte ci sono a volte no...

**Comment by SimoSca** [comment]
Risolto tutto col commit del 10/06/1025.

**Comment by Panciz** [comment]
Controllare Maggiore sia > di Minore
Potresti spiegarmi meglio?

Intendo controllare che il valore minimo da raggiungere sia inferriore a
quello massimo.

Davide

**Comment by SimoSca** [comment]
Risolta con gli ultimi aggiornamenti.
Lascio a te il piacere ti chiuderla una volta verificato.
