### ISSUE TITLE
Helpers personalizzati di Handlebars

### ISSUE THREAD

**Issue by predorock** [coder-molok/foowd_alpha2#64]
Prima dell'utilizzo degli script AMD, facevo uso di `Handlebars.registerHelper('prefer',func ..)` per impostare il cuore rosso ad una offerta se dall'utente loggato fosse stata espressa una preferenza.
Ora con la nuova struttura basata su `requirejs` questa cosa non funziona più. Bisogna trovare il modo di caricare degli `Helpers` di Handlebars personalizzati, in modo da re-integrare questa funzionalità.

**Comment by SimoSca** [comment]
Prova, da uno script di require, a impostare Handlebars come variabile globale, tipo:

````
.......
     window.Handlebars = require('handlebars');
.......
````

stando pero' attento alle tempistiche tra caricamento ed esecuzione.

Se vuoi fino alle 18:00 sono disponibile per un hangouts.

**Comment by predorock** [comment]
In realtà io nel `WallController.js` faccio già: 

      define(function(require){

	...
	var Handlebars = require('handlebars');
	var templates = require('templates');
	....
	var WallController = (function(){

		...
	
		Handlebars.registerHelper('prefer', function(object) {
			var result = "";
			if(object.data.root.prefer !== null){
				result = "red-heart";
			}
			return new Handlebars.SafeString(result);
		});
                ...
       }();
       return WallController
      });


Però in questo modo non mi funziona, ovvero quando visualizzo la pagina HTML il placeholder nel template viene sostituito con [Object][Object].

C'è un modo per fare un `require.config()` in elgg ? Googleando ho visto che si può dare una configurazione di handlebars in modo da specificare il runtime di handlebars, i suoi template, e appunto eventuali helpers registrati.

**Comment by SimoSca** [comment]
A dire il vero non ho mai provato.
Comunque quello che suggerivo con 

````
window.Handlebars = ...
````

era proprio di assegnare la proprieta' Handlebars all'oggetto window, che in javascript e' sostanzialmente il root. Come fai te inve 

````
var Handlebars = ...
````
associ il risultato del require a una variabile con scope locale, che' quello che in genere si fa.
Comunque se potessi vedere l'errore sarebbe piu' facile.

Se vuoi che ci facciamo una videochiamata mandami una mail e collaboriamo come fatto ieri.

**Comment by predorock** [comment]
Risolto includendo `handlebars.runtime`
