### ISSUE TITLE
Lunghezza Descrizione

### ISSUE THREAD

**Issue by SimoSca** [coder-molok/foowd_alpha2#65]
Attualmente nel DB la descrizione ha una lunghezza di 255 caratteri.
Probabilmente sono pochini, specialmente qualora un produttore voglia raccontare qualcosa di particolare in merito al prodotto.

Credo che 1000 caratteri possano bastare. 

@Panciz che ne pensi?

**Comment by Panciz** [comment]
Si sicuramente.

**Comment by coder-molok** [comment]
ok, priorità BASSISSIMA
Il 12/giu/2015 21:26, "Davide Poletti" <notifications@github.com> ha
scritto:

**Comment by SimoSca** [comment]
I Tags come ho scritto in [https://github.com/coder-molok/foowd_alpha2/blob/master/doc/foowd_main.md](https://github.com/coder-molok/foowd_alpha2/blob/master/doc/foowd_main.md) si possono inserire mediante pannello d'amministrazione, pertanto lascio stabilire a voi cosa inserire: ho creato un metodo d'immissione user-friendly, ma se non si capisse qualcosa chiede pure.

**Comment by coder-molok** [comment]
Scusa, ma centra con la lunghezza della descrizione???
Il 13/giu/2015 15:45, "Simone S." <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
No, era solo in risposta alla considerazione che i tags sono un po pochini:

ho colto l'occasione per ricordare che i tags vanno configurati nei settings del plugin, tutto qui.

Questo in realtà non era un vero quesito, ma solo un consulto: di fatto basta cambiare un parametro nello schema.xml e fare un "propel migrate" in base a quello.
