### ISSUE TITLE
API Offerte Search Quota

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#66]
Si inserisce il concetto di Quota che e' la quantita' minima ordinabile dal singolo utente.

Da distinguere dalla quantita' minima presente adesso che si riferisce al "mionimo per raggiu ngere un ordine". 

Il search dovra tornare nel campo del Json  @totalQt@ il totale delle quote inserite come preferenze. 

Anche nelle preferenze per utente @prefer.Qt@ la quantita indicata e' quella del numero di quote richieste dall'utente, equivalente a quante volte hapremuto il like per intenderci.

A questo punto e' necessario inserire nel DB il campo @quota@, che indica appunt la quota minima di cui parlo.
Il campo prezzo si riferisce a questa quota minima.
La spesa dell'utente e'  per intenderci si calcola come: 

@prefer.Qt@ x @price@

Inserire nel DB anche il campo unita' di misura quota.
I valori che puo assumere questo campo sono definiti o in un altra tabella o in un file.
vedi issue https://github.com/coder-molok/foowd_alpha2/issues/79

**Comment by SimoSca** [comment]
Coerente con quanto avevo segnato ieri tornato a casa.

Specifico:
--------------

- @minqt@
      - e' il numero minimo di quote per le quali l'offerente sara' disposto a fare l'ordinazione: a questo punto nella tabella da `decimal` lo porterei a `integer`

- @maxqt@
     - stesso discorso di @minqt@, ma inteso come massimo di quote

- @preferQt@ 
    - essendo associato al numero di click, inteso come multiplo di quote, dovrebbe essere un `integer`: nella tabella `prefer` e' gia' presente un campo `qt`, pertanto non ho bisogno di crearne uno nuovo. Al piu potrei rinominare la colonna `qt` in `preferqt` in modo che quando viene ritornato come dato json sia meglio identificabile
