### ISSUE TITLE
API ricerca Offerte estrazione preferenze

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#67]
Al momento nella ricerca offerete e' possibile inserire un externa ID per ritornare le preferenze inserite per le offerete ricercate da un utente.

Per rendere le API piu flessibie in seguito permeteere di specificare un array di ExternalID come prametro in modo da poter ritornare un array di preferenze.

In questo modo deve essree possibile ad esempio ritornare le preferenze inserite da un gruppo di utenti per alcune offerte.

**Comment by SimoSca** [comment]
Fatto: ora nella ricerca delle offerta basta specificare un elenco di id separato da virgole, ad esempio:

`ExternalId=25,78"`

per ogni offerta ritorna anche le preferenze espresse dall'utente con id 25 e da quello con id 78.

Documantazione API e file di esempio POSTMAN aggiornati col commit odierno.
