### ISSUE TITLE
Metodo di libreria per trasformare collezione Propel in json

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#7]
Methodo query per trasformare propel collection in json array vedi 

Lo scopo e' quello di ottenere un metodo riutilizzabile facilmente per ritornare le collection propel restituite dal metodo find() in json array. l'esempio e' in https://github.com/coder-molok/foowd_alpha2/blob/master/api_offerte/app/controller/offerte.php#L10. 

vedi suggerimenti 
http://stackoverflow.com/questions/15888640/multi-row-tojson-function-using-propel-and-backbone

si potrebbe metterla in una classe util. comune.

**Comment by SimoSca** [comment]
Se lo scopo è quello di ritornare i dati in formato json, api_foowd fa proprio questo.
Propongo di chiudere questa issue se non vi è altro.
