### ISSUE TITLE
Pulizia Plugin Elgg

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#70]
Togliere dell' Elgg di produzione i plugin non necessari.

**Comment by coder-molok** [comment]
Cosa è stato tolto e cosa è stato lasciato?
Il 07/set/2015 16:33, "Simone S." <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
"Tolto" nulla: per il momento ho solo "Disattivato" alcuni plugins inutilizzati nell'attuale versione.
L'elenco lo puoi leggere su 
[https://github.com/coder-molok/foowd_alpha2/blob/dev/doc/simone.md#20072015](https://github.com/coder-molok/foowd_alpha2/blob/dev/doc/simone.md#20072015)

Oltre ai nostri plugin **foowd\_*** non e' stato inserito altro.
