### ISSUE TITLE
Theme Elgg

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#71]
Migliorare colori in mdo da allinearlo con pagine nostra custom.

**Comment by SimoSca** [comment]
La terrò come ultima:
anche se non ci vuole molto, in teoria la pensavo come una issue facente parte della gestione del thema, pertanto collegata in secondo piano al lavoro di @predorock .

**Comment by coder-molok** [comment]
In verità centrerebbe con la creazione della board personale, nel senso che
o la board di Predo prende il posto della attuale pagina personale,
o la attuale pagina personale viene personalizzata in modo da fungere da
board (in questo modo non si perdono i meccanismi social del profilo.

M

Il giorno 18 giugno 2015 19:49, Simone S. <notifications@github.com> ha
scritto:

**Comment by Panciz** [comment]
Mi sembrava di avertene accenato di persona e che fossi d'accordo, effettivamente concordo che fa parte del plugin che su cui sta lavorando @predorock. 
Te la lascio assegnata a te come dici comunque lasciala per ultima.

**Comment by SimoSca** [comment]
sviluppero' durante l'assestamento di ciascuna pagina
