### ISSUE TITLE
Server Pulizia Offerte senza immagine

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#72]
Rimuovere da ambiente test sul server le offerte senza immagini.

**Comment by SimoSca** [comment]
Fatto.
Colgo l'occasione per sollevare un quesito, che non ha alcuna priorità:
quando un'offerta viene eliminata vogliamo cancellare tutte le preferenze ad essa associata o le teniamo?
Personalmente le terrei lasciando a ciascun utente l'onere di cancellare le preferenze espresse su offerte eliminate. Naturalmente nella visualizzazione dell'elenco delle preferenze di un'utente verrebbero contrassegnate in modo da renderle distinguibili da quelle ancora aperte.

**Comment by Panciz** [comment]
io sarei per la cencellazione automatica, magari con avviso e notifica via mail.

Dobrebbe essere una situazione abbastanza inusuale per ora lasciamola sospesa.

Apro  nuova issue per ricordarci di decidere a riguardo.
