### ISSUE TITLE
Board Preferenze inserite

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#75]
Elenco di tutte le preferenze inserite con barra vedi issue https://github.com/coder-molok/foowd_alpha2/issues/74

Vedi https://github.com/coder-molok/foowd_alpha2/blob/master/doc/Grafics/foow_pages.pdf pg 19

**Comment by coder-molok** [comment]
Non dovrebbe essere ( o centrare almeno) con la pagina personale?

M

2015-06-17 19:25 GMT+02:00 Davide Poletti <notifications@github.com>:

**Comment by predorock** [comment]
Allora ho creato la pagina preferenze ma ho un piccolo problemino. Le API di simone fanno si che possa ottenere le preferenze di un certo utente, e va benissimo. Il problema che ciò che ritornano non sono i dati relativi alle offerte/preferenze ma l'associazione ```preferenza -> utente``` la quale è strutturata così:
```json 
{
    "response": true,
    "body": [
        {
            "Id": 1,
            "UserId": 37,
            "OfferId": 2,
            "Created": "2015-06-11 14:14:00",
            "Qt": 6
        },
        {
            "Id": 3,
            "UserId": 37,
            "OfferId": 3,
            "Created": "2015-06-13 14:21:07",
            "Qt": 36
        },
        {
            "Id": 4,
            "UserId": 37,
            "OfferId": 4,
            "Created": "2015-06-14 01:32:53",
            "Qt": 3
        },
        {
            "Id": 5,
            "UserId": 37,
            "OfferId": 8,
            "Created": "2015-06-14 01:39:38",
            "Qt": 4
        },
        {
            "Id": 6,
            "UserId": 37,
            "OfferId": 7,
            "Created": "2015-06-14 17:17:46",
            "Qt": 6
        },
        {
            "Id": 7,
            "UserId": 37,
            "OfferId": 5,
            "Created": "2015-06-14 18:43:09",
            "Qt": 5
        },
        {
            "Id": 8,
            "UserId": 37,
            "OfferId": 6,
            "Created": "2015-06-15 07:45:03",
            "Qt": 7
        },
        {
            "Id": 9,
            "UserId": 37,
            "OfferId": 9,
            "Created": "2015-06-15 07:45:29",
            "Qt": 8
        }
    ]
} 
```
Ora per ottenere i dati relativi all'offerta/preferenza dovrei fare n successive chiamate per ogni OfferId del body precedente (cosa che rallenterebbe di parecchio il caricamento della pagina). Si può fare in modo che vengono trasmessi anche i dati relativi del prodotto? basterebbe nestare all'interno di ciascun elemento un oggetto json con i dettagli del prodotto.
@SimoSca e chiaro? riesci a cambiarmelo?

**Comment by coder-molok** [comment]
Non vorrei si "gonfiasse" troppo la risposta.
Secondo i principi di Singola responsabilità e di Interfaccia specializzata
direi che non va bene aggiungere anche quei contenuti in questa richiesta.

Se fosse possibile ottenere i dati di tutte le offerte con una sola
chiamata (con una lista di ID) sarebbe un buon compromesso tra struttura
API e comodità di utilizzo?

M

Il giorno 30 giugno 2015 08:21, Marco <notifications@github.com> ha scritto:

**Comment by SimoSca** [comment]
Per i cambiamenti No problem, ma prima di procedere aspetto che vi accordiate.

**Comment by coder-molok** [comment]
Aspetto il parere di Davide.

2015-06-30 12:35 GMT+02:00 Simone S. <notifications@github.com>:

**Comment by predorock** [comment]
La pagina "preferenze" dell'utente necessita di mostrare i dettagli di una offerta, con il relativo progresso. Se non ho questi dati come faccio a fare la pagina delle preferenze?

L'API in questione io l'ho richiamata così : ```http://localhost/foowd_alpha2/api_foowd/public_html/api/prefer?ExternalId=37&type=search``` e mi restituisce i dati relativi all'associazione utente -> preferenza, che per quanto significativi e utili io lato frontend non me ne faccio nulla, solo di quelli.

**Comment by coder-molok** [comment]
... quindi devi integrare i dati e, come giustamente hai scritto
all'inizio, fare una chiamata per ogni prodotto è troppo oneroso.
Ma farne solo un'altra con la lista degli OfferId ottenuti sarebbe così
terribile?

M

Il giorno 30 giugno 2015 12:46, Marco <notifications@github.com> ha scritto:

**Comment by Panciz** [comment]
direi che l'ideale sarebbe otterenere tutto con una sola chiamata.
Stiamo parlando delle preferenze inserite da un singolo utente siamo
nell'ordine delle decine penso quindi non ci dovrebbero essere problemi a
fare una join tra le tre tabelle Cliente/Prefeerenze/Offerte

Davide

2015-06-30 13:06 GMT+02:00 Marco Colombo <notifications@github.com>:

**Comment by coder-molok** [comment]
Daccordo. Simone puoi definire al volo il formato di I/O così poi lavorate in parallelo?

**Comment by SimoSca** [comment]
Sul formato I/O io e marco ci siamo accordati ieri sera.
