### ISSUE TITLE
Responsiveness Pagine

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#76]
TUtte le pagine fatte al di fuori di Elgg dovrebbero essere resposive.
In particolare:

* Barra in alto diventa da una riga divisa in due a due righe distinte
* Le colonne del wall diventano singole
* Altri eventuali riallinamenti per rendere fuibile la schermata anche a schermi piccoli
* pulsanti per inserimento preferenze sotto barra rpeferenze

vedi 
https://github.com/coder-molok/foowd_alpha2/blob/master/doc/Grafics/foowd_web%20specifiche.pdf

pg 16

**Comment by predorock** [comment]
Ho fatto si che la pagina preferenze sia responsive. Ho fissato un breakpoint (limite dopo il quale il contenuto si riadatta) a 900px. Sto procedendo con la pagina delle preferenze. 
Non ho trovato nessuna indicazione per il wall.
