### ISSUE TITLE
Blocco preferenze su modifica offerta

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#77]
Quando e come si chiude l'offerta.

Cosa fare riguardo le preferenze offerte.

Come e se avviwsare l'utente riguardo la modifica e la cancellazione?

**Comment by coder-molok** [comment]
Questa questione va discussa primariamente con Tommaso.

@Tommy: Le offerte hanno una scadenza e quando scadono, le relative
preferenze potrebbero non essere diventate ordini.
Cosa farci?
--Molok-- questa è la mia proposta, va confermata:
Vanno "archiviate", ma l'utente deve poter accedere e vedere le preferenze
date ad offerte scadute.
Dal profilo personale, in fondo alla pagina, aggiungere un contatore di
"offerte scadute" che, a dispetto del nome, riporta solo le offerte
(scadute) collegate all'utente da preferenze.

Per la effettiva "pulizia" (cioè eliminazione da DB) penseremo poi.
----

M

Il giorno 19 giugno 2015 10:40, Davide Poletti <notifications@github.com>
ha scritto:

**Comment by Panciz** [comment]
Per ora cancelliamo le preferenze su rimozione offerta in modo da poter resettare facilemente il DB finche siamo in test.

**Comment by SimoSca** [comment]
opzione settata tramite `schema.xml`.

**Comment by DDDamage** [comment]
..è essenziale che la preferenza espressa per un'offerta non passi alla stessa offerta con parametri modificati (es. prezzo, quota)

Poi con la funzione "segui produttore" è possibile vedere le nuove offerte del produttore. Sarebbe buono giocarsi tutto con l'ordinamento del wall. Con tag (di cui devo approfondire il discorso) e like sui produttori

**Comment by SimoSca** [comment]
@DDDamage 
> ..è essenziale che la preferenza espressa per un'offerta non passi alla stessa offerta con parametri modificati (es. prezzo, quota)

puoi riformulare la frase?? 
Allo stato attuale le preferenze non modificano nulla in merito alla quota: a livello di codice sono due entità ben distinte che interagiscono, attualmente, soltanto incrementando o decrementando la preferenza in base ai click.

**Comment by DDDamage** [comment]
Dico che le preferenze espresse rimangano valide soltanto per quella offerta immodificata

**Comment by DDDamage** [comment]
Se viene modificata le preferenze si azzerano.
Se viene riproposta uguale dopo la sua scadenza le preferenze rimangono.

**Comment by Panciz** [comment]
io non la renderei modificabile l'offerta da un certo punto in poi. Al massimo ritirabile e poi se ne aggiunge un altra uguale.

Per gli utenti l'effetto sarebbe lo stesso: di colpo le loro preferenze sono azzerate.
Il produttore pero in questo modo si renderebbe conto piu chiaramente che sta facendo un operazione "speciale" che impatta su la possibilità di vendere sto prodotto visto che azzera le preferenze.

**Comment by DDDamage** [comment]
Se viene riproposta dopo la sua scadenza (senza chiusura anticipata), gli utenti che nn sono rientrati nel gruppo dovranno pur mantenere la preferenza, no?

**Comment by DDDamage** [comment]
Potremmo anche eliminare le scadenze per ora, sia chiaro. La questione è solo discostarsi da un listino fisso e che poi quando viene creato il gruppo i produttori non hanno la merce (già successo)

**Comment by Panciz** [comment]
Ok allora procediamo in questo modo.

Una volta pubblicata l'offerta puo essere modificata con molti vincoli.

1. Si puo cambiare la data di scadenza posticipandola (anche se passata)
2.  si potrebbe cambiare qt minima
3 AUMENTARE il massimo. (diminuendolo alcune preferenze verrebbero escluse)
4 solo DIMINUIRE il prezzo (non lo vendo allora lo sconto)


IIn breve Un produttore puo dire offro di piu, per piu tempo a di meno senza perdere le preferenze.
Non potra dire lo faccio pagare di piu, o ne offro di meno.
Chiaramente il prodotto rimane lo stesso!!!


Se si volesse effettuare altre modifiche si elimina l'offerta e se ne crea un altra.

Davide

**Comment by coder-molok** [comment]
Hai dimenticato "diminuire la quantità minima per la spedizione" o sbaglio?

Che corrisponderebbe a "non riesco a spedirne 10 per volta, proviamo con 5
per volta...

M
Il 24/lug/2015 17:19, "Davide Poletti" <notifications@github.com> ha
scritto:

**Comment by coder-molok** [comment]
Forse era il punto 2 ? l'ho interpretato ora...

Il giorno 27 luglio 2015 17:04, Marco Colombo <molok.del.drago@gmail.com>
ha scritto:

**Comment by DDDamage** [comment]
Ok, diciamo cosa non si può cambiare:
-Dimensione Quota
-Prezzo (eccetto sconti)

**Comment by DDDamage** [comment]
La soluzione a questa issue mummia è la seguente:
Quando viene modificata un'offerta gli utenti che la seguono ricevono una comunicazione via mail. 
Nella mail è contenuto il nome del campo aggiornato. In questo modo è possibile limitare il rialzo dei prezzi e favorire sconti o altre azioni promozionali

**Comment by SimoSca** [comment]
La riprendo dopo tanto tempo, chiedo venia.
Riassumendo, una mia proposta di gestione sarebbe la seguente:

- fino a quando nessuno ha espresso preferenze sull'offerta, questa potrebbe essere modificabile in qualunque parte

- una volta che sono state espresse preferenze modificabile ancora qualunque campo, ma in tal caso si avvisano gli utenti che ne hanno espresso preferenze (direi solo quelle non ancora acquistate, ovvero in stato "newest" o "pending") con una mail e se la cosa risulta abbastanza fattibile, comunicare quale campo e' stato cambiato.

In quest'ultimo caso, sarebbe utile magari aspettare un'ora prima di mandare le mail: "Complimenti %produttore%, la tua offerta e' stata aggiornata con successo. Hai un'ora di tempo per svolgere altre modifiche prima che gli utenti che seguono questa offerta vengano aggiornati in merito ai cambiamenti apportati."

Che ne pensate?

**Comment by DDDamage** [comment]
Va benissimo, magari manda a fede la bozza della mail così la revisiona

**Comment by coder-molok** [comment]
Non sono convinto del "qualunque campo", comunque inutile perdere tempo
adesso.
Va bene come hai descritto tranne che:

Precisazioni:

ogni modifica resetta il conto di un'ora di tempo? direi di sì.

Se c'è un ordine in attesa di conferma (le 24h di attesa) le preferenze
sono in che stato? pending?
Queste non dovrebbero cambiare, creerebbero troppa confusione (immagina una
modifica fatta a un'ora e un minuto dalla fine delle 24 ore... )
Quindi in caso esistano preferenze in pending, al produttore mostrerei
PRIMA del form di modifica, un messaggio tipo:
"*un'ordine è in attesa di partire e il prodotto non può essere modificato*"

*oppure *alla modifica del prodotto, le 24 ore vanno resettate.

Direi che per il momento puoi adottare la modifica più immediata
(reimpostazione delle 24 ore?)

Marco


Il giorno 1 novembre 2015 13:45, DDDamage <notifications@github.com> ha
scritto:

**Comment by DDDamage** [comment]
In ogni caso.. questa issue non è urgente.. tant'è che aggiunge nuove possibilità

Sarebbe meglio aver concluso tutto il resto prima di aggiustare questo dettaglio.

**Comment by SimoSca** [comment]
@coder-molok :

concordo con le tue osservazioni, tant'e' che questa e' proprio una scelta amministrativa che spetta a voi.

Le mie proposte sono "grossolane", nel senso di "aggiungere un piccolo step": infatti la modifica di un'offerta non e' cosa da poco, specialmente se ci sono gia' ordini in atto.

Allo stato attuale **TUTTO** e' modificabile: volevo rammentarlo nel caso in fase ti test emergano problemi attribuibili a questo (ad esempio ordino a 20 euro ma nelle 24h il produttore alza il prezzo a  30euro : in tal caso l'ordine conteggia le quote a 30 euro).

**Comment by SimoSca** [comment]
Alla luce della rimozione dell'iter delle 24h, vi chiedo cortesemente di specificarmi i vincoli da inserire nella modifica dell'offerta. 
Nello specifico:
per ogni campo presente nel form dell'offerta, vi chiedo di dirmi se e' modificabile o meno, ed i relativi vincoli. ad esempio

    titolo -> non dovrebbe essere modificabile

oppure

    prezzo -> modificabile solo se non vi sono preferenze su esso

Non e' urgente, ma dato che ormai siamo ad una fase concreta, penso sia il caso di parlarne.

**Comment by DDDamage** [comment]
La soluzione più rapida è mettere un avviso: "Attenzione, modificando questa offerta le quote prenotate dai consumatori saranno azzerate. Procedere?"

E ad una qualsiasi modifica si azzerano le quote.

**Comment by SimoSca** [comment]
Se la volete cosi' non ho problemi.

Magari agli utenti che hanno espresso la preferenza si potrebbe mandare una mail avvisandoli che quell'offerta ha subito delle modifiche, elencando le modifiche apportate e il numero di preferenze che erano state espresse prima dell'azzeramento, che ne pensi?
Se ti garba, allora come al solito chiedo solamente di scrivermi il prototipo del testo.

Inoltre, ma secondario, potrebbe essere utile impostare un timer: inviare le mail solamente a un tot di minuti (ad esempio 30) dall'utlima modifica.

**Comment by coder-molok** [comment]
Sono d'accordo con le proposte che avete fatto, ma per semplificare molto,
al momento, bloccherei tutto.

Aggiungerei sulla pagina dell'offerta lato produttore un avviso:
"Nel caso volesse apportare modifiche all'offerta ci contatti rapidamente
via mail (clicca qui)."
con un link "mailto" che abbia già l'oggetto "Modifica offerta xxxx (id:
yyyy)"

In questo modo possiamo valutare per i primi casi che modifiche chiedono e
se è il caso di avvisare chi ha espresso preferenze ed al limite azzerare
le stesse...

Marco

Il giorno 13 gennaio 2016 23:12, Simone S. <notifications@github.com> ha
scritto:

**Comment by SimoSca** [comment]
Quello che preferite voi.

Immedesimandomi però penso che almeno durante il primo inserimento una o due modifiche alla descrizione vengono fatte. 
Ad esempio da utente farei così:

1. scrivo la descrizione e salvo
2. vado nella pagina dell'offerta e guardo se il testo scritto in quel modo mi piace, e trovo eventuali errori da correggere
3. la prima volta quasi sicuramente trovo qualcosa che non mi garba e decido di modificare la descrizione

Pertanto mi sento di suggerire questo: 
fin quando sull'offerta non vi sono preferenze direi di considerarla completamente modificabile, e invece far apparire il "mailto" proposto da molok per evitare l'azzeramento automatico qualora vi siano già preferenze espresse.

**Comment by coder-molok** [comment]
Sono d'accordo. Modificabile finché ha 0 (zero) preferenze (attive, se sono tutte "evase" si può modificare)

Nel messaggio per il produttore specifichiamo "Alcuni utenti sono interessati all'offerta, quindi per modificarla ..."

**Comment by SimoSca** [comment]
Per evase intendi sia quelle inerenti ordini prenotati che ordini conclusi, giusto?

**Comment by coder-molok** [comment]
Intendevo quello, ma mi sono reso conto che noi non salviamo una "prenotazione" con i dati attuali al momento della conferma, quindi occorre mantenere le informazioni invariate finché l'ordine non è concluso.

**Comment by SimoSca** [comment]
Volendo al momento della prenotazione possiamo inserire nella mail il resoconto dell'offerta con tutti i dettagli, e magari inviare una mail di aggiornamento al produttore (in modo che anche lui sia sicuro dei dati relativi all'offerta).

Per rendere tutto piu semplice, volendo potremmo semplicemente inserire il resoconto dell'offerta come allegato in tutte le mail.

**Comment by DDDamage** [comment]
Stiamo mettendo un po' troppa carne al fuoco con sta cosa..

**Comment by DDDamage** [comment]
Offerta senza preferenze: modifica libera
Offerta con preferenze: modifica con azzeramento preferenze (avviso produttore)
Offerta con ordine preso in carico: modifiche non possibile (avviso produttore)

Non sbattetetevi troppo lato ux perchè sono eventi particolari che pochi utenti si troveranno di fronte. E se non si accorgono di nulla ancora meglio. Es. se un produttore modifica un'offerta che seguo e non me la ritrovo nel board massimo dico "ah credevo di aver messo delle quote" e finisce lì..

**Comment by SimoSca** [comment]
Prima di partire col completamento di questa fase vi chiedo solamente di confermarmi quale tra le varie opzioni trattate volete che venga applicata.

In ogni caso @DDDamage , relativamente a

> Es. se un produttore modifica un'offerta che seguo e non me la ritrovo nel board massimo dico "ah credevo di aver messo delle quote" e finisce lì..

condivido una mia osservazione che riguarda siti di e-commerce tipo ebay: visto che lo uso sporadicamente, per me perdere un'offerta dalla board equivale praticamente a perderla del tutto. Difficilmente ricordo l'offerta specifica che stavo seguendo, pertanto senza una traccia nella board probabilmente non la ripescherei piu.

Attualmente a livello di database quando una preferenza raggiunge zero quote viene automaticamente eliminata, pertanto con questo metodo se ne perde completamente la traccia.


Attendo vostra decisione per completare questa issue.

**Comment by coder-molok** [comment]
Propongo la soluzione perfetta:
- modifica libera finché ho zero preferenze.
- modifica libera con preferenze, ma i follower ricevono mail di notifica
della modifica (che parte un'ora dopo la modifica, per evitare che ne
partano diverse se un produttore cambia-salva-cambia-salva...)(1)
- offerta vincolata completamente in caso di ordine effettuato.

(1) Simone, è grossomodo una soluzione che hai proposto tu, quindi immagino
sia di facile realizzazione.
Si riesce però a tenere traccia delle modifiche effettuate? In modo da
informare il cliente di cosa è stato modificato, se prezzo o descrizione o
altro?

In questo modo
- non andiamo a cancellare preferenze
- tuteliamo il consumatore
- non vincoliamo eccessivamente il produttore
- teniamo il contatto coi clienti ricordandogli che hanno espresso
preferenze e che siamo sempre lì

@Tommy, se confermi che sei d'accordo Simone può chiudere la issue...
Il 16/gen/2016 00:02, "Simone S." <notifications@github.com> ha scritto:

**Comment by DDDamage** [comment]
Per me va bene, basta che non ci sprecate troppo tempo dietro..

**Comment by SimoSca** [comment]
La mia idea sarebbe di tenere traccia solo delle modifiche relative a offerte che hanno gia' preferenze e solo  fino allo scadere di un'ora dall'ultima modifica:
durante quest'arco di tempo i campi modificati dal form potrebbero apparire con uno sfondo diverso, in modo che il produttore possa ricontrollarli.
Al termine della scadenza si mandano al produttore e ai followers di quell'offerta delle mail di conferma e di notifica rispettivamente: in queste mail si potrebbero indicare esplicitamente i campi modificati, oppure rimandare direttamente al link dell'offerta modificata.

In ogni caso, terminato questo iter sarebbe mia intenzione perdere le tracce delle modifiche: non credo che allo stato attuale uno storico delle modifiche dell'offerta possa servire.

**Comment by SimoSca** [comment]
Un ultima cosa:

essendo praticamente ininfluenti, lascerei come sempre modificabili sia l'immagine che i Tags: 
specialmente l'immagine, avendo il crop, e' praticamente ingestibile anche per gli amministratori (altrimenti bisognerebbe imporre ai produttori di mandarci nuove immagini con delle specifiche, cosa che mi sembra piuttosto onerosa).

**Comment by DDDamage** [comment]
Considerate che questa discussione è nata in un momento in cui le funzionalità previste erano differenti (es. preferenze forzate).. Luglio 2015

Ora, questi dettagli non sono vitali (lo saranno solo quando la piattaforma inizierà a girare sul serio). Quindi rimandiamo la discussione a quando e se si presenterà il problema. Iniziamo a vedere se i produttori riescono a caricarle le offerte, prima di pensare ad ulteriori complicazioni ;)

**Comment by SimoSca** [comment]
Ho terminato tutti i check e i crontab per realizzare queste scelte.

Vi chiedo provate pure a modificare ordini in tutti i casi:

- non hanno preferenze
- hanno preferenze ma non hanno alcun ordine in carico
- hanno ordinazioni in carico

indicatemi, qui o per mail, come modificare i testi. @coder-molok : se vuoi possiamo fare come l'ultima volta: salvo tutti i testi in un file e tu provvedi a modificarli a tuo piacimento.
NB: per testi intendo sia quelli delle mail, che quelli che appaiono sotto il titolo dell'offerta, nella pagina delle modifiche di singola offerta.

Inoltre ho temporaneamente pensato di fare in questo modo: per il momento le voci relative ai campi modificate appaiono su un background di colore plum. Questo e' assolutamente temporaneo e ci lavoro nei prossimi giorni. 
Per renderlo semplice potrei semplicemente affiancargli un'icona che rappresenti lo stato di modifica.

**Comment by SimoSca** [comment]
Le pagine contenenti i messaggi, sia popup che d'avviso, e i testi delle mail li trovi rispettivamente:

- foowd_offerte/views/default/forms/foowd_offerte/update.php
- foowd_offerte/actionsfoowd_offerte/update.php
- foowd_utility/Uoowd/FoowdOffer.php

non ho avuto il tempo di organizzare bene i messaggi perche' mi premeva anzitutto sapere se come e' gestita puo' andare.
Per evitare di sparpagliare i messaggi, mi piacerebbe creare delle apposite funzioni in "foowd_utility/Uoowd/FoowdOffer.php", pertanto se vuoi domani provvedo a organizzare tutto qui dentro. Se invece vuoi fare direttamente te non mi oppongo :-)

**Comment by DDDamage** [comment]
Non riesco ad accedere alle pagine contenenti i messaggi di cui il tuo ultimo messaggio (link incompleto?)

**Comment by SimoSca** [comment]
Contengono il codice grezzo lato server: non vi puoi accedere dal browser.
Puoi visualizzarli contemplando i sorgenti del repository oppure visualizzare i contenuti qui su github:

- https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_utility/classes/Uoowd/FoowdOffer.php

- https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_offerte/actions/foowd_offerte/update.php

- https://github.com/coder-molok/foowd_alpha2/blob/dev/mod_elgg/foowd_offerte/views/default/forms/foowd_offerte/update.php
