### ISSUE TITLE
Unita misura come format

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#79]
Siccome l'unità di misura vuole essere una stringa a volte complesse direi che la soluzione migliore è che sia definibile come pattern.

Ad esempio

Bottigla da %d gr

%d Forma da 2Kg

in pratica si usa %d come segna posto per indicare dove mettere la quantità singola quota.

La visualizzazioine sarà fatta usando (Printf Php)[http://php.net/manual/it/function.printf.php] .
o altro in Js.

**Comment by SimoSca** [comment]
Perfetto, anzi di piu! 
Essendo abitutato col C e C++ mi trovo decisamente meglio a formattare le stringhe in quel modo.

Thanks
