### ISSUE TITLE
Creare una pagina personalizzata in elgg 1.8.20

### ISSUE THREAD

**Issue by predorock** [coder-molok/foowd_alpha2#8]
Ho cercato come creare una pagina personalizzata in elgg, ma la documentazione dell'ultima versione non mi sembra proprio fatta bene. 
Googlando ho trovato un tutorial per fare la stessa cosa ma con la versione di elgg 1.8.* , e seguendo il tutorial tutto funziona.
Ora bisogna capire quale versione di elgg è meglio utilizzare (magari in base alla qualità della documentazione , anche esterna) e nel caso cambiare alcune delle funzioni di elgg che ho utilizzato.
Non ho pushato il codice che ho scritto, in quanto non ho provato e non penso funzioni nella versione di elgg usata nel repo.
Intanto vi metto il link [link]( http://www.perjensen-online.dk/04/how-to-create-a-custom-page-in-elgg/) al tutorial

**Comment by coder-molok** [comment]
quindi se ho capito bene lo hai provato nella versione 1.8.20... e funziona.

Direi che la cosa migliore è caricare il tuo codice in un branch, poi
vediamo chi riesce a scaricarselo su una installazione del nostro ambiente
e provarlo.

M
Il 02/mar/2015 17:52 "Marco" <notifications@github.com> ha scritto:

**Comment by predorock** [comment]
Si Marco è proprio così.
Io ho una installazione in locale di elgg 1.8.20, e funziona. 
Il codice è esattamente quello del tutorial, forse creare un branch crea un po di confusione.
Comunque fammici lavorare un po, magari il problema è meno grave di quello che sembra, al massimo procedo come dici tu.

**Comment by Panciz** [comment]
Il tutorial di cui hai postato il link e' abbastanza vecchio sicuramente fa riferimento ad una veriosne vecchia di ELGG perche' la release che usiamo non era ancora uscita.

L'esempio e' buono ma non mi sembra cosi diverso dal tutorial [originale](http://learn.elgg.org/en/latest/tutorials/blog.html#the-object-view) quindi direi di usare come riferimento primario quello. Prorpio nei casi in cui quello non sia soddisfacente cercare altro.

In ogni caso anche senza postare tutto il codice inizia indicando che tipo di errore ricevi e spiegando meglio la problematica.

Guardando il codice del tutorial vedo subito una funzionalita che non non possiamo usare nel file 
`pages/custompage/index.php`

       $friends = elgg_list_entities_from_relationship($options);

infatti le offerte non sono nel database elgg e quindi dobbiamo procedere in un altro modo.

In ogni caso rimarrei comunque sulla versione 1.9 che mi sembra sia la release stable.

**Comment by predorock** [comment]
Ho capito qual'era il baco. Il campo href del menù deve avere lo stesso nome della cartella in cui è contenuta la pagina a cui si fa riferimento.
Funziona nella nuova versione.
