### ISSUE TITLE
layout wall larghezza e lunghezza colonne

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#80]
Il wall dovrebbe essere idealmente suddiviso in quattro colonne.

Le immagini presente nelle colonne dovrebbero avere tutte larghezza uguale ma di due size differenti. La ratio delle immagini e' o 3:2 o 2:3 in pratica o larghe e basse oppure strette e alte.
Sempre considerando che la larghezza dovra sempre essre uguale.

Vedi pg 3 https://github.com/coder-molok/foowd_alpha2/blob/master/doc/Grafics/foowd_web%20specifiche.pdf

Alcune inmmagini formato 2:3 quindi strette e lunghe potrebbero essere anche piu strette e non occupare tutta la colonna, vedi immagine in basso a dx.

**Comment by predorock** [comment]
ora il layout dovrebbe essere di 4 colonne con i margini DX e SX equidistanti dai bordi dello schermo

**Comment by predorock** [comment]
#93
