### ISSUE TITLE
Filtro in Board

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#81]
Filtrare solo le offerte per cui la quota minima e' stata raggiunta

**Comment by predorock** [comment]
Secondo me è meglio implementare questa cosa lato server. Io per fare il filtraggio comunque devo chiamare delle API.

**Comment by Panciz** [comment]
Si hai ragione, nel senso che è inutile caricare tutto per poi filtrarne solo alcuni.

Direi che si puo aggiungere un parametro alla search offer per ora, Poi possiamo pensare a crearne un ad hoc in futuro. Per ora aggiungi un parametro.

**Comment by SimoSca** [comment]
No problem, vi chiedo solamente di farmi un esempio di chiamata.
Come parametro opzionale potremmo utilizzare il nome `trigger` (o altro che vi possa piacere) e impostarlo a `true`.

In ogni caso per *quota minima raggiunta* si intende il fatto che **il totale delle preferenze su tutti gli utenti e relative a quell'offerta** superi la **quota minima** ?

**Comment by Panciz** [comment]
non su tutti gli utenti ma in questa fase il totale delle preferenze **dell'utente**  relative a quell'offerta superi la quota minima. 
Nella seconda fase secondo quanto abbiamo discusso dovrebbe diventare **degli amici dell'utente**

Giusto  @DDDamage ??

**Comment by DDDamage** [comment]
Ritrattare in relazione ai tag di ricerca
