### ISSUE TITLE
Pagina produttore

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#82]
Da pagina 13 a pagina 19 https://github.com/coder-molok/foowd_alpha2/blob/master/doc/Grafics/foowd_web%20specifiche.pdf

Da notare

* Carousell immagini.
* Preferenze totali espresse per produttore e altri totali per produttore

**Comment by predorock** [comment]
@DDDamage @Panciz online c'è un abbozzo della pagina produttore. In questi gionti finisco il carosello immagini e fixo gli altri bug

**Comment by DDDamage** [comment]
Ok magari aspetto a segnalare i bug però inizio a guardare

**Comment by predorock** [comment]
La pagina di per se è finita. Aspetto specifiche sulle immagini del carosello.

**Comment by DDDamage** [comment]
Le specifiche sono scritte in #117 #107

**Comment by DDDamage** [comment]
immagine 3:5
