### ISSUE TITLE
Set di icone sito

### ISSUE THREAD

**Issue by predorock** [coder-molok/foowd_alpha2#84]
Chiedere al grafico se è possibile avere lo stesso set di icone che utilizza lui, in modo tale che la riproduzione sul sito diventi più fedele.

**Comment by coder-molok** [comment]
Giro a Tommaso, che ha il contatto rapido col grafico.

Il giorno 30 giugno 2015 02:25, Marco <notifications@github.com> ha scritto:

**Comment by predorock** [comment]
Ha risposto anche a me. Lo sento domani tranquillo.
Marco P
