### ISSUE TITLE
Form e API  Produttore

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#85]
Il produttore deve poter aggiungere alla creazione.
Oltre ai campi utenti e' sono necessari:

- Ragione sociale
- Indirizzo
- num telefono
- mail
- P.Iva.
- Sito

Inoltre le immagine caribabili dovrebbero essere n (da 3 a 5).
Aggiunge i campi nel db, nelle API e nel form per gestire questi dati

**Comment by SimoSca** [comment]
Questi campi sono tutti obbligatori?

**Comment by Panciz** [comment]
Va bene ma non metterei obbligatori per gli utenti il numero di telefono e l'indirizzo.
Hai ragione a considerare i campi che compongiono indirizzo e numero di telefono per tutti, mentre sono  specifici dell'offertente P.Iva, Ragione sociale e list delle immagini per il carousell.

Iniziamo ad impostarla cosi poi  vediamo.

**Comment by SimoSca** [comment]
Perfect, thanks.
