### ISSUE TITLE
Correggere il campo content type nell'header

### ISSUE THREAD

**Issue by predorock** [coder-molok/foowd_alpha2#87]
Ho notato da un po di tempo che la console di chrome non mi visualizzava i dati JSON in modo corretto, ora ho capito perché. Il problema sta negli header delle risposte. 
```
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:690
Content-Type:text/html;charset=UTF-8
Date:Thu, 16 Jul 2015 13:01:18 GMT
Keep-Alive:timeout=5, max=99
Server:Apache/2.4.10 (Debian)
Vary:Accept-Encoding
````
come si può notare il content-type dell'header è text/html, si può correggere in appllication/json ?
Questo problema è generico per tutte le chiamate alle API che faccio.

**Comment by Panciz** [comment]
si per forza è corretto correggeren in `application/json`

**Comment by SimoSca** [comment]
Settato.
@predorock Vuoi che inserisca anche il `charset=UTF-8` o che imposti altri parametri?

**Comment by predorock** [comment]
si anche il charset=UTF-8 va bene.
Non sono troppo sicuro di quel content encoding = gzip.
Intanto credo sia meglio lasciarlo così, magari chiedo a @Panciz se può documentarsi su come e maglio fare.

**Comment by SimoSca** [comment]
Perfect.
Considera che a dire il vero non avevo messo mano agli header, pertanto escludendo il content-type, tutto il resto sono dei default.

**Comment by Panciz** [comment]
Allora charset e content type vanno bene.
vedi 
http://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type
http://stackoverflow.com/questions/9254891/what-does-content-type-application-json-charset-utf-8-really-mean 


L'encoding gzip è la compression , il messaggio viaggia zippato per migliorare le performance, vedi https://en.wikipedia.org/wiki/HTTP_compression . In pratica dipende da quello che il client dichiara di accettare, gzip è quello piu utilizzato.

**Comment by predorock** [comment]
fixed commit [5484642]
