### ISSUE TITLE
Inserimento prodotti - comparsa caratteri imprevisti

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#88]
Se nel selezionare l'unità di misura scelgo "decimetri cubi", mi visualizza "decimetri_cubi", l'errore persiste nel wall

![inserimento prodotti 1](https://cloud.githubusercontent.com/assets/13355694/8730095/3244140a-2bef-11e5-84d6-739d83f3f618.png)

PS: non riesco ad inserire la label

**Comment by SimoSca** [comment]
Risolta: le nuove offerte verranno salvate nel giusto formato.
