### ISSUE TITLE
Github - labels

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#89]
Bug nello strumento per segnalare i bug :P

Se provo ad aprire una nuova issue non mi compare la tendina a destra con varie opzioni tra cui le labels

![github](https://cloud.githubusercontent.com/assets/13355694/8730146/75386a04-2bef-11e5-8f4d-45309d31781e.png)

**Comment by Panciz** [comment]
Ho indagato e ho scoperto che le label possono essere inserite solo dai contributors.
http://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github-if-you-are-not-a-contributor-owner

I contributors di un progetto sono quelli che hanno inviato almeno una volta del codice, dovresti fare una finta commit. Probabilemente riesco a fartelo anche io per ora lascia un attimo stare la cosa delle label.
