### ISSUE TITLE
Versione Elgg 1.10

### ISSUE THREAD

**Issue by Panciz** [coder-molok/foowd_alpha2#9]
Verificare nuove feature e problemi nuova versione.

verificare effettiva compabilita' plugin

**Comment by Panciz** [comment]
Citando Simone su asana

>Per il momento il codice scritto risulta compatibile con la 1.10.3;
>Potrei creare i plugin sulla base della versione 1.9.7 e poi cercare di fixarli subito per renderli > >compatibili con la 1.10.

**Comment by SimoSca** [comment]
Confermo.

**Comment by SimoSca** [comment]
Già iniziato a lavorare su questa versione: credo che si possa chiudere la issue.
