### ISSUE TITLE
Wall - campo ricerca a schermo ridotto

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#90]
Browser: Waterfox (=Firefox 64 bit)

Se restringo lo schermo fino alla dimensione minima la scritta foowd_ e il campo di ricerca si incolonnano
![wall 1](https://cloud.githubusercontent.com/assets/13355694/8730242/f3e0db8e-2bef-11e5-98a4-7289b625ec53.png)

**Comment by predorock** [comment]
ok, come faccio in questo caso? come devo re-disporre gli elementi?

**Comment by Panciz** [comment]
Secondo me scritta e Foowd dovrebbero rimanere in alto e pulsanti passare in basso.

Oppure Scritta "Foowd" sopra barra di ricerca , sopra pulsanti : una sopra gli altri con la barra rosa che invitabilmente occupa piu spazio.

**Comment by DDDamage** [comment]
Dal documento "nuove specifiche web"

![barra navigazione responsive](https://cloud.githubusercontent.com/assets/13355694/8756756/d6ae435e-2cd4-11e5-8f26-9b9cce515967.png)

**Comment by DDDamage** [comment]
Da documento "nuove specifiche web"
![barra navigazione responsive](https://cloud.githubusercontent.com/assets/13355694/8756802/226b6024-2cd5-11e5-84d4-4940d31fc6fd.png)

**Comment by predorock** [comment]
il documento nuove specifiche web è sul repo? io non lo trovo, o meglio è presente solo, `foowd_web_specifiche.pdf`

**Comment by Panciz** [comment]
si e' quello pg 12

**Comment by predorock** [comment]
Ho capito, ma il primo screenshot e molto più piccolo. Ho bisogno almeno delle misure limite e anche di un design nel caso si restringa di più.

**Comment by coder-molok** [comment]
Marco, siamo praticamente alla larghezza di una immagine nel primo
snapshot. Le immagini sono fisse , no?
Quindi siamo a quanto ? 300px?
Il 19/lug/2015 17:24, "Marco" <notifications@github.com> ha scritto:

**Comment by DDDamage** [comment]
La larghezza minima a cui posso restringere il browser (firefox-waterfox) è 283 pixel o giù di lì (misurato a mano su photoshop)

**Comment by coder-molok** [comment]
Usando Midori su windows ho problemi simili al restringimento su cellulare,
potrebbe quindi essere un problema di direttive css non supportate?
![midori-foowd](https://cloud.githubusercontent.com/assets/8371887/10635264/c5166acc-77f7-11e5-85ee-6c70fa566e05.png)

**Comment by SimoSca** [comment]
Non posso dire nulla essendo questa parte lato frontEnd, ma per capire:

questo problema avviene nel momento in cui fai un resize della finestra o è presente di default, anche facendo un refresh della pagina?

**Comment by DDDamage** [comment]
Nell'esempio di molok (Midori) è presente di default anche con finestra allargata.

Nella mia esperienza accade:
- da cellulare (android) anche diminuendo lo zoom
- su desktop  (mozilla) quando restringo la pagina

**Comment by DDDamage** [comment]
Da rivedere assieme a tutta la visualizzazione mobile
