### ISSUE TITLE
Wall - elementi di navigazione

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#91]
Browser: Waterfox (=Firefox 64 bit)

Se restringo lo schermo fino alla dimensione minima,
gli elementi sulla destra passano nella barra rosa.
Per come era pensata la grafica responsive dovrebbero rimanere nella barra bianca che andrebbe a posizionarsi sotto quella rosa
![wall 2](https://cloud.githubusercontent.com/assets/13355694/8730331/651dd11c-2bf0-11e5-9bfb-f752447fcf42.png)

**Comment by predorock** [comment]
concettualmente ho capito che cosa intendi, @DDDamage c'è un documento grafico di riferimento per vedere bene come fare?

**Comment by Panciz** [comment]
vedi commento a https://github.com/coder-molok/foowd_alpha2/issues/90

**Comment by DDDamage** [comment]
Dal documento "nuove specifiche web"
![barra navigazione responsive](https://cloud.githubusercontent.com/assets/13355694/8756783/01395172-2cd5-11e5-9fe5-c30a1031f455.png)

**Comment by DDDamage** [comment]
Da rivedere assieme a tutta la visualizzazione mobile

**Comment by DDDamage** [comment]
Mi permetto di riaprire questa issue perchè risolvibile correggendo i soli fogli di stile.

Precisamente:

.navbar-section {   box-shadow: 0px 0px 20px 0px #F0F0F0;
}

#user-menu { margin: 12px 20px 0px 0px;
top: unset;
transform: unset;
}

![menu responsive](https://cloud.githubusercontent.com/assets/13355694/12864500/ead48dea-cc8c-11e5-827f-22134d77d569.png)

**Comment by SimoSca** [comment]
L'unica modifica che ho apportato e' il box-shadow in .navbar-section : le arte in google chrome non centravano verticalmente il #user-menu.

**Comment by SimoSca** [comment]
A fine 2015 la popolarita' dei browser risulta (dal piu diffuso al meno):

* chrome
* IE
* firefox
* safari
* opera

Avere la compatibilita' con tutti e' ardua e bisogna tenerne conto.

**Comment by DDDamage** [comment]
Senza modificare il css nella dello user menù sussistono i problemi di posizionamento del menù di navigazione 
![nav vert](https://cloud.githubusercontent.com/assets/13355694/12872755/80e9783a-cdab-11e5-8d0e-acf0a3fd5736.png)

**Comment by DDDamage** [comment]
Il div "id=user-menù" è già contenuto nel div "class=user-menù-section", quindi già di base viene posizionato correttamente.

I due parametri del CSS
- top: 50%
- tranform: translateY (50%)

Sono aggiunti ad hoc e non fanno altro che sballare quando le schermo viene ridotto (con lo schermo allargato non dà problemi per coincidenza nelle distanze).
Per il posizionamento verticale è sufficiente aggiungere un margine di 12px dall'alto, per posizionare lo user menù all'interno della sua sezione della barra.

Questo sistema il bug
> 
> #user-menu { margin: 12px 20px 0px 0px;
> top: unset;
> transform: unset;
> }
>

**Comment by SimoSca** [comment]
Ho applicato i cambiamenti: dimmi se cosi' va bene.

**Comment by DDDamage** [comment]
Perfetto così
![navigazione corretta](https://cloud.githubusercontent.com/assets/13355694/12923026/4ed1b4f2-cf54-11e5-9378-364e20d2c3b1.png)
