### ISSUE TITLE
Wall - pulsanti di dettaglio

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#92]
I pulsanti di dettaglio si posizionano uno sotto l'altro mentre dovrebbero essere affiancati
![wall 3](https://cloud.githubusercontent.com/assets/13355694/8730364/85e7ae4a-2bf0-11e5-850c-238cbb0c56c8.png)

**Comment by Panciz** [comment]
vedi comento a https://github.com/coder-molok/foowd_alpha2/issues/90
