### ISSUE TITLE
Wall - ridimensionamento immagini verticali

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#93]
Le immagini verticali nel wall hanno tutte la dimensione massima.

La maggiorparte dovrebbero avere una dimensione inferiore (grandi come quelle orizzontali) e solo alcune dovrebbero essere larghe tutta la colonna
![wall 4](https://cloud.githubusercontent.com/assets/13355694/8730423/d4440408-2bf0-11e5-9643-f2d74ea23e51.png)

**Comment by coder-molok** [comment]
Domanda da programmatore: in base a cosa + o - grandi?
Il 16/lug/2015 19:28, "DDDamage" <notifications@github.com> ha scritto:

**Comment by predorock** [comment]
Attualmente le immagini che vengono salvate nella cartella `medium` di ciascun utente sono tutte larghe 400px. Pur ritagliandone una nuova, riducendone molto la larghezza, risulta sempre un'immagine ingrandita di 400px. 
Al momento non posso verificare se con immagini più piccole il wall funziona effettivamente, se non sostituento a mano le immagini nella cartella in cui vengono salvate.
@SimoSca forse il crop delle immagini va impostato differentemente?

**Comment by predorock** [comment]
Il wall di per se funziona (ho provato a inserire un immagine a mano nella cartella). Ma bisogna aggiustare il crop

**Comment by SimoSca** [comment]
attualmente il crop relativo all'offerta viene impostato in proporzione 2:3 o 3:2, mentre per le dimensioni dimmi pure quali misure ti servono.

**Comment by DDDamage** [comment]
Le immagini sono sempre della stessa dimensione.
Quelle verticali vengono ridotte del 33% solo quando visualizzate nel wall.

Ogni 2 immagini verticali ridotte al 33% ne viene caricata 1 al 100%

**Comment by DDDamage** [comment]
Oppure:
Per ogni immagine verticale visualizzata al 100% altre due vengono visualizzate al 33%

**Comment by DDDamage** [comment]
Scusate avevo fatto casino. ..un momento che mi confronto con teo

**Comment by DDDamage** [comment]
In ogni caso, non è una questione di caricamento delle immagini ma della loro visualizzazione nel wall.

**Comment by Panciz** [comment]
come avevo scritto alla fine della issue https://github.com/coder-molok/foowd_alpha2/issues/80 alcune immagini possono essere meno larghe e non occupare tutta la colonna a disposizione.

Il problema è che se si scala l'immagine lo si fa anche per l'altezza non solo per la larghezza, altrimenti non mantieni il rapporto tra le dimensioni e distorci l immagine. Quindi ha ragione Simone a richiedere altre dimensioni.
