### ISSUE TITLE
Wall - barre di avanzamento

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#95]
Le barre di avanzamento delle preferenze nel wall sono complete anche quando la preferenza non ha raggiunto l'ordine minimo.
![wall 6](https://cloud.githubusercontent.com/assets/13355694/8730482/45c5ebfa-2bf1-11e5-8fac-40d30abf29ad.png)

**Comment by predorock** [comment]
Non è un problema relativo all'interfaccia in quanto la progressione è calcolata in base al rapporto tra preferenze espresse e quantità minima da raggiungere. @SimoSca le preferenze vengono calcolate individualmente o su tutti gli utenti? oggi ho fatto una call rapida con tommy e per ora valutiamo le preferenze sull'utente singolo rispetto al totale.

**Comment by SimoSca** [comment]
mi puoi scrivere la chiamata che svolgi?

**Comment by predorock** [comment]
Chiamata alle API :
```
Remote Address:5.196.228.146:80
Request URL:http://5.196.228.146/api_foowd/public_html/api/offer?type=search&ExternalId=37
Request Method:GET
Status Code:200 OK
```
Applicazione del template : 
```html
<span class="mini-progress-bar">
            <span class="mini-progress" data-unit="1" data-progress="{{totalQt}}" data-total="{{Minqt}}">
            </span>
</span> 
```

Script di riempimento della barra : 
```javascript
function fillProgressBars(){
	//valore in cui si trova il punto 0 della barra (immagine)
	var halfBar = -417;
	$('.mini-progress').each(function(i) {
	    var unit = $(this).data('unit');
	    var progress = $(this).data('progress');
	    var total = $(this).data('total');

	   var barSize = $(this).width();
	   var progress = (progress/total)*barSize;
	   progress = progress > barSize ? barSize : progress;	    
	  $(this).css('background-position-x', (halfBar + progress) + 'px');
	});
}
```

**Comment by SimoSca** [comment]
Tanto per capirci, la risposta sul mio DB locale e'

````
{
  "response": true,
  "body": [
    {
      "Id": 344,
      "Name": "lol",
      "Description": "<p>lkjljl<\\/p>",
      "Publisher": 37,
      "Price": 5,
      "Minqt": 6,
      "Maxqt": null,
      "Quota": 0,
      "Unit": "",
      "UnitExtra": null,
      "Created": "2015-06-09 17:25:53",
      "Modified": "2015-06-10 16:16:34",
      "State": null,
      "UserId": 612,
      "totalQt": 18,
      "prefer": [
        {
          "Id": 28,
          "UserId": 14,
          "Created": "2015-06-15T10:38:00Z",
          "Qt": 12,
          "Offer": {
            "Id": 344,
            "Name": "lol",
            "Description": "<p>lkjljl<\\/p>",
            "Publisher": 37,
            "Price": 5,
            "Minqt": 6,
            "Maxqt": null,
            "Quota": 0,
            "Unit": "",
            "UnitExtra": null,
            "Created": "2015-06-09T15:25:53Z",
            "Modified": "2015-06-10T14:16:34Z",
            "State": null,
            "totalQt": 18
          }
        }
      ],
      "Tag": "emilia"
    },
   {...},
   {...}
 ]
}
````

dove `@totalQt@` rappresenta il totale di preferenze (tra tutti gli utenti) espresse su quel prodotto, invece nell'oggetto `@prefer@` trovi la chiave `@Qt@`, che rappresenta la quantita' di preferenze espresse dallo specifico utente.
In pratica `@totalQt@` e' un campo che tiro fuori facendo una semplice somma algebrica tra numeri reali, mentre `@Qt@` e' proprio un field della tabella `prefer`: quello che in teoria andrebbe aggiornato al "click".

Se qualcosa non torna dimmi senza indugio: magari mi sono spiegato male.

In questo mio esempio la @Qt@ supera la @minQt@ perche' allo stato attuale non e' ancora delineato come comportarsi quando si raggiunge/supera la quota minima: credo faccia parte del prossimo step di sviluppo.

**Comment by SimoSca** [comment]
Guardando il tuo template, direi che ad occhio nel campo data-progress bisognerebbe aggiustare in modo da inserire `Qt` al posto di `totalQt`: non credo sia difficile estrarre dall'array prefer l'opportuno oggetto.

**Comment by predorock** [comment]
Il campo `Offer` veniva duplicato. Simone lo ha rimosso. Ora nel template anziché `totalQt` metterò `user.Qt`
