### ISSUE TITLE
Barra di progressione e prezzo se un utente e loggato oppure no

### ISSUE THREAD

**Issue by predorock** [coder-molok/foowd_alpha2#96]
Nella pagina di wall, in ciascun post del prodotto, abbiamo la barra di progressione che identifica il rapporto tra le `preferenze espresse dell'utente` e `la quantità minima da raggiungere` per poter effettuare un ordine. La stessa cosa e presente anche nella pagina di dettaglio nella barra rosa in alto a sx.

Ora se un utente non e loggato, caso quindi in cui ci sia un visitatore generico nel sito, io non posso avere per principio questi dati. Quindi, secondo un mio ragionamento, ne consegue che queste parti non devono essere mostrate. Devono comparire soltanto se un utente ha effettuato il login.

E' corretto o devo agire in modo diverso?
@Panciz @DDDamage

**Comment by DDDamage** [comment]
Esattamente.
Era una cosa che avevo già segnalato in passato ma non qua su github.
