### ISSUE TITLE
Redirect Elgg

### ISSUE THREAD

**Issue by predorock** [coder-molok/foowd_alpha2#98]
Sto cercando di spostare il sistema di redirect, lato elgg e sto avendo un problema nel redirect alla pagina profile. Praticamente, se non sono loggato e vado alla pagina del profilo (cambiando direttamente l'url) mi rimane sulla stessa pagina senza re-indirizzarmi sulla pagina di login.
@SimoSca tu che sei più pratico di me su elgg, come posso fare questa cosa

**Comment by SimoSca** [comment]
Quella pagina profilo (`<sito>/profile`) è una pagina di default di elgg. All'inizio pensavo che fosse cosa buona riutilizzarla, ma mi sono reso conto che riutilizzare parti di elgg è impegnativo e poco produttivo: probabilmente ne rifarò una nuova e piu adatta a noi.

Rispondendo: probabilmente in quella pagina ci dev'essere impostato `forward(REFERER)` che rimanda alla pagina su cui si era quando si prova a cambiare l'url.

Se vuoi che reindirizzi alla pagina del login lo faccio io lavorando sulla view di quella pagina.
