### ISSUE TITLE
Errore registrazione

### ISSUE THREAD

**Issue by DDDamage** [coder-molok/foowd_alpha2#99]
Non sono sicuro di come ho fatto a generare questo errore. 

Ho provato ad eseguire una nuova registrazione, mi ero dimenticato di inserire sito web e telefono.

Sono tornato indetro e ho inserito solo il telefono non il sito web.
Altri campi non compilati: immagini da inserire

Risultato: errore sconosciuto

![errore registrazione](https://cloud.githubusercontent.com/assets/13355694/8796354/7658e28a-2f94-11e5-84c2-fc3a7d17ceab.png)

**Comment by SimoSca** [comment]
attualmente le immagini sono obbligatorie solo per gli "offerenti", ma posso imporre che qualsiasi utente inserisca almeno un'immagine durante la registrazione, se preferisci.

**Comment by DDDamage** [comment]
Ah ok allora il bug è:
anche senza inserire l'immagine è possibile mandare la richiesta di registrazione. Negli altri campi restituisce l'errore sulla riga superiore al campo e non in una schermata successiva.

A questo punto credo che se non si inserisca alcuna immagine restituisca l'errore sconosciuto in alto a dx dell'immagine.
![registrazione errore1](https://cloud.githubusercontent.com/assets/13355694/8803025/d7b5128a-2fc4-11e5-80ef-12118bf3b1b5.png)

**Comment by coder-molok** [comment]
Sicuri non dipenda dall"essere tornato indietro"??

Da quanto dice Simone l'immagine non è richiesta per l'utente regolare...
Il 21/lug/2015 16:23, "DDDamage" <notifications@github.com> ha scritto:

**Comment by DDDamage** [comment]
Non ho idea posso riprovare a seguire la stessa procedura per generarlo nuovamente..

**Comment by Panciz** [comment]
o lo replichiamo o se ci dici quando l'hai fatto piu o meno cerchiamo di controllare se siamo fortunati con i log.

**Comment by DDDamage** [comment]
Provo a replicarlo, ma devo effettuare una nuova registrazione, vedi  #110

**Comment by SimoSca** [comment]
Sicuramente è perchè sei tornato indietro: per qualche strano motivo elgg mantiene questi messaggi.
Appena posso, vedo di personalizzare questa procedura di elgg.
